### ISSUE TITLE
GRPC BLOCKED

### ISSUE THREAD

**Issue by zt9788** [elastic/apm-agent-java#2091] opened 2021-08-27 07:34 UTC
When the client concurrency is large, blocked may occur

## Describe the bug

APM 1.24.0/1.25.0 
production environment：

```
"http-nio-8080-exec-3" #334 daemon prio=5 os_prio=0 tid=0x00007f3644c87000 nid=0xf94c waiting for monitor entry [0x00007f36394ac000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at co.elastic.apm.agent.bci.ElasticApmAgent.ensureInstrumented(ElasticApmAgent.java:723)
        - waiting to lock <0x00000007363a43f8> (a java.lang.Class for co.elastic.apm.agent.bci.ElasticApmAgent)
        at co.elastic.apm.agent.bci.DynamicTransformerImpl.ensureInstrumented(DynamicTransformerImpl.java:30)
        at co.elastic.apm.agent.concurrent.JavaConcurrent.captureContext(JavaConcurrent.java:107)
        at co.elastic.apm.agent.concurrent.JavaConcurrent.withContext(JavaConcurrent.java:102)
        at co.elastic.apm.agent.concurrent.ExecutorInstrumentation$ExecutorRunnableInstrumentation.onExecute(ExecutorInstrumentation.java:115)
        at java.lang.invoke.LambdaForm$DMH/2146388121.invokeStatic_LL_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/132577100.linkToTargetMethod(LambdaForm$MH)
        at io.grpc.stub.ClientCalls$ThreadlessExecutor.execute(ClientCalls.java:755)
        at io.grpc.internal.DelayedClientCall.drainPendingCalls(DelayedClientCall.java:295)
        at io.grpc.internal.DelayedClientCall.setCall(DelayedClientCall.java:152)
        at io.grpc.internal.ManagedChannelImpl$RealChannel$PendingCall$1.run(ManagedChannelImpl.java:1101)
        at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:740)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
        at com.xxxxServiceGrpc$com.xxxxServiceBlockingStub.someMethod(com.xxxx.java:6820)
        at sun.reflect.GeneratedMethodAccessor1139.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.xxxxxxGrpcClient.invoke(com.xxxxxxGrpcClient.java:72)
        at com.xxxxxxx.RpcClientProxy.invoke(RpcClientProxy.java:52)
        at com.sun.proxy.$Proxy793.somemethod(Unknown Source)

```

## Steps to reproduce

I make a @Test (when I use apache common pool2 to create channel ,the thread alway to be BLOCKED)
```
channel = ManagedChannelBuilder.forAddress(..........)
                .usePlaintext()
                .keepAliveWithoutCalls(true)
                .maxInboundMessageSize(Integer.MAX_VALUE)
                .idleTimeout(grpcConfig.getPool().getTimeBetweenEvictionRunsMillis(),TimeUnit.MILLISECONDS)
                .directExecutor()
                .build();
        blockingStub = com.xxxxx.newBlockingStub(channel);

public Stub getConnection(){return blockingStub}

for(int i=0;i<40;i++) {
            xxxxx finalClient = client;
            new Thread(TtlRunnable.get(new Runnable() {
                @SneakyThrows
                @Override
                public void run() {
                    for(int m=0;m<10;m++) {
                            new Thread(new Runnable() {
                                @SneakyThrows
                                @Override
                                public void run() {
                                    for(int j=0;j<10;j++) {
                        GrpcRequest.Builder reqB = GrpcRequest.newBuilder();
                        reqB.....                       
                                        GrpcResponse response =  finalClient.getConnect().withDeadlineAfter(3000L,TimeUnit.MILLISECONDS).test(reqB.build());

                                        System.out.println(JsonFormat.printer().print(response));
                                    }
                            }
                        }).start();


                    }
                }
            })).start();
```

## Debug logs

<details>
<summary>Click to expand</summary>

```
all thread will show this when I take apm
-javaagent:elastic-apm-agent-1.25.0.jar
-Delastic.apm.profiling_inferred_spans_excluded_classes=com.alibaba.nacos
-Delastic.apm.enable_log_correlation=true
-Dlog_level=debug
(if use apache common pool2 to getPool(new channel) and returnObject ,the Thread will blocked always)


Exception in thread "Thread-155" io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: ClientCall started after deadline exceeded. Deadline exceeded after -7.512103600s. 
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at com.xxxxServiceGrpc$com.xxxxBlockingStub.testmethod(Edu100CrmhqServiceGrpc.java:1800)
	at testGrpc$2$1.run(TestThirft.java:226)
	at java.lang.Thread.run(Thread.java:745)
```

</details>

**Comment by eyalkoren** [comment] 2021-08-29 07:57
Thanks for reporting!

The fact that a thread (or many threads) are blocked on a monitor is not a bug in itself, it could be an indication for proper synchronized execution, where only one thread can enter the synchronized section at any given moment, which means that other threads will be blocked on the synchronization monitor in a state of contention. 

The specific [synchronized section](https://github.com/elastic/apm-agent-java/blob/f9267ff7fc7df619cb2272b8790fde618055c8f6/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java#L722-L757) causing this thread blockage is guarded by a double-locking section to ensure that this contention is only effective at startup time, so we need to see what's not working properly in this case.

A negative effect of this synchronization may be one of the following:
- a delay (and timeout as it seems here) in some requests only on startup time, not visible after some warmup
- a delay in all requests, even after the app was given several minutes to warm up
- a complete hang of the application

So firstly, please let us know which of the above best describes the issue.

If it's the latter, it may indicate we cause a deadlock, in which case we will need a complete thread dump taken while the application is hang. You can provide it through [gist](https://gist.github.com/).

If it's one of the former, we need to see why this takes so long. I am not sure I understand what this means:
```
Deadline exceeded after -7.512103600s.
```
What does a negative measurement mean? Is it because it counts deadline (i.e. a point in time) instead of timeout?
Can you change the configuration causing this timeout, possibly even for the warmup time, to allow long execution only for the first requests?

For further investigation: it may make sense to exclude the `io.grpc.stub.ClientCalls$ThreadlessExecutor` from our concurrent plugin instrumentation. The gRPC span's context is transferred through the gRPC instrumentation, so if, for example, this executor only runs tasks when the spans are active (e.g. during the execution of `io.grpc.ClientCall#start`), then we don't need it.

**Comment by zt9788** [comment] 2021-08-30 02:13
Hi, this is the full thread dump
When the program is just started, the probability of blocked is relatively high
JDK1.8
apm1.24
[https://gist.github.com/zt9788/d1a376252dc712df2285e1619e37e79f](url)

**Comment by zt9788** [comment] 2021-09-01 08:09
@eyalkoren 
I try to use apm1.25-SNAPSHOT in product environment today ,there is also blocked threads 
-D......
-Delastic.apm.enable_log_correlation=true 
-Delastic.apm.enable_experimental_instrumentations=true 

I used Thrift(RPC)  before. Now I'm going to switch to grpc, so I use the  proxy to execute grpc. When I don't use APM, the program is no BLOCKED .  I create a pool to mangerment grpc channel ,and use borrowObject to got the grpc stub 

this is the full thread dump 
[logs](https://gist.github.com/zt9788/13fe8d74f617bd0747e90071595f3c94)

**Comment by SylvainJuge** [comment] 2021-09-02 10:06
From the stack trace, we see that lots of time is spent on `executor` instrumentation, which instruments `Runnable` instances at runtime. This could very likely be a side effect of your load testing strategy that is not waiting at all between every client test.

Could you try if that makes a difference by setting `-Delastic.apm.disable_instrumentations=executor` ?
This instrumentation is usually required for context propagation, here I just wan to know if the performance issue is related to this or not.

**Comment by SylvainJuge** [comment] 2021-09-02 11:46
To be a bit more clear, from the thread dumps the issue is more a *contention issue* and not a *deadlock*, which means that the numerous calls to `ensureInstrumented` are blocking each other due to an exclusive lock and only one thread is allowed to proceed, hence blocking other threads.

My current hypothesis is related to the `executor` plugin, which instruments classes that instrument `Runnable`, in the case of gRPC there might be an implementation detail (like plenty of subclasses or lambda) that make this instrumentation take longer than expected or be called many times. If disabling the `executor` plugin resolves the performance issue, it means we are on the right track for further investigation.

**Comment by zt9788** [comment] 2021-09-03 03:04
I think you're right，I was use the [transmittable-thread-local](https://github.com/alibaba/transmittable-thread-local/blob/master/README-EN.md) to record custom traceid before，but when i use grpc ,
It will BLOCKED thread ,so i drop the it to use default thread pool.
I saw a article, it is may have the same proplem.
The author used   `parallelStream` `ForkJoin` `ForkJoinPool` then the program BLOCKED too.  It may `transform` the  classes repeatedly It takes longer and longer ,so the author give a solution add  the code of  `appliedInstrumentations = getOrCreate(classToInstrument);` in `ElasticApmAgent.java:727` 

PS:
Yesterday I tried to disable the grpc plugin in the test code  but the problem still exists;

**I just tried `-Delastic.apm.disable_instrumentations=executor` in my test code , It looks OK.(there has no DEADLINE_EXCEEDED exception)
i will try it in my production env Later**

**Comment by zt9788** [comment] 2021-09-03 09:36
@SylvainJuge 

Hi, I used the `-Delastic.apm.disable_instrumentations=executor`  there is also BLOCKED the thread at production env.
full thread dump :
   [logs](https://gist.github.com/zt9788/af8a2995e1dd26b0244477810d5debf0)


In addition I try to use one pool catch the BLOCKED like this(there is about 4,5 threads blocked),It can recover  in few seconds(I have no enough time to  save the complete thread stack):
```
"TaskThreadPool-Async-Executor8" Id=255 BLOCKED on java.lang.Class@7f31245a owned by "grpc-default-executor-7" Id=313
    at co.elastic.apm.agent.bci.ElasticApmAgent.ensureInstrumented(ElasticApmAgent.java:723)
    -  blocked on java.lang.Class@7f31245a
    at co.elastic.apm.agent.bci.DynamicTransformerImpl.ensureInstrumented(DynamicTransformerImpl.java:30)
    at co.elastic.apm.agent.grpc.ChannelInstrumentation$ChannelAdvice.onExit(ChannelInstrumentation.java:88)
    at java.lang.invoke.LambdaForm$DMH/172223696.invokeStatic_LL_V(LambdaForm$DMH)
    at java.lang.invoke.LambdaForm$MH/2012744708.linkToTargetMethod(LambdaForm$MH)
    at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
    at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:911)
    at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
    at xxxxxx.service.YyyyyServiceGrpc$YyyyyServiceBlockingStub.grpcPing(YyyyyServiceGrpc.java:1709)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at xxxxxx.client.impl.DefaultCrmhqGrpcClient.invoke(DefaultCrmhqGrpcClient.java:65)
    at xxxxxx.client.AbstractDefaultGrpcClient.validateObject(AbstractDefaultGrpcClient.java:63)
    at xxxxxx.client.DefaultGrpcClientFactory.validateObject(DefaultGrpcClientFactory.java:86)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:477)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
    at xxxxx.yyyy.getStub(yyyy.java:86)
    at xxxxx.yyyy.updateCrmRecordByThrfit(yyyy.java:216)
    at xxxxx.yyyy.updateCrmRecord(yyyy.java:172)
    at xxxxx.yyyy$$FastClassBySpringCGLIB$$458aa19d.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
    at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
    at org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$1563/1935081145.call(Unknown Source)
    at co.elastic.apm.agent.concurrent.JavaConcurrent$CallableLambdaWrapper.call(JavaConcurrent.java:235)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

```

**Comment by SylvainJuge** [comment] 2021-09-08 14:20
Hi @zt9788 ,

Since disabling either `grpc` or `executor` instrumentations did not changed much what you observed here, I think that the issue would be likely related to high contention (and not be something specific to those plugins). Your test program shown here just starts 400 threads, and each of them is executing 10 gRPC client requests, which is definitely very aggressive without any kind of warmup.

Just to confirm this hypothesis, could you try to do the following:
1. modify your client program to have a "warmup" phase where a few requests are executed (only a single thread)
2. slowly increase the number of threads once the warmup phase is completed

Since all your application classes will be loaded by the warmup, there should not be any extra call to the `ensureInstrumented` method when executing the second step, and thus performance should be better.

**Comment by zt9788** [comment] 2021-09-09 05:54
@SylvainJuge 

Thanks very very much. This is indeed the reason for the blocking of threads. I  warmup grpc and now  it is normal in the production environment.

In order to be compatible with the common-pool2 written by thrift, I didn't expect that the socket connection was not created when the stub was created.

Because of the problems caused by our code quality, thank you again.

We will observe the production environment for a week. If the problem does not recur, we will close this issues.
Thanks again.

**Comment by SylvainJuge** [comment] 2021-09-09 07:19
Thanks for your feedback!

Load testing is definitely a tricky subject thus it's quite common to have such issues.

I'll close this issue for now, and we can re-open/comment if needed within a week.
Doing it this way allows to minimize the number of open tasks we have and you don't have to remember updating/closing the issue. If there is still an issue you can still comment on the issue and we can re-open it.

**Closed by SylvainJuge** 2021-09-09 07:19 UTC
Labels: agent-java, community, triage

**Comment by eyalkoren** [comment] 2021-09-29 09:45
@zt9788 we just created a concurrency improvement related to the issue reported here in #2150.
If it's not too much trouble, can you restore the former test scenario (without any warmup) and see whether the observed issue is eliminated? That would be very useful info for us and other users.

**Comment by zt9788** [comment] 2021-10-08 02:08
@eyalkoren Sorry, I just saw it. I'm on vacation recently. I'll come back and test it in a few days

**Comment by eyalkoren** [comment] 2021-10-13 07:03
Thanks a lot for trying it out and sharing!! ❤️ 
Causing seconds-worth delays on startup still sounds troubling, but if it's good enough for you as it is, I will live it for now.
Let me know if you have any additional info I can look into, for example - a thread dump taken in the blocked state with the snapshot version.
