### ISSUE TITLE
WebFlux - transaction has status code 200 where it should be 500

### ISSUE THREAD

**Issue by sangkyunkim89** [elastic/apm-agent-java#1939] opened 2021-07-28 04:27 UTC
1. spring version 2.2.6 webflux, netty
```
    @Operation(
        summary = "상품 이미지 검색", description = "상품 이미지 검색 api", responses = {
            @ApiResponse(responseCode = "200", description = "상품 이미지 검색 성공", content = @Content(schema = @Schema(implementation = GoodsDTOV1.ImageResponse.class))),
            @ApiResponse(responseCode = "404", description = "상품 이미지 검색 실패", content = @Content(schema = @Schema(implementation = GoodsDTOV1.ImageResponse.class)))
        }
    )
    @GetMapping("/goods")
    @ReactorCacheables(cacheNames = CacheNameConstant.GOODS_IMAGE_LIST, key = "getCacheKey(#method)")
    public Mono<ResponseDTOV2> getGoodsList(@ParameterObject @ModelAttribute @Valid GoodsDTOV1.Search goods) {
        return goodsService.getGoodsList(goods.getUrl(), ImageSearchTypeEnum.getValue(goods.getImageSearchType()))
            .flatMap(goodsImageVO -> {

                final GoodsDTOV1.ImageResponse imageResponse = goodsMapStruct.toDTO(goodsImageVO);

                if (1 == 1) {
                    throw new RuntimeException();
                }

                return Mono.just(
                    ResponseDTOV2.builder().data(imageResponse).build()
                );
            });
    }


Obviously a status 500 internal server error occurred.
In elastic-apm it comes out as 200

```
![image](https://user-images.githubusercontent.com/65607130/127263894-cb53cc26-b267-4499-933e-9a829ec9e95a.png)

![image](https://user-images.githubusercontent.com/65607130/127264120-f4f3d0d2-67fa-4344-b5ba-2360969e0488.png)

404 is normal
![image](https://user-images.githubusercontent.com/65607130/127264186-dabdf079-591a-469b-a5de-55b2471c29ca.png)

**Comment by eyalkoren** [comment] 2021-07-28 14:33
Closing as duplicate of #1938

**Closed by eyalkoren** 2021-07-28 14:33 UTC
Labels: agent-java, community
