### ISSUE TITLE
Bytecode instrumentation does not respect ClassLoader

### ISSUE THREAD

**Issue by apangin** [elastic/apm-agent-java#1606] opened 2021-01-07 23:10 UTC
After adding elastic-apm-agent-1.19.0 to a Java application, I start getting the following exception:
```
java.lang.ClassCastException: org.apache.cassandra.concurrent.JMXEnabledThreadPoolExecutor cannot be cast to org.apache.cassandra.concurrent.TracingAwareExecutorService
	at org.apache.cassandra.concurrent.StageManager.getStage(StageManager.java:158)
	at org.apache.cassandra.net.MessagingService.receive(MessagingService.java:582)
	at org.apache.cassandra.net.async.MeteredMessageInConsumer.receive(MeteredMessageInConsumer.java:41)
	at org.apache.cassandra.net.async.connection.In.doPayload(In.java:395)
	at org.apache.cassandra.net.async.connection.In.receive(In.java:438)
	at org.apache.cassandra.net.async.connection.In.receive(In.java:50)
	at one.actor.Actor.run(Actor.java:82)
	at one.actor.Dispatcher.execute(Dispatcher.java:54)
	at one.actor.Actor.tryScheduleToExecute(Actor.java:223)
	at one.actor.Actor.enqueue(Actor.java:129)
	at org.apache.cassandra.net.async.connection.In.access$600(In.java:50)
	at org.apache.cassandra.net.async.connection.In$1.completed(In.java:214)
	at org.apache.cassandra.net.async.connection.In$1.completed(In.java:181)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The only difference is one JVM option: `-javaagent:/path/to/elastic-apm-agent-1.19.0.jar`. The application works fine without this option.

JDK 8u265, Linux or Windows.

The logs from the agent:
```
     [java] 2021-01-04 23:41:24,854 [main] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
     [java] 2021-01-04 23:41:25,083 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.19.0 as Launcher on Java 1.8.0_265 Runtime version: 1.8.0_265-b01 VM version: 25.265-b01 (BellSoft) Windows 10 10.0
     [java] 2021-01-04 23:41:37,125 [main] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING state
     [java] 2021-01-04 23:41:39,340 [elastic-apm-server-healthcheck] WARN  co.elastic.apm.agent.report.ApmServerHealthChecker - Elastic APM server http://localhost:8200/ is not available (Connection refused: connect)
     [java] 2021-01-04 23:41:41,369 [elastic-apm-remote-config-poller] ERROR co.elastic.apm.agent.configuration.ApmServerConfigurationSource - Connection refused: connect
     [java] 2021-01-04 23:42:09,260 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Error trying to connect to APM Server. Some details about SSL configurations corresponding the current connection are logged at INFO level.
     [java] 2021-01-04 23:42:09,307 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type JSON_WRITER with this error: Connection refused: connect
     [java] 2021-01-04 23:42:09,308 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 0 seconds (+/-10%)
     [java] 2021-01-04 23:42:39,208 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Error trying to connect to APM Server. Some details about SSL configurations corresponding the current connection are logged at INFO level.
     [java] 2021-01-04 23:42:39,209 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type JSON_WRITER with this error: Connection refused: connect
     [java] 2021-01-04 23:42:39,209 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 1 seconds (+/-10%)
     [java] 2021-01-04 23:42:53,844 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor refers to a missing class.
     [java] 2021-01-04 23:42:53,848 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.concurrent.JMXEnabledScheduledThreadPoolExecutorMBean refers to a missing class.
     [java] 2021-01-04 23:42:54,699 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.concurrent.DebuggableScheduledThreadPoolExecutor$UncomplainingRunnable refers to a missing class.
     [java] 2021-01-04 23:42:55,158 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.cql3.statements.CFStatement refers to a missing class.
     [java] 2021-01-04 23:42:55,159 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.cql3.statements.ModificationStatement$Parsed refers to a missing class.
     [java] 2021-01-04 23:42:55,162 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.cql3.CQLStatement refers to a missing class.
     [java] 2021-01-04 23:42:55,165 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.cql3.statements.SchemaAlteringStatement refers to a missing class.
     [java] 2021-01-04 23:42:55,252 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.cql3.statements.PermissionAlteringStatement refers to a missing class.
     [java] 2021-01-04 23:42:55,255 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.cql3.statements.AuthenticationStatement refers to a missing class.
     [java] 2021-01-04 23:42:56,912 [Fabric:7002:0] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.db.BlacklistedDirectoriesMBean refers to a missing class.
     [java] 2021-01-04 23:42:58,701 [Fabric:7002:0] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.net.async.connection.Connection$Message refers to a missing class.
     [java] 2021-01-04 23:42:59,178 [Fabric:7002:1] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.concurrent.ThreadPoolsMonitorMBean refers to a missing class.
     [java] 2021-01-04 23:42:59,256 [Fabric:7002:1] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.apache.cassandra.concurrent.TracingAwareExecutorService refers to a missing class.
```

Originally, `JMXEnabledThreadPoolExecutor` class extends `DebuggableThreadPoolExecutor`, and `DebuggableThreadPoolExecutor` implements `TracingAwareExecutorService` interface. However, after bytecode transformation, `DebuggableThreadPoolExecutor` no longer implements `TracingAwareExecutorService`.

### Analysis

This Java application uses two Cassandra clients of two different versions. These versions are not compatible with each other, but their packages / class names intersect. In order to resolve name conflicts, the classes of newer Cassandra are loaded by a separate ClassLoader from a location unreachable by the System ClassLoader. Meanwhile, the older Cassandra classes are on the application classpath (i.e. loaded by the System ClassLoader).

Elastic APM Agent instruments ThreadPoolExecutors by default. When instrumenting `JMXEnabledThreadPoolExecutor` of a newer Cassandra, it loads classes with a System ClassLoader instead of the custom ClassLoader used to load newer Cassandra client. This results in loading wrong classes.

### Example

I've attached a reduced stadalone test case that demonstrates the wrong behavior: [threadpooltest.zip](https://github.com/elastic/apm-agent-java/files/5784369/threadpooltest.zip)

When running `java -jar threadpooltest.zip`, it prints
```
Test passed
```

But when running `java -javaagent:/path/to/elastic-apm-agent-1.19.0.jar -jar threadpooltest.zip`, the result is
```
Exception in thread "main" java.lang.AssertionError: Class hierarchy changed!
        at pool.ThreadPoolTest.run(ThreadPoolTest.java:8)
        at Main.main(Main.java:6)
```

The sources for the test: [src.zip](https://github.com/elastic/apm-agent-java/files/5784378/src.zip)

**Comment by felixbarny** [comment] 2021-01-11 07:21
@raphw did you encounter a similar issue before? Do we set up Byte Buddy incorrectly or could this be a bug in Byte Buddy?

**Comment by eyalkoren** [comment] 2021-01-11 08:59
@felixbarny Don't you think it is something related to the Indy CL? Maybe relying on cached Indy CL? I will reproduce and see if this may be related.

**Comment by felixbarny** [comment] 2021-01-11 13:58
I don't think it's related to the advice dispatching mechanism. Maybe it has something to do with the type pool cache, but I'm not sure.

**Comment by raphw** [comment] 2021-01-12 22:10
Brilliant to have a reproduction, thanks @apangin!

I also assume that it has something to do with caching type descriptions, I will have to dig a little bit. Those caches must consider the class loader and not only the name of a class.

Weirdly enough, Byte Buddy is purely additive in its default setup. It should be impossible to remove an interface from the input byte code. I'll spin it up tomorrow and let you know but I am pretty sure this is caused by some caching layer.

**Comment by felixbarny** [comment] 2021-01-13 10:11
Not sure if it plays a role here but one thing that's specific to our Byte Buddy setup is that we're patching the bytecode version of instrumented classes to 51 in order to be able to insert invokedynamic instructions. See also [`PatchBytecodeVersionTo51Transformer`](https://github.com/elastic/apm-agent-java/blob/master/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/PatchBytecodeVersionTo51Transformer.java).

**Comment by raphw** [comment] 2021-01-13 22:44
It seems like the interface is indeed removed during instrumentation:

```
rafael@raftop:~/dump$ javap pool.DebuggableThreadPoolExecutor-original.1610577051760.class 
Compiled from "DebuggableThreadPoolExecutor.java"
public class pool.DebuggableThreadPoolExecutor extends java.util.concurrent.ThreadPoolExecutor implements pool.TracingAwareExecutorService {
  public pool.DebuggableThreadPoolExecutor(int, int, long, java.util.concurrent.TimeUnit, java.util.concurrent.BlockingQueue<java.lang.Runnable>);
}

rafael@raftop:~/dump$ javap pool.DebuggableThreadPoolExecutor.1610577051760.class 
Compiled from "DebuggableThreadPoolExecutor.java"
public class pool.DebuggableThreadPoolExecutor extends java.util.concurrent.ThreadPoolExecutor {
  public pool.DebuggableThreadPoolExecutor(int, int, long, java.util.concurrent.TimeUnit, java.util.concurrent.BlockingQueue<java.lang.Runnable>);
}
```

Normally, this should never happen unless you are using a `ClassFileBufferStrategy` that removes the byte code that is offered by the JVM. I'll look more into it tomorrow.

**Comment by felixbarny** [comment] 2021-01-14 07:47
I found out in which area the problem is in:

When disabling the type pool cache (`java -javaagent:elastic-apm-agent-1.19.0.jar -Delastic.apm.enable_type_pool_cache=false -jar threadpooltest.zip`), the output is `Test passed`.

So there's probably a bug in [`SoftlyReferencingTypePoolCache`](https://github.com/elastic/apm-agent-java/blob/master/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/SoftlyReferencingTypePoolCache.java) or in the setup here:

https://github.com/elastic/apm-agent-java/blob/56bae31eb563fbc532729c13a24f01523e382958/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java#L630-L632

**Comment by raphw** [comment] 2021-01-14 20:38
Ok, I understand the problem now. You can argue, that the `CustomClassLoader` is incorrectly implemented but of course, this scenario should be handled correctly by Byte Buddy anyways. So here is the anatomy of the bug:

- When `CustomThreadPoolExecutor` is loaded, this class is passed to the class file transformer first. While instrumenting, the agent checks whether the class is an instance of `ExecutorService`, this requires navigating the type hierarchy of the class. On the way, `DebuggableThreadPoolExecutor` needs to be resolved from the class loader by its class file since it is not legal to load classes during the instrumentation of another class (in overly simplified words). Byte Buddy invokes `classLoader.getResourceAsStream("/pool/DebuggableThreadPoolExecutor.class")` to locate the class file from the class loader. This is passed down to the system class loader since the `CustomClassLoader` does not handle resource lookups.
- Byte Buddy is now satisfied with the type description and resolves the super type matcher, concluding that `CustomThreadPoolExecutor` is indeed a `ExecutorService`.
- Next, `DebuggableThreadPoolExecutor` is instrumented. Byte Buddy was instructed to cache type description to avoid the duplicate class file processing. The description of `DebuggableThreadPoolExecutor` does now represent the system class loader's representation, without the interface. When deserializing the description back to a byte array, it is now missing.

In a way, Byte Buddy is tricked into this behavior by resolving the incorrect class file for `DebuggableThreadPoolExecutor` which lets it believe that it already knows the correct description. But of course, ideally Byte Buddy would ignore any cached description for the currently instrumented class since the class file that is provided by the instrumentation API is guaranteed to be correct.

I will work on a fix for it; however, Byte Buddy can only read linked class files by querying the class loader and matchers might not be applied correctly if class files are misrepresenting actual features such as interfaces that are being implemented.

**Comment by raphw** [comment] 2021-01-14 21:29
I don't find time to test this today, but you can rerun the example with the *cache-override* branch of Byte Buddy and see if the problem is handled. It takes a bit of additional overhead per transformation but it is the more correct approach and since the byte array is already resolved, it should not be to bad since there's no additional IO involved.

**Comment by raphw** [comment] 2021-01-15 23:27
It does now work with the current Byte Buddy master snapshot. I will release this some time next week, I think to allow for resolving this issue.

**Comment by eyalkoren** [comment] 2021-01-17 05:06
> however, Byte Buddy can only read linked class files by querying the class loader and matchers might not be applied correctly if class files are misrepresenting actual features such as interfaces that are being implemented.

I think that's a fair limitation (and it only means we fail matching, not as bad as breaking things).
In case we come across that, we can disable type caching, although the hard part will be to know this happened, as there will be no indication...

**Comment by raphw** [comment] 2021-01-17 19:53
Not quite, unfortunately. If the class loader resolves the incorrect class file, caching does not help since the instrumentation API only resolves the current class file. The only alternative would be to abort any transformation of a non-loaded class and to use a resubmission strategy to later redefine such classes where the loaded type is available to apply a transformation (and matching) based on the loaded type which always represents the actual definition.

**Comment by eyalkoren** [comment] 2021-01-18 07:53
I see, then would [delaying the instrumentation](https://github.com/elastic/apm-agent-java/pull/1594) and using `DescriptionStrategy.Default.HYBRID` in the late retransformation be good enough? If so, I think it is rare enough to consider such a configurable delay satisfactory, unless you also have an idea how we can identify this is happening in runtime.

**Comment by raphw** [comment] 2021-01-18 09:26
I'd need to add a mechanism to Byte Buddy for this but it makes sense. The resubmission approach already works around many corner cases where Byte Buddy fails to resolve a class file altogether and rather operates on loaded classes. The idea would be to early abort transformation of unloaded classes and to resubmit them immediately. This way, all transformations would be treated as retransformations and as a bonus, one would never query user class loaders (and be exposed to their flaws) or block user threads for the time of transformation. The disadvantage would be that one looses traces for the time it takes to apply the retransformation.

I need to explore that and then it's pretty much a wild card on costs, but this is certainly something that makes sense to offer as a DSL option.

**Comment by eyalkoren** [comment] 2021-01-18 10:24
> The disadvantage would be that one looses traces for the time it takes to apply the retransformation.

In some cases it may be worse and we really want to instrument on startup. For example, we rely on `java.sql.Connection#prepareStatement` to store the SQL for the returned statement. Since `PreparedStatement`s can be long-lived, we don't want to miss those.
So, ideally, we can eventually decide on a general strategy as you suggest, but with the ability to make exceptions.

**Comment by raphw** [comment] 2021-01-24 22:51
I see, in such cases the approach won't work but I will add an ability to fine-grain it. It's rather complicated as it turns out and will likely require an API change but it's a good feature to have in the library, I think, especially when dealing with class loaders that do not provide byte arrays of class files.

**Closed** 2021-02-05 08:30 UTC
Labels: agent-java, bug
