### ISSUE TITLE
doGetCurrentTransaction() and doStartTransaction() always return null

### ISSUE THREAD

**Issue by comoroberto** [elastic/apm-agent-java#2066] opened 2021-08-17 15:06 UTC
## Describe the bug

- `ElasticApm.currentTransaction()` always returns `NoopTransaction.INSTANCE` because `doGetCurrentTransaction()` returns null.

- `ElasticApm.startTransaction()` always returns `NoopTransaction.INSTANCE` because `doStartTransaction()` returns null.

## Expected behavior
- `ElasticApm.currentTransaction()` should return the currently running transaction, or if there is no current transaction, it should return a noop transaction.

- `doGetCurrentTransaction()` should not always return null.

- `doStartTransaction()`  should not always return null.

## Debug logs

https://github.com/elastic/apm-agent-java/blob/f9267ff7fc7df619cb2272b8790fde618055c8f6/apm-agent-api/src/main/java/co/elastic/apm/api/ElasticApm.java#L191

![image](https://user-images.githubusercontent.com/84711700/129748573-4d3cd57e-d99c-410f-9364-4dd6f6804f66.png)

https://github.com/elastic/apm-agent-java/blob/f9267ff7fc7df619cb2272b8790fde618055c8f6/apm-agent-api/src/main/java/co/elastic/apm/api/ElasticApm.java#L83

![image](https://user-images.githubusercontent.com/84711700/129748628-9f148473-348b-4f15-af06-4d7c80f9f740.png)

**Comment by eyalkoren** [comment] 2021-08-18 04:34
The API is noop by design. In order for it to function properly, you need to [attach](https://www.elastic.co/guide/en/apm/agent/java/current/setup.html#setup) the agent as well, which then instruments the API classes to make sure everything is doing what it's supposed to do.

I am closing this issue, but if you still feel a fix is required, you can reopen.

If not working after attaching the agent, you can set the [`log_level`](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-level) to `debug` and look for messages saying the the API instrumentations are applied.

**Closed by eyalkoren** 2021-08-18 04:34 UTC
Labels: agent-java, community
