### ISSUE TITLE
Service Version per classloader

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#1725] opened 2021-03-30 14:05 UTC
## Is your feature request related to a problem?
We deploy multiple wars with different version to a JBoss EAP. Currently we can only set the service version globally for all deployments, but we would like to set the version for each deployment individualy (similar to the service name).

## Describe the solution you'd like
Can we please add `overrideServiceVersionForClassLoader(ClassLoader classLoader, String serviceVersion)` to the Tracer class, so we can use e.g.
```
@WebListener
public class ElasticAPMServiceNameAndVersionContextListener implements ServletContextListener {

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        Tracer tracer = GlobalTracer.get();
        tracer.overrideServiceVersionForClassLoader(getClass().getClassLoader(), "...");
    }
```
to set the service version.

**Comment by felixbarny** [comment] 2021-03-30 14:40
That seems linked to auto-detecting the version https://github.com/elastic/apm-agent-java/issues/1327

Have you thought about how to determine the service version of each web application? Is that part of the `MANIFEST.MF`? If yes, can we load that file using `servletContext.getClassLoader().getResourceAsStream("META-INF/MANIFEST.MF")`. How do you have to configure Maven and Gradle to set the version?

**Comment by felixbarny** [comment] 2021-03-31 09:49
It would be great to have something like that within the agent. I added some thoughts here: https://github.com/elastic/apm-agent-java/issues/1327#issuecomment-810934303

**Comment by eyalkoren** [comment] 2021-03-31 11:40
@tobiasstadler thanks for your awesome inputs! This is an important issue and it's on the long-term plans. 
Do you mind if we close this issue as a duplicate of #1327 and keep the discussion going there?

**Comment by tobiasstadler** [comment] 2021-04-01 08:38
In my opinion this issues is prerequisite for #1327. But we can continue in #1327 if you like.

**Comment by eyalkoren** [comment] 2021-04-01 08:53
I agree on that, but I'd prefer implementing a capability along with its actual usage.
For example, I imagine `overrideServiceVersionForClassLoader ` calls may be tightly coupled with `overrideServiceNameForClassLoader`, so we may not need to have these two APIs and a duplicated implementation with an additional map.

**Closed as completed by eyalkoren** 2021-04-01 08:53 UTC
Labels: agent-java
