### ISSUE TITLE
use_path_as_transaction_name started affecting all requests

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-agent-java#2291] opened 2021-11-25 17:10 UTC
## Describe the bug
In a Spring Boot 2.5.7 MVC webapp, at some point prior to 1.27.0 the `use_path_as_transaction_name` feature started treating every request as "unknown" and replacing the name.

## Steps to reproduce
1. Configure APM for Spring application with `use_path_as_transaction_name`
2. Make a request to a controller-bound method
3. Observe the request appears as `GET /foo/1234` instead of `Controller#getFoo`

## Expected behaviour
Only requests with an unknown handler binding should be replaced with their path, as in previous versions.

## Debug logs
Too noisy with lettuce events to find the relevant section.

**Comment by felixbarny** [comment] 2021-11-30 07:45
@SylvainJuge looks like a regression after https://github.com/elastic/apm-agent-java/pull/1906

**Comment by SylvainJuge** [comment] 2021-12-02 11:01
I'm not really sure to understand the issue here, so maybe I'm missing something.

When `use_path_as_transaction_name` is set to `true`, it is expected that all transactions names would be impacted, thus it is expected that `Controller#getFoo` will be replaced with `GET /foo/1234`. In this case using also the [url_groups](https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-url-groups) is often required to limit cardinality (the number of distinct transactions).

The change introduced in #1906 aimed to provide a better default for cases where the controller method is not known, so in a way it would be `use_path_as_transaction_name=true` only for transactions that would be otherwise named "unknown".

Thus, if I understand correctly in your case just not setting `use_path_as_transaction_name` should make it behave the way it's expected to. Can you check if doing that would work for you ? If not I'd be happy to know more about your use-case.

**Comment by OrangeDog** [comment] 2021-12-02 12:23
> it is expected that all transactions names would be impacted

That's not what it used to do, nor what the documentation says:

> If set to `true`, transaction names of unsupported or partially-supported frameworks will be in the form of `$method $path` instead of just `$method unknown route`.

**Comment by SylvainJuge** [comment] 2021-12-02 13:51
Yes, I agree with you, we at least should update the documentation to reflect the current behavior.
Also, this configuration parameter is still marked as **experimental** even if it has been available since version 1.0.0.

Previously:
- when disabled (default), so you might some "unknown" transactions
- when enabled, it would use the URL path as fallback for those "unknown" transactions

Now:
- "unknown" transactions are named using path by default, thus in a sense it is just enabling the previous behavior by default
- when set to `true`, all transactions use the path name, even if we could the controller+method name

In this case, when upgrading the agent you have to now rely on the default configuration, and I understand that it might be a bit tedious. However, that also means that you don't have to explicitly configure the agent to behave like it used to.

Do you have any use-case where relying on the now-default behavior would not work ?

Also, one of the reasons that we changed this implementation is to prepare for the case when we will be able to use path patterns for frameworks like Spring MVC or JAX-RS that support it. For example it would enable users to pick between the resource/controller class+method and a more "RESTified name" like `GET /path/{id}`.

**Comment by OrangeDog** [comment] 2021-12-02 15:15
The new default behaviour is what I want, but I wasn't expecting it to change, especially without any mention,

**Comment by SylvainJuge** [comment] 2021-12-02 15:43
After discussing this internally I have to admit that on top of an inaccurate documentation, my understanding of it wasn't 100% accurate.

We currently provide this kind of "automatic fallback" for unknown transaction only for Spring MVC, and not for other frameworks, which, while it could be convenient in your case, is inconsistent. Once we have settled for the right strategy we'll update this issue.

Sorry for the inconvenience.

**Comment by eyalkoren** [comment] 2021-12-07 10:51
@OrangeDog thanks for reporting and providing this useful feedback. 
Please see https://github.com/elastic/apm-agent-java/pull/2320#issue-796790990.

The rationale of not using the path as a default fallback is the risk of having very high cardinality in applications that use path parameters. So between the bad experience of getting all transactions under one group and getting very high number of transaction groups, we prefer the former, with the ability to override through the `use_path_as_transaction_name`. The advantage of letting the users to manually set this config is letting them know about the related risk and the `url_groups` to overcome it.

**Comment by OrangeDog** [comment] 2021-12-07 11:24
@eyalkoren everyone seems very confused about what this used to do and what it does now with Spring:

### Before:
- false: known handlers are `Class#method`, unknown handlers are `METHOD "unknown route"`
- true: known handlers are `Class#method`, unknown handlers are `METHOD path`<sup>*</sup>

### Now:
- false: known handlers are `Class#method`, unknown handlers are `METHOD path`<sup>*</sup>
- true: all requests are `METHOD path`

If you changed it on purpose then you need to fix the documentation (and the release note).
If you didn't change it on purpose then you should probably revert it.

<sup>*</sup> This is the behaviour I want. I don't mind how I get it.

**Comment by eyalkoren** [comment] 2021-12-07 15:21
Sorry if you are still confused, this is indeed not as straighforward as I would like it to be.

Let's refer only to the fully-correct part of your "Before" description (assuming that "Before" is < 1.26.0):
> Before:
false: known handlers are Class#method
true: known handlers are Class#method

This behaviour is restored with #2320 . As for the "unknown handlers", it's a bit more complicated, but if you set `use_path_as_transaction_name=true`, you would get `METHOD path` for those.

> This is the behaviour I want. I don't mind how I get it.

Awesome, then keep on using `use_path_as_transaction_name=true` and it should get you what you want. You can try [this snapshot build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-2320/detail/PR-2320/4/artifacts) and see if it does what you expect. We'd be happy to get your feedback on it.
Thanks!

**Comment by OrangeDog** [comment] 2021-12-07 15:34
> keep on using use_path_as_transaction_name=true

No, I have to have it set to `false` at the moment. #2320 is still open.

**Comment by eyalkoren** [comment] 2021-12-07 16:05
> No, I have to have it set to false at the moment.

Sorry, then please go back to your "Before" as well 🙂 

> #2320 is still open.

Right. If you can test it's build artifact (that i linked above), it would be a nice verification that it does what you want before we merge it. That is- if you have some test/staging environment where you can validate it.

Thanks

**Closed** 2021-12-08 07:34 UTC
Labels: agent-java, community, triage
