### ISSUE TITLE
Debug error messages when using spring-webflux without `spring-web` dependency

### ISSUE THREAD

**Issue by kananindzya** [elastic/apm-agent-java#2232] opened 2021-11-03 05:17 UTC
In cases when you run spring-webflux without `spring-web` dependency getting informative errors below:

```
2021-11-03 11:14:23,032 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.springframework.web.context.ConfigurableWebApplicationContext refers to a missing class.
2021-11-03 11:14:23,032 [main] DEBUG co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - ByteBuddy type resolution stack trace: 
net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for javax.servlet.ServletContext
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:162) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$TokenizedGenericType.toErasure(TypePool.java:6794) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyTypeList.get(TypePool.java:6602) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyTypeList.get(TypePool.java:6575) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at java.util.AbstractList$Itr.next(AbstractList.java:371) ~[?:?]
	at net.bytebuddy.matcher.ElementMatchers.takesArguments(ElementMatchers.java:1309) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.dynamic.scaffold.inline.InliningImplementationMatcher.of(InliningImplementationMatcher.java:71) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:208) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11362) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11298) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:11016) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:11763) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:11702) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11240) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [?:?]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563) [?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) [?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) [?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) [?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) [?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) [?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) [?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) [?:?]
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.resolve(FilteringSpringBootCondition.java:108) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter.isPresent(FilteringSpringBootCondition.java:140) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.OnWebApplicationCondition.getOutcome(OnWebApplicationCondition.java:80) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.OnWebApplicationCondition.getOutcomes(OnWebApplicationCondition.java:58) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.match(FilteringSpringBootCondition.java:49) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$ConfigurationClassFilter.filter(AutoConfigurationImportSelector.java:370) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:128) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:879) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) [spring-boot-2.5.0.jar:2.5.0]
	at com.kanaindzya.apm.sb2.FooApplication.main(FooApplication.java:20) [classes/:?]
2021-11-03 11:14:23,034 [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation SpringServiceNameInstrumentation: hasSuperType(erasure(name(equals(org.springframework.web.context.WebApplicationContext)))) matches interface org.springframework.web.context.WebApplicationContext
2021-11-03 11:14:23,035 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.springframework.web.context.WebApplicationContext refers to a missing class.
2021-11-03 11:14:23,035 [main] DEBUG co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - ByteBuddy type resolution stack trace: 
net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for javax.servlet.ServletContext
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:162) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$TokenizedGenericType.toErasure(TypePool.java:6794) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$GenericTypeToken$Resolution$Raw$RawAnnotatedType.of(TypePool.java:3707) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$GenericTypeToken$Resolution$Raw.resolveReturnType(TypePool.java:3617) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyMethodDescription.getReturnType(TypePool.java:7349) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.dynamic.scaffold.inline.InliningImplementationMatcher.of(InliningImplementationMatcher.java:70) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:208) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11362) ~[elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11298) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:11016) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:11763) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:11702) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11240) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source) [elastic-apm-agent-1.26.1-SNAPSHOT.jar:?]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [?:?]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563) [?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) [?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) [?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) [?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) [?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) [?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) [?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) [?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) [?:?]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) [?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) [?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) [?:?]
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.resolve(FilteringSpringBootCondition.java:108) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter.isPresent(FilteringSpringBootCondition.java:140) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.OnWebApplicationCondition.getOutcome(OnWebApplicationCondition.java:80) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.OnWebApplicationCondition.getOutcomes(OnWebApplicationCondition.java:58) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.match(FilteringSpringBootCondition.java:49) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$ConfigurationClassFilter.filter(AutoConfigurationImportSelector.java:370) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:128) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434) [spring-boot-autoconfigure-2.5.0.jar:2.5.0]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:879) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) [spring-boot-2.5.0.jar:2.5.0]
	at com.kanaindzya.apm.sb2.FooApplication.main(FooApplication.java:20) [classes/:?]
2021-11-03 11:14:23,430 [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation HandlerAdapterInstrumentation: (name(equals(org.springframework.web.reactive.function.server.support.HandlerFunctionAdapter)) or name(equals(org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter)) or name(equals(org.springframework.web.reactive.socket.server.support.WebSocketHandlerAdapter)) or name(equals(org.springframework.web.reactive.result.SimpleHandlerAdapter))) matches class org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter
2021-11-03 11:14:23,435 [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method m
```

**Comment by SylvainJuge** [comment] 2022-06-13 12:37
After further investigation, the issue is not triggered by the agent itself, it's just an optional dependency whose class resolution fails. By looking at the source code we can see that the `org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.ClassNameFilter#isPresent` wraps this in a try-catch block and gracefully returns `false` when unable to load such class.

The downside here, is that the agent is not aware of this and reports what appears to be an error, so I would suggest to just close this for now unless it becomes an issue:
- the `DEBUG` logs are usually only required for investigation/debugging, it does not impacts agent behavior
- making the agent ignore this error would have to rely on some heuristics (like "just ignore errors when loading spring context) and could be complex to implement, thus the return on investment is clearly not great.

As a consequence, I'll close this for now as there isn't much we can do about it. @kananindzya feel free to comment if you think it's worth digging this a bit more or have ideas for an applicable work-around.

**Closed by SylvainJuge** 2022-06-13 12:37 UTC
Labels: bug, agent-java, community, size:small
