### ISSUE TITLE
support for weblogic servers

### ISSUE THREAD

**Issue by zakthan** [elastic/apm-agent-java#109] opened 2018-06-27 15:10 UTC
I was wondering if you have ever tried this agent with oracle weblogic and if not if there are any plans to do so in the future.
Thank you in advance.

**Comment by felixbarny** [comment] 2018-06-27 16:47
The problem is that there is no publically available docker container for this so we can't easily do integration tests. In the future, we will probably set up a dedicated environment. But for 1.0 there are are no plans to add official support for WebLogic. Did you try the agent with WebLogic? Do you get errors?

**Comment by ripleymj** [comment] 2018-08-27 18:59
I decided to give APM a try today with one of our Oracle PeopleSoft environments, and then noticed this bug. I added the Java agent to a WebLogic 12.2.1.3.0 installation, and it seems to have worked. I'll admit that on the first time out, I'm not entirely sure what to be looking for, but I started seeing data arrive within a few seconds (screenshot attached).

As for Docker WebLogic, Oracle is attempting that: https://github.com/oracle/docker-images/tree/master/OracleWebLogic but given the dumpster fire that is Oracle licensing, I can't speculate if that'd be usable for Elastic.

Keep up the good work. I'm excited to see what this can show us about our environment.

![screenshot_2018-08-27 kibana](https://user-images.githubusercontent.com/12940106/44679564-57d7fb00-aa09-11e8-92fc-9a9188e74ba8.png)

**Comment by felixbarny** [comment] 2018-08-27 19:39
That’s great to hear! When you encounter any issues be sure to report them. But so far it seems to just work?

**Comment by ripleymj** [comment] 2018-08-27 19:56
Looks good so far. Installation into WebLogic was pretty much textbook. I haven't seen any errors reported on either the WLS or APM side, but it's just me clicking around on a few pages in a throw-away environment.

PeopleSoft seems to ignore most JavaEE convention and recklessly re-implement standard functionality. It looks like a decent number of fields in APM are blank since it can't find the data in the standard locations, but that might just be me needing more time to understand how this all fits together.

**Comment by felixbarny** [comment] 2018-08-28 05:09
Which fields are blank for example?

**Comment by ripleymj** [comment] 2018-08-28 13:37
My apologies, I jumped too fast too soon in making that statement. Looking over the data a bit more, most of the things that are blank are probably legitimate. The Service tab, for instance, doesn't have framework, version, or git_ref, but those couldn't exist for this, since PeopleSoft is just one giant war file shoved into WLS. The Process tab doesn't show Java's argv, not quite sure about that one. The System tab doesn't have loadavg, but that may be an LXC container side-effect.

Timeline doesn't pick up any Spans, which I guess is where SQL requests would appear? Peoplesoft offloads most of the heavy lifting to its application server over it's own protocol, so that's likely a dead-end for APM.

Username is a bit of an oddity. It's not populating for Peoplesoft, again because I think they do their own session management. However, it does show up when using the WLS Administration Console, which uses JavaEE auth. If there were any will to pursue this here, am I reading the docs correctly that the OpenTracing API is the means to expose hints from an uncooperative app to the APM agent?

Another interesting feature I noticed in there, not only does APM redact the JSESSIONID cookie, but it has also figured out that PS_TOKEN cookie contains sensitive content and redacts it.

**Comment by felixbarny** [comment] 2018-08-30 10:31
> The Process tab doesn't show Java's argv

This is opt-in, see https://www.elastic.co/guide/en/apm/agent/java/current/config-reporter.html#config-include-process-args

> The System tab doesn't have loadavg

AFAICT, the system tab does not support `loadavg`

>  Peoplesoft offloads most of the heavy lifting to its application server over it's own protocol, so that's likely a dead-end for APM.

Do you know which protocol is used there? Is it proprietary?

> Username is a bit of an oddity

Username is not really supported out-of-the-box atm. I've created an issue for that: https://github.com/elastic/apm-agent-java/issues/183

> it has also figured out that PS_TOKEN cookie contains sensitive content and redacts it.
That's because `*token` is considered sensitive. See also 
https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-sanitize-field-names

**Comment by sandilyasd** [comment] 2018-12-14 09:47
I would also like to test the integration of Java APM agent with Weblogic 12.2. Could you please help me where exactly we need to add the confgiurations. In setDomainenv.sh?

**Comment by ripleymj** [comment] 2018-12-14 14:00
I no longer have that environment to refer back to, but I think I may have used setEnv.sh. Any of the scripts that get merged at startup should work, but you'll need to determine which makes sense for your environment so you can target the servers in the cluster that you want to monitor, for instance, you may not want the Admin Server reporting to APM.

**Closed** 2019-04-09 15:56 UTC
Labels: [zube]: In Review, framework support
