### ISSUE TITLE
Capture body backend request

### ISSUE THREAD

**Issue by tmihaldinec** [elastic/apm-agent-java#867] opened 2019-09-30 13:12 UTC
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions. 
Hi,
we have one issues... we have some WildFly application which is doing some B2B operations (SOAP request and response) and behind it is also invoking Apache HttpClient request toward some backend systems and based on response from backend it is building response back to cleint

we completely capture body request from this Wildfly application (request and response) and we see in timeline POST request toward this backend system but when i open this request we dont see POST body request

so question is .. how can we capture Apache HttpClient request which is requested by this WildFly application

thanks in advance
tomislav

**Comment by felixbarny** [comment] 2019-09-30 13:40
Closing as a duplicate of https://discuss.elastic.co/t/apm-java-agent-capture-body-backend-request-apache-httpclient/201646

**Closed by felixbarny** 2019-09-30 13:40 UTC
