### ISSUE TITLE
Instrumenting ActiveMQ for JMS messages

### ISSUE THREAD

**Issue by mlguthrie** [elastic/apm-agent-java#753] opened 2019-07-26 18:19 UTC
**Describe the bug**
I'm working with this Docker image of ActiveMQ:

[https://hub.docker.com/r/rmohr/activemq](https://hub.docker.com/r/rmohr/activemq)

It allows customization through the ACTIVEMQ_OPTS variable. I've set that variable to this:

```
 ACTIVEMQ_OPTS=-Dserver.name=$HOSTNAME -javaagent:/opt/elastic-apm-agent-1.7.0.jar -Delastic.apm.service_name=$HOSTNAME -Delastic.apm.environment=test -Delastic.apm.server_url=http://server:8200 -Delastic.apm.secret_token=top_secret -Delastic.apm.application_packages= -Delastic.apm.disable_instrumentations= "
```

**To Reproduce**
1. Grab the Docker image above
2. Pass in the ACTIVEMQ_OPTS with appropriate settings that I've used above

**Expected behavior**
I would expect to see messages and container metrics. Instead, I see the container registered in Kibana but when clicking on the name all of the tabs for Transactions, Errors, and Metrics are completely empty.

I have this working for other JVMs running on our infrastructure. This is the only JVM that doesn't appear to be sending any data, including metrics. It does appear to send its container name to Elasticsearch though.

**Debug logs (provided below)**

<details>
<summary>Click to expand</summary>

```
INFO: Loading '/opt/activemq/bin/env'

INFO: Using java '/docker-java-home/jre/bin/java'

INFO: Starting in foreground, this is just for debugging purposes (stop process by pressing CTRL+C)

INFO: Creating pidfile /opt/activemq/data/activemq.pid

2019-07-26 17:53:49.105 [main] INFO co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.7.0 as activemq-test-577567dcc8-hzfbn on Java 1.8.0_171 (Oracle Corporation) Linux 3.10.0-957.10.1.el7.x86_64

2019-07-26 17:53:49.108 [main] WARN co.elastic.apm.agent.configuration.StartupInfo - Detected usage of an old configuration key: 'server_url'. Please use 'server_urls' instead.

2019-07-26 17:53:49.108 [main] WARN co.elastic.apm.agent.configuration.StartupInfo - To enable all features and to increase startup times, please configure application_packages

2019-07-26 17:53:49.193 [apm-server-healthcheck] INFO co.elastic.apm.agent.report.ApmServerHealthChecker - Elastic APM server is available: { "build_date": "2019-06-20T14:39:23Z", "build_sha": "9a099b63c53eac8c55707df96193143ec66337e9", "version": "7.2.0"}

Java Runtime: Oracle Corporation 1.8.0_171 /usr/lib/jvm/java-8-openjdk-amd64/jre

Heap sizes: current=79360k free=56694k max=7456768k

JVM args: -Dorg.apache.activemq.UseDedicatedTaskRunner=false -Dserver.name=activemq-test-577567dcc8-hzfbn -javaagent:/opt/elastic-apm-agent-1.7.0.jar -Delastic.apm.service_name=activemq-test-577567dcc8-hzfbn -Delastic.apm.environment=test -Delastic.apm.server_url=http://server:8200 -Delastic.apm.secret_token= -Delastic.apm.application_packages= -Delastic.apm.disable_instrumentations= -Xms64M -Xmx8G -Djava.util.logging.config.file=logging.properties -Djava.security.auth.login.config=/opt/activemq/conf/login.config -Dcom.sun.management.jmxremote -Djava.awt.headless=true -Djava.io.tmpdir=/opt/activemq/tmp -Dactivemq.classpath=/opt/activemq/conf:/opt/activemq/../lib/: -Dactivemq.home=/opt/activemq -Dactivemq.base=/opt/activemq -Dactivemq.conf=/opt/activemq/conf -Dactivemq.data=/opt/activemq/data

Extensions classpath:

[/opt/activemq/lib,/opt/activemq/lib/camel,/opt/activemq/lib/optional,/opt/activemq/lib/web,/opt/activemq/lib/extra]

ACTIVEMQ_HOME: /opt/activemq

ACTIVEMQ_BASE: /opt/activemq

ACTIVEMQ_CONF: /opt/activemq/conf

ACTIVEMQ_DATA: /opt/activemq/data

Loading message broker from: xbean:activemq.xml

INFO | Refreshing org.apache.activemq.xbean.XBeanBrokerFactory$1@fbd1f6: startup date [Fri Jul 26 17:53:52 UTC 2019]; root of context hierarchy

INFO | Using Persistence Adapter: KahaDBPersistenceAdapter[/opt/activemq/data/kahadb]

INFO | PListStore:[/opt/activemq/data/localhost/tmp_storage] started

INFO | Apache ActiveMQ 5.14.5 (localhost, ID:activemq-dbshtfxd-577567dcc8-hzfbn-33571-1564163636103-0:1) is starting

INFO | Listening for connections at: tcp://activemq-dbshtfxd-577567dcc8-hzfbn:61616?maximumConnections=1000&wireFormat.maxFrameSize=104857600

INFO | Connector openwire started

INFO | Listening for connections at: amqp://activemq-dbshtfxd-577567dcc8-hzfbn:5672?maximumConnections=1000&wireFormat.maxFrameSize=104857600

INFO | Connector amqp started

INFO | Listening for connections at: stomp://activemq-dbshtfxd-577567dcc8-hzfbn:61613?maximumConnections=1000&wireFormat.maxFrameSize=104857600

INFO | Connector stomp started

INFO | Listening for connections at: mqtt://activemq-dbshtfxd-577567dcc8-hzfbn:1883?maximumConnections=1000&wireFormat.maxFrameSize=104857600

INFO | Connector mqtt started

WARN | ServletContext@o.e.j.s.ServletContextHandler@733037{/,null,STARTING} has uncovered http methods for path: /

INFO | Listening for connections at ws://activemq-dbshtfxd-577567dcc8-hzfbn:61614?maximumConnections=1000&wireFormat.maxFrameSize=104857600

INFO | Connector ws started

INFO | Apache ActiveMQ 5.14.5 (localhost, ID:activemq-test-577567dcc8-hzfbn-33571-1564163636103-0:1) started

INFO | For help or more information please see: http://activemq.apache.org

WARN | Store limit is 102400 mb (current store usage is 0 mb). The data directory: /opt/activemq/data/kahadb only has 60017 mb of usable space. - resetting to maximum available disk space: 60017 mb

INFO | No Spring WebApplicationInitializer types detected on classpath

INFO | ActiveMQ WebConsole available at http://0.0.0.0:8161/

INFO | ActiveMQ Jolokia REST API available at http://0.0.0.0:8161/api/jolokia/

INFO | Initializing Spring FrameworkServlet 'dispatcher'

INFO | No Spring WebApplicationInitializer types detected on classpath

INFO | jolokia-agent: Using policy access restrictor classpath:/jolokia-access.xml
```
</details>

**Notes**

I've tried various settings for `-Delastic.apm.application_packages=` and nothing seems to work. Including `org.apache.activemq`

**Comment by eyalkoren** [comment] 2019-07-28 04:10
Since you try to monitor the message broker itself- this is the expected behaviour.
Our agent either automatically trace servlet containers, or manually trace proprietary Java applications, but it is not intended to trace any arbitrary middleware. All we can provide for that would probably be metrics, but using an APM agent for this purpose is not the way to go.

Our JMS support means **we instrument JMS clients**, so if you set `-Delastic.apm.disable_instrumentations=` (i.e. set with an empty string) in all other JVMs sending/receiving messages to/from you ActiveMQ, you should get the JMS visibility we provide from the clients' perspective.

Closing this issue now, please let us know if you have further questions, here or [in our forum](https://discuss.elastic.co/c/apm).

**Closed** 2019-07-28 04:11 UTC
