### ISSUE TITLE
Webflux/Reactor with agent 1.28.2 (regression?)

### ISSUE THREAD

**Issue by sangkyunkim89** [elastic/apm-agent-java#2379] opened 2021-12-31 05:30 UTC
springboot 2.2.6
apm agent 1.28.2
webflux

-javaagent:elastic-apm-agent-1.28.2.jar -Dspring.profiles.active=local -Dshostname=image-api -Delastic.apm.service_name=image-api -Delastic.apm.application_packages=com.musinsa.search.app.image_api -Delastic.apm.server_url=http://localhost:8200 -Delastic.apm.secret_token=no -Delastic.apm.disable_instrumentations= -Delastic.apm.enable_experimental_instrumentations=true -Dfile.encoding=UTF-8 -Dfile.client.encoding=UTF-8 -Dclient.encoding.override=UTF-8 -Delastic.apm.environment=local

```
return immediatelyReturnMono
                    .flatMap((data) -> {
                       //networking
                        final Mono<SimilarGoodsSyteVO> similarGoodsSyteVOMono = similarGoodsSyteRepository.getSimilarGoodsList(similarGoodsVO);
                      
                        return Mono.zip(Mono.just(similarGoodsVO), similarGoodsSyteVOMono).flatMap(tuple -> {
                         
                            saveSyteSimilarGoods(tuple);

                            return immediatelyReturnMono;
                        });
                    })
                    .timeout(Duration.ofMillis(0), immediatelyReturnMono);


```

The above code returns immediately immediatelyReturnMono by timeout, but all operations are performed flatmap in the background.
Agent 1.25.1 worked fine, but when I upgraded the version to 1.28.2, the code did not work.

What does it have to do with the agent? I thought but it's true

**Comment by eyalkoren** [comment] 2022-01-02 06:30
@sangkyunkim89 Please provide debug logs for both 1.25.1 and 1.28.x (you can upload and share through https://gist.github.com/).

-----

### Capture debug logs procedure

Ideally this should be done outside of production:
- it requires to restart the application
- debug logs can be verbose
- ideally having only a few transactions in the log help for investigation as there is less noise due to production traffic
- if not possible, we can still use it for a few minutes in production, when using an external configuration file ([doc](https://www.elastic.co/guide/en/apm/agent/java/current/configuration.html#configuration)) the `log_level` can be changed at runtime.

Here, we will refer to the agent log file as `/tmp/agent.log`, but any other location could be used.

- configure the agent with `log_level=debug` ([doc](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-level)) and `log_file=/tmp/agent.log` ([doc](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-file))
- truncate the `/tmp/agent.log` file and restart the application
- execute a few transactions which aren't properly captured by the agent
- copy the `/tmp/agent.log` file and send it back for investigation

**Comment by SylvainJuge** [comment] 2022-01-04 15:04
After investigating this for a couple hours, I still don't know what could be wrong here, can you help us clarify this @sangkyunkim89  ?

This code example is from your application, but relying on a zero-timeout to execute things in the background looks like an anti-pattern to me (but I'm not an Webflux/Reactor expert here). Can you describe the expected behavior of this code exactly ?

From what I understand, you have a `Mono` whose value must be used to `save` something else, presumably in the database, and you want to do that asynchronously, hence using a `flatMap` operator. Using a zero timeout allows you to execute this without blocking and allows to return the initial `Mono`. In other words, you rely on the timeout to always be triggered and only use the fallback value.

Also, can you describe if and how the agent affects your application ? Could you add `.log()` statement to the returned mono/flux and provide the output with and without the agent to see what is the impact on the application ?

Then, if the impact is only on the captured data by APM agent, could you provide a bit more details here ? For example, does the asynchronous (database save) operation that is executed here is not captured properly when it should ?

### Next steps:
- [ ] clarify the expected application behavior
- [ ] clarify the observed behavior with and without the agent

**Comment by jackshirazi** [comment] 2022-07-07 15:22
This issue doesn't seem like it is progressing, and the latest versions of the agent may provide the solutions needed. I will now close this issue, but please feel free to reopen it if work is still needed in this area

**Closed by jackshirazi** 2022-07-07 15:22 UTC
Labels: agent-java, community, triage, size:medium
