### ISSUE TITLE
CPU Spike while instrumenting application in container environment

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-java#1902] opened 2021-07-06 09:20 UTC
Hi

When I instrument a a java application running in container 

`/bin/java -XX:+UseG1GC -jar /tmp/apm-agent-attach.jar --config config_file=/tmp/elasticapm.properties  --pid $pid_java`

I see a spike in CPU usage, and my container gets killed when it hits the CPU limit

Is there a way to reduce CPU consumption or to flatten the curve (even if it goes slowly)

![image](https://user-images.githubusercontent.com/30473593/124575273-8cbc5b80-de4b-11eb-8afb-a24f6ade7a81.png)

**Comment by jackshirazi** [comment] 2021-07-06 09:31
why exactly is the container killed? CPU is a compressible resource and the container gets throttled, it's only killed on an OOM

**Comment by eyalkoren** [comment] 2021-07-06 09:54
If you are not using agent 1.24.0, try upgrading to it. It included a fix for our type pool cache that may be related.

**Comment by WassimDhib** [comment] 2021-07-06 15:07
> 
> 
> why exactly is the container killed? CPU is a compressible resource and the container gets throttled, it's only killed on an OOM

I've got an "exit code 137"

This is my container configuration 

```yaml
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 2Gi
```

**Comment by jackshirazi** [comment] 2021-07-06 17:09
> I've got an "exit code 137"
Yes, that's a kill from exceeding memory. Please upgrade to the latest version as mentioned, and see if it still happens

**Comment by WassimDhib** [comment] 2021-07-07 09:11
I was using the agent 1.23
I will try the next version when I have the opportunity.

In the monitoring graphics, the container doesn't seem to hit a memory limit (of 4 Gi)
I also noticed that memory is overcommited in my test environment.

```
sh-4.2$ cat /proc/sys/vm/overcommit_memory
1
```

**Comment by WassimDhib** [comment] 2021-07-07 15:24
tested using agent 1.24.0 , agent is not starting (user cannot read in /tmp/hsperfdata_root)

`{"@timestamp":"2021-07-07T15:22:12.151Z", "log.level":"DEBUG", "message":"Looking in the following folders for hsperfdata_<user>/<pid> files: [/tmp/hsperfdata_root]", "ecs.version": "1.2.0","service.name":"java-attacher","event.dataset":"java-attacher.log","process.thread.name":"main","log.logger":"co.elastic.apm.attach.JvmDiscoverer.ForHotSpotVm"}`

**Comment by eyalkoren** [comment] 2021-07-08 05:53
This is an expected `DEBUG` message from the attacher cli tool. Please look for something else in the entire log.
Are you using the attacher exactly the same way you did with 1.23.0? 
Are you running the cli tool with the same user that runs the Java application?
Are you running the cli tool with the same Java version as the application?

Please provide as many details as possible to describe your setup and changes between your 1.23 and 1.24 setup, so we can look into this.

**Comment by WassimDhib** [comment] 2021-07-08 15:07
command line for agent version 1.22 (sorry it was not .1.23)
```
pid_java=$(grep java  /proc/*/status  | awk -F"/" '{print $3}');
java -XX:+UseG1GC -jar /tmp/apm-agent-attach.jar --config config_file=/tmp/elasticapm.properties --pid $pid_java
```
=>

```
2021-07-08 15:33:45.628  INFO Attaching the Elastic APM agent to 1
2021-07-08 15:34:07.647  INFO Done
```
command line for agent version 1.24
```
pid_java=$(grep java  /proc/*/status  | awk -F"/" '{print $3}');
java -XX:+UseG1GC -jar /tmp/apm-agent-attach.jar --config config_file=/tmp/elasticapm.properties --include-pid $pid_java --log-level all
```
=>

`{"@timestamp":"2021-07-07T15:22:12.151Z", "log.level":"DEBUG", "message":"Looking in the following folders for hsperfdata_<user>/<pid> files: [/tmp/hsperfdata_root]", "ecs.version": "1.2.0","service.name":"java-attacher","event.dataset":"java-attacher.log","process.thread.name":"main","log.logger":"co.elastic.apm.attach.JvmDiscoverer.ForHotSpotVm"}`



The application is running with root user in unprivileged container
Agent is running with an other user is group root :
`gid=0(root) groups=0(root)`

Agent and application are running with the me jre
```
sh-4.2$ java -version
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11-LTS, mixed mode, sharing)
```

**Comment by WassimDhib** [comment] 2021-07-09 08:07
```
sh-4.2$ ./opt/rh/devtoolset-7/root/usr/bin/strace java -XX:+UseG1GC -jar /tmp/apm-agent-attach-cli-1.24.0.jar  --config config_file=/tmp/elasticapm.properties --include-pid $pid_java
execve("/usr/bin/java", ["java", "-XX:+UseG1GC", "-jar", "/tmp/apm-agent-attach-cli-1.24.0"..., "--config", "config_file=/tmp/elasticapm.prop"..., "--include-pid", "7"], 0x7ffe2473f298 /* 199 vars */) = 0
brk(NULL)                               = 0x95c000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b05f8a000
readlink("/proc/self/exe", "/usr/lib/jvm/java-11-openjdk-11."..., 4096) = 62
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/tls/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/tls/x86_64", 0x7ffcd297d220) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/tls/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/tls", 0x7ffcd297d220) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/x86_64", 0x7ffcd297d220) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli", {st_mode=S_IFDIR|0755, st_size=23, ...}) = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/tls/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/tls/x86_64", 0x7ffcd297d220) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/tls/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/tls", 0x7ffcd297d220) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/x86_64", 0x7ffcd297d220) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=13423, ...}) = 0
mmap(NULL, 13423, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f0b05f86000
close(3)                                = 0
open("/lib64/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20!\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=90248, ...}) = 0
mmap(NULL, 2183272, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b05b54000
mprotect(0x7f0b05b69000, 2093056, PROT_NONE) = 0
mmap(0x7f0b05d68000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7f0b05d68000
close(3)                                = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260l\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=141968, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b05f85000
mmap(NULL, 2208904, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b05938000
mprotect(0x7f0b0594f000, 2093056, PROT_NONE) = 0
mmap(0x7f0b05b4e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x16000) = 0x7f0b05b4e000
mmap(0x7f0b05b50000, 13448, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0b05b50000
close(3)                                = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/libjli.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220)\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=70600, ...}) = 0
mmap(NULL, 2164184, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b05727000
mprotect(0x7f0b05736000, 2097152, PROT_NONE) = 0
mmap(0x7f0b05936000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xf000) = 0x7f0b05936000
close(3)                                = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220\r\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=19288, ...}) = 0
mmap(NULL, 2109712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b05523000
mprotect(0x7f0b05525000, 2097152, PROT_NONE) = 0
mmap(0x7f0b05725000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f0b05725000
close(3)                                = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240%\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2151672, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b05f84000
mmap(NULL, 3981792, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b05156000
mprotect(0x7f0b05318000, 2097152, PROT_NONE) = 0
mmap(0x7f0b05518000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c2000) = 0x7f0b05518000
mmap(0x7f0b0551e000, 16864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0b0551e000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b05f83000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b05f81000
arch_prctl(ARCH_SET_FS, 0x7f0b05f81740) = 0
mprotect(0x7f0b05518000, 16384, PROT_READ) = 0
mprotect(0x7f0b05725000, 4096, PROT_READ) = 0
mprotect(0x7f0b05d68000, 4096, PROT_READ) = 0
mprotect(0x7f0b05b4e000, 4096, PROT_READ) = 0
mprotect(0x7f0b05936000, 4096, PROT_READ) = 0
mprotect(0x601000, 4096, PROT_READ)     = 0
mprotect(0x7f0b05f8b000, 4096, PROT_READ) = 0
munmap(0x7f0b05f86000, 13423)           = 0
set_tid_address(0x7f0b05f81a10)         = 326
set_robust_list(0x7f0b05f81a20, 24)     = 0
rt_sigaction(SIGRTMIN, {sa_handler=0x7f0b0593e790, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f0b059475d0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7f0b0593e820, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7f0b059475d0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(NULL)                               = 0x95c000
brk(0x97d000)                           = 0x97d000
brk(NULL)                               = 0x97d000
open("/tmp/apm-agent-attach-cli-1.24.0.jar", O_RDONLY) = 3
mmap(NULL, 200704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b05f50000
lseek(3, -22, SEEK_END)                 = 12720804
read(3, "PK\5\6\0\0\0\0006\v6\vX\230\4\0L\202\275\0\0\0", 22) = 22
lseek(3, 12419660, SEEK_SET)            = 12419660
read(3, "PK\1\2\24\0\24\0\10\10\10\0\213N\277RUI\221yv\0\0\0\202\0\0\0\24\0\4\0"..., 46) = 46
lseek(3, 0, SEEK_SET)                   = 0
read(3, "PK\3\4\24\0\10\10\10\0\213N\277R\0\0\0\0\0\0\0\0\0\0\0\0\24\0\4\0", 30) = 30
lseek(3, 12419660, SEEK_SET)            = 12419660
read(3, "PK\1\2\24\0\24\0\10\10\10\0\213N\277RUI\221yv\0\0\0\202\0\0\0\24\0\4\0"..., 1024) = 1024
lseek(3, 0, SEEK_SET)                   = 0
read(3, "PK\3\4\24\0\10\10\10\0\213N\277R\0\0\0\0\0\0\0\0\0\0\0\0\24\0\4\0", 30) = 30
munmap(0x7f0b05f50000, 200704)          = 0
lseek(3, 54, SEEK_SET)                  = 54
read(3, "\35\313\261\n\3020\20\200\341=\220w\270\27H\260\272ek\273\25\2\5\301\375H\316z\30\257%\271"..., 118) = 118
close(3)                                = 0
readlink("/proc/self/exe", "/usr/lib/jvm/java-11-openjdk-11."..., 4096) = 62
stat("/etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned", 0x7ffcd29791f0) = -1 ENOENT (No such file or directory)
access("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/lib/libjava.so", F_OK) = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/lib/jvm.cfg", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=29, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0b05f89000
read(3, "-server KNOWN\n-client IGNORE\n", 4096) = 29
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f0b05f89000, 4096)            = 0
stat("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/lib/server/libjvm.so", {st_mode=S_IFREG|0755, st_size=21037384, ...}) = 0
futex(0x7f0b057260b0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/lib/server/libjvm.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \316(\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=21037384, ...}) = 0
mmap(NULL, 22802264, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b03b97000
mprotect(0x7f0b04def000, 2093056, PROT_NONE) = 0
mmap(0x7f0b04fee000, 1110016, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1257000) = 0x7f0b04fee000
mmap(0x7f0b050fd000, 364376, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0b050fd000
close(3)                                = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=13423, ...}) = 0
mmap(NULL, 13423, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f0b05f86000
close(3)                                = 0
open("/lib64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \262\5\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=991616, ...}) = 0
mmap(NULL, 3171168, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b03890000
mprotect(0x7f0b03979000, 2093056, PROT_NONE) = 0
mmap(0x7f0b03b78000, 40960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe8000) = 0x7f0b03b78000
mmap(0x7f0b03b82000, 82784, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f0b03b82000
close(3)                                = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20S\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1137024, ...}) = 0
mmap(NULL, 3150120, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b0358e000
mprotect(0x7f0b0368f000, 2093056, PROT_NONE) = 0
mmap(0x7f0b0388e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x100000) = 0x7f0b0388e000
close(3)                                = 0
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/jli/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin/../lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220*\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=88776, ...}) = 0
mmap(NULL, 2184192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f0b03378000
mprotect(0x7f0b0338d000, 2093056, PROT_NONE) = 0
mmap(0x7f0b0358c000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x14000) = 0x7f0b0358c000
close(3)                                = 0
mprotect(0x7f0b0358c000, 4096, PROT_READ) = 0
mprotect(0x7f0b0388e000, 4096, PROT_READ) = 0
mprotect(0x7f0b03b78000, 32768, PROT_READ) = 0
stat("/etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned", 0x7ffcd297a210) = -1 ENOENT (No such file or directory)
mprotect(0x7f0b04fee000, 864256, PROT_READ) = 0
prctl(0x35 /* PR_??? */, 0, 0x10, 0, 0) = -1 ERANGE (Numerical result out of range)
prctl(0x35 /* PR_??? */, 0, 0x4, 0, 0)  = 0
munmap(0x7f0b05f86000, 13423)           = 0
mmap(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f0b05e80000
clone(child_stack=0x7f0b05f7ffb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f0b05f809d0, tls=0x7f0b05f80700, child_tidptr=0x7f0b05f809d0) = 327
futex(0x7f0b05f809d0, FUTEX_WAIT, 327, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGQUIT {si_signo=SIGQUIT, si_code=SI_USER, si_pid=326, si_uid=1000930000} ---
futex(0x7f0afc008ab8, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigreturn({mask=[]})                 = 202
futex(0x7f0b05f809d0, FUTEX_WAIT, 327, NULL) = 0
close(7)                                = 0
unlink("/tmp/.java_pid326")             = 0
munmap(0x7f0af395a000, 141187908)       = 0
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

```

**Comment by WassimDhib** [comment] 2021-07-09 08:12
I think the jvm discovery is failing because of lack of read permissions in /tmp/hsperfdata_root, but since I provided a valid PID it should pass

**Comment by SylvainJuge** [comment] 2021-07-09 09:45
Hi @WassimDhib ,

The attacher process always tries to read in `/tmp/hsperfdata_${USER}` as it allows to apply a generic filtering on many attributes (class name, PID, arguments, ...), while the PID is valid, that means that failing to read this file is equivalent to not being able to see the JVM.

- What are the permissions on the `/tmp/hsperfdata_root` in your case ?
- What is the name of the user used for attach ? I'm a bit surprised to not see it appear in the list of `/tmp/hsperfdata_${USER}` folders that we read.
- Do you have the same behavior when the same user is used for attach and running the application ?

**Comment by WassimDhib** [comment] 2021-07-09 12:14
my user used for attach :

```
sh-4.2$ id
uid=1000930000 gid=0(root) groups=0(root),1000930000
```

the running application : 

```
sh-4.2$ cat /proc/7/status
Name:   java
Umask:  0022
State:  S (sleeping)
Tgid:   7
Ngid:   0
Pid:    7
PPid:   1
TracerPid:      0
Uid:    1000930000      1000930000      1000930000      1000930000
Gid:    0       0       0       0
```

permissions on hsperfdata_root  (there is no other hsperfdata_* directory).

`drwxr-xr-x. 2 root       root  16 Dec 12  2019 hsperfdata_root`

**Comment by SylvainJuge** [comment] 2021-07-09 12:53
So, from what I understand, in your case:
- application is running as (unpriviledged) root within a container, with the uid  `1000930000`
- attach is run with another user, but with the same uid, `1000930000`

**Comment by WassimDhib** [comment] 2021-07-09 14:09
> 
> 
> So, from what I understand, in your case:
> 
>     * application is running as (unpriviledged) root within a container, with the uid  `1000930000`
> 
>     * attach is run with another user, but with the same uid, `1000930000`
> 
> 
> Is that correct ?
Yes

> Also, can you try to attach with the exact same `root` user that is being used to run the application to check if that makes a difference here ?
There is no way I could log (with rsh) into the container with the same root user, this is how the openshift container platform is working

**Comment by SylvainJuge** [comment] 2021-07-09 14:22
I've tried to reproduce the observed issue with docker without success so far:
- https://docs.docker.com/engine/security/userns-remap/ to remap container user, (so `root` within container will be use a non root UID on host).
- I have the same set of permissions within `hsperfdata_root` : 
```
root@08c8f5bc91d0:/# ls -l /tmp/hsperfdata_root/
total 32
-rw------- 1 root root 32768 Jul  9 14:12 1
```
- there is a similar set of permissions on the `hsperfdata_root` folder itself
```
root@08c8f5bc91d0:/# ls -ld /tmp/hsperfdata_root
drwxr-xr-x 1 root root 4096 Jul  9 13:57 /tmp/hsperfdata_root
```

Few things to check
- there is an extra `.` at the end of the `ls -rtl /tmp/hsperfdata_root/` output that you provided, that means there might be other ACL (like SELinux) involved to control access to this file
- the issue does not seem related to the attach process or the agent, but rather the ability to read files in `/tmp/hsperfdata_root` with the user that is being used for attaching, in your case `cat /tmp/hsperfdata_root/69` (where `69` is the JVM pid on container) should trigger an error as the file can't be read.

Disclamer: I'm not an expert in Docker/Openshift/SELinux/containers.

**Comment by WassimDhib** [comment] 2021-07-13 08:59
Yes for sure there is an issue with the ACL related to the Openshift configuration.

I see that the JvmDiscoverer.java  was added to version v1.23.0 as part of "[Attacher improvements](https://github.com/elastic/apm-agent-java/commit/5c73fc0519c145a3d4fb38c02f456acb1854fe29#diff-52462b2238029e585b31aa9c4dc9112fb1476ffd25bd1cc485b287634c91a816)"

In my use case, I'd prefer to fallback to a prior v1.22.0 behavior if read permissions are not set on hsperfdata

Actually agent v1.22.0  is fully working in my environment if we set aside the fact that it's causing CPU spikes for some containers (may be 5%).

**Comment by eyalkoren** [comment] 2021-07-19 14:14
This is not necessarily a read permission issue.
I don't think it can be a read permission of the files because:
- we filter those using `canRead()`
- we don't really read their contents
- you don't see any error in the cli tool log

It may be a read permission of the folder, where `listFiles()` doesn't throw exception, only returns `null`. We can add a `canRead()` check with logging on the folder to get this info.

But the difference from `jps` (used in 1.22.0) may also be the tmp directories we look at. I'll take a deeper look into this when I get the chance

**Comment by eyalkoren** [comment] 2021-07-20 11:03
@WassimDhib a couple of followup questions:
- Can you see both users when logging in, e.g. through `cat /etc/passwd`?
- You cannot login with the same user that runs the app, but is there a way t `su` to it?
- Can you share the output of `ls /tmp -l | grep hsperfdata`?

**Comment by SylvainJuge** [comment] 2022-02-02 16:02
Hi @WassimDhib , this issue hadn't any update in a while, does the issue still happens in your environment ?
I will close it for now, feel free to comment and/or provide any feedback for further investigation, we can re-open if relevant.

**Closed by SylvainJuge** 2022-02-02 16:02 UTC
Labels: agent-java, triage
