### ISSUE TITLE
WebFlux - transaction has status code 200 where it should be 500

### ISSUE THREAD

**Issue by sangkyunkim89** [elastic/apm-agent-java#1938] opened 2021-07-28 11:37 UTC
1. spring version 2.2.6 webflux, netty
```
    @Operation(
        summary = "상품 이미지 검색", description = "상품 이미지 검색 api", responses = {
            @ApiResponse(responseCode = "200", description = "상품 이미지 검색 성공", content = @Content(schema = @Schema(implementation = GoodsDTOV1.ImageResponse.class))),
            @ApiResponse(responseCode = "404", description = "상품 이미지 검색 실패", content = @Content(schema = @Schema(implementation = GoodsDTOV1.ImageResponse.class)))
        }
    )
    @GetMapping("/goods")
    @ReactorCacheables(cacheNames = CacheNameConstant.GOODS_IMAGE_LIST, key = "getCacheKey(#method)")
    public Mono<ResponseDTOV2> getGoodsList(@ParameterObject @ModelAttribute @Valid GoodsDTOV1.Search goods) {
        return goodsService.getGoodsList(goods.getUrl(), ImageSearchTypeEnum.getValue(goods.getImageSearchType()))
            .flatMap(goodsImageVO -> {

                final GoodsDTOV1.ImageResponse imageResponse = goodsMapStruct.toDTO(goodsImageVO);

                if (1 == 1) {
                    throw new RuntimeException();
                }

                return Mono.just(
                    ResponseDTOV2.builder().data(imageResponse).build()
                );
            });
    }


Obviously a status 500 internal server error occurred.
In elastic-apm it comes out as 200

```
![image](https://user-images.githubusercontent.com/65607130/127263894-cb53cc26-b267-4499-933e-9a829ec9e95a.png)

![image](https://user-images.githubusercontent.com/65607130/127315811-1dbe225a-7934-4c32-b6e9-f0aab53ec9ce.png)

```
    @Operation(
        summary = "상품 이미지 검색", description = "상품 이미지 검색 api", responses = {
            @ApiResponse(responseCode = "200", description = "상품 이미지 검색 성공", content = @Content(schema = @Schema(implementation = GoodsDTOV1.ImageResponse.class))),
            @ApiResponse(responseCode = "404", description = "상품 이미지 검색 실패", content = @Content(schema = @Schema(implementation = GoodsDTOV1.ImageResponse.class)))
        }
    )
    @GetMapping("/goods")
    @ReactorCacheables(cacheNames = CacheNameConstant.GOODS_IMAGE_LIST, key = "getCacheKey(#method)")
    public Mono<ResponseDTOV2> getGoodsList(@ParameterObject @ModelAttribute @Valid GoodsDTOV1.Search goods) {

         if (1 == 1) {
                throw new RuntimeException();
         }

        return goodsService.getGoodsList(goods.getUrl(), ImageSearchTypeEnum.getValue(goods.getImageSearchType()))
            .flatMap(goodsImageVO -> {

                final GoodsDTOV1.ImageResponse imageResponse = goodsMapStruct.toDTO(goodsImageVO);



                return Mono.just(
                    ResponseDTOV2.builder().data(imageResponse).build()
                );
            });
    }
```
![image](https://user-images.githubusercontent.com/65607130/127316009-07d74a0e-7cd3-476c-aa45-64eb19f96e7e.png)

If the exception is outside of mono, it is exposed normally, but if an error occurs inside mono, it does not work properly.

404 is normal
![image](https://user-images.githubusercontent.com/65607130/127264186-dabdf079-591a-469b-a5de-55b2471c29ca.png)

**Comment by SylvainJuge** [comment] 2021-07-28 12:48
Hi @sangkyunkim89 , thanks for reporting this.

We usually prefer to deal with such reports in our forum first, and only keep issues when actual changes are required in the agent.

Do you have an error handler in your application that gets executed when an exception is thrown ?
Since you are using annotated controllers, it should be something like this (here we explicitly set 500 status code for any error).
```
    @ExceptionHandler
    public ResponseEntity<String> handleException(RuntimeException e) {
        return ResponseEntity.status(500)
            .body(greetingHandler.exceptionMessage(e));
    }
```

The difference when the exception is thrown within the `Mono` operator body and before building the `Mono` is that in the first case it's dispatched to the error handler (if any) when the body is executed, and in the second case it's thrown when dispatching the request (which might not be always captured by the error handler as it's an application bug).

In practice, capturing errors (exceptions) and status codes are not related, thus we can have errors reported on transactions that execute successfully with 200 HTTP status (the opposite is also true).

**Comment by sangkyunkim89** [comment] 2021-07-28 15:10
@SylvainJuge thank u 
but I was already processing like this
```
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    @ExceptionHandler(value = {
            Exception.class,
            MismatchedInputException.class
    })
    public ErrorResponseDTO handleUnknownException(Exception ex, ServerHttpRequest serverHttpRequest) {
        log.error(makeExceptionMessage(ex, serverHttpRequest), ex);

        return ErrorResponseDTO.create(ex);
    }
```

![image](https://user-images.githubusercontent.com/65607130/127347190-e8987f26-d203-4383-9806-4db300d6a843.png)

**Comment by sangkyunkim89** [comment] 2021-07-28 15:14
@SylvainJuge i test 
```
@GetMapping("/goods")
    @ReactorCacheables(cacheNames = CacheNameConstant.GOODS_IMAGE_LIST, key = "#goods.getCacheKey(#method)")
    public Mono<ResponseDTOV2> getGoodsList(@ParameterObject @ModelAttribute @Valid GoodsDTOV1.Search goods) throws Exception {
				if (1 == 1) {
//                    ElasticApm.currentTransaction().captureException(new Exception());
            throw new RuntimeException();
//                    return Mono.error(new Exception());

        }
				

        return goodsService.getGoodsList(goods.getUrl(), ImageSearchTypeEnum.getValue(goods.getImageSearchType()))
            .flatMap(goodsImageVO -> {

                final GoodsDTOV1.ImageResponse imageResponse = goodsMapStruct.toDTO(goodsImageVO);

                return Mono.just(
                    ResponseDTOV2.builder().data(imageResponse).build()
                );
            });
    }
```
i tested
I tried putting the exception to the outside instead of inside the monologic, but an internal server error occurred

result image

![image](https://user-images.githubusercontent.com/65607130/127347665-fb9cc162-6dae-476f-b046-7d087bf315a0.png)

**Comment by sangkyunkim89** [comment] 2021-07-29 01:27
@SylvainJuge 
I want to see it as an error 500, but can I only see the error that comes with number 200 like the image above?

**Comment by SylvainJuge** [comment] 2021-07-30 07:33
Hi @sangkyunkim89 ,

One thing that I forgot to ask, is which version of the agent are you using ? we released the `1.25.0` recently, thus make sure to try with this version first to ensure that it's not something already fixed.

Also, do you have multiple exceptions handler by chance ?

I tried to reproduce the issue with our test application but did not manage to reproduce the behavior that you observed, thus I guess that the next logical step would be to try debugging the agent behavior on your side as I don't have access to your application. Adding the sources of the agent on your project and set some breakpoints in your IDE should be enough.

For Webflux, the part that deals with end of the transaction is defined in `endTransaction` method : 
https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-spring-webflux/apm-spring-webflux-plugin/src/main/java/co/elastic/apm/agent/springwebflux/TransactionAwareSubscriber.java#L245

In particular, the status code is set within the `fillResponse` method : https://github.com/elastic/apm-agent-java/blob/b3a8c147d33e360e8d3bf30193ff79103e904fdc/apm-agent-plugins/apm-spring-webflux/apm-spring-webflux-plugin/src/main/java/co/elastic/apm/agent/springwebflux/TransactionAwareSubscriber.java#L359

What I'd like to know in your case is if we have a status code provided or if the `200` comes from the default that we set when we do not have such status.

**Comment by sangkyunkim89** [comment] 2021-07-30 07:50
@SylvainJuge  
hi~~ im already using 1.25.0 apm agent...

in above example, i return status 500 internal error


There is only one exception handler, and you mean that if an exception occurs in mono logic and returns as a 500 status code, it is normal for a 500 error to appear in kibana?

I have to raise an exception outside of mono logic and it gives 500 error in kibana

**Comment by SylvainJuge** [comment] 2021-07-30 08:10
For the multiple exception handlers, I would just need to be sure that only a single one would be applied, here it seems to be the case thus it's not the issue.

The difference between the exception to be thrown outside or within the mono logic is the following:
- outside of mono logic: it gets triggered in the request dispatching phase (request processing hasn't been executed yet)
- inside of mono logic: it gets triggered when the request is being processed.

Thus, while it's very close from code perspective, it's completely different when it gets executed, as different hooks are used to capture both types of exceptions.

Knowing if `statusCode` is `null` when the transaction completes would allow us to know if the `200` status fallback is applied, if so, that means in your case we might terminate the transaction _before_ the exception handler execution and thus before the status code is known.

**Comment by sangkyunkim89** [comment] 2021-07-30 08:26
@SylvainJuge 
Now that I've tested it, I know the cause.
If we request our server and immediately throw an exception in mono logic, a 500 error is shown in kibana
However, if I request highlevelclient within mono logic and raise an exception after receiving 200, it comes out as 200 in kibana.

**Comment by SylvainJuge** [comment] 2021-07-30 08:37
I'm not really sure to understand what happens here, what is the meaning of `highlevelclient` in your case ?

If you receive a 200 status code from a service, this will be what the agent captures, if there is an exception thrown while processing the response on the Webflux client side, this is something that should be handled by the webflux client instrumentation (which is not available yet).

**Comment by sangkyunkim89** [comment] 2021-07-30 08:43
@SylvainJuge 
exmaple
```
@GetMapping("/test")
    public Mono<ResponseDTOV2> getTest() {
        return searchElastic().flatMap(a -> {

            // receive status 200
            

            //throw exception after status 200
            if (a == 1) {
                throw new RuntimeException();
            }

            return Mono.just(
                ResponseDTOV2.builder().data(1).build()
            );
        });
    }
 
    public Mono<Response> searchElastic() {
        return elasticsearch.search();
    }
```
in above case, show 200 status in kibana
but
```
@GetMapping("/test")
    public Mono<ResponseDTOV2> getTest() {
        return Mono.just(1).flatMap(a -> {

            //Exception immediately
            if (a == 1) {
                throw new RuntimeException();
            }

            return Mono.just(
                ResponseDTOV2.builder().data(1).build()
            );
        });
    }
```
in above case, show status 500 in kibana

**Comment by SylvainJuge** [comment] 2021-07-30 09:56
I see, this happens with the following conditions:
- using a mono with non immediate result (not `Mono.just(...)`), for example `Mono.just("hello").delayElement(Duration.ofMillis(100)).flatMap(s -> {throw new RuntimeException("intentional exception");})`
- using an exception handler

What happens in this case is that the transaction is ended with `200` status code before the exception handler is executed, which explains why we get the unexpected status. I will investigate a bit further to see if it's something that could be easily fixed or not.

**Comment by sangkyunkim89** [comment] 2021-07-30 10:22
@SylvainJuge 
thank u I hope you can fix it soon!

I have one more question, if I use the highlevelclient of es, there is a line in the timeline saying that I used it, but when I use the webclient, nothing comes out, so does the webclient not support it?

**Comment by SylvainJuge** [comment] 2021-07-30 13:12
Yes, that's correct, this is because Webflux client is not (yet) supported with automatic instrumentation, see #1303 for details.

**Comment by SylvainJuge** [comment] 2021-07-30 17:57
I've implemented a simple work-around, can you check [this snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1948/2/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.25.1-SNAPSHOT.jar) and tell us if the issue is resolved in your case ?

**Comment by sangkyunkim89** [comment] 2021-07-30 18:13
@SylvainJuge goods!! thank u 
im happy because of your speed feedback

![image](https://user-images.githubusercontent.com/65607130/127694811-68935467-4625-4414-9494-ca1f0848d7cc.png)

**Comment by sangkyunkim89** [comment] 2021-07-30 18:52
@SylvainJuge 

public void onOutgoingRequest(WebClient.RequestHeadersUriSpec<?> request) {
        // creates a span representing the external call
        final Transaction transaction = ElasticApm.currentTransaction();
        Span span = ElasticApm.currentSpan()
            .startSpan("external", "http", null)
            .setName("get method imagine-api call");
        try (final Scope scope = transaction.activate()) {
            span.injectTraceHeaders((name, value) -> request.header(name, value));
        } catch (Exception e) {
            span.captureException(e);
            throw e;
        } finally {
            span.end();
        }
    }

```
public Response onOutgoingRequest(Request request) throws Exception {
    // creates a span representing the external call
    Span span = ElasticApm.currentSpan()
            .startSpan("external", "http", null)
            .setName(request.getMethod() + " " + request.getHost());
    try (final Scope scope = transaction.activate()) {
        span.injectTraceHeaders((name, value) -> request.addHeader(name, value));
        return request.execute();
    } catch (Exception e) {
        span.captureException(e);
        throw e;
    } finally {
        span.end();
    }
}
```

change custom like bottom
```
public void onOutgoingRequest(WebClient.RequestHeadersUriSpec<?> request) {
        // creates a span representing the external call
        final Transaction transaction = ElasticApm.currentTransaction();
        Span span = ElasticApm.currentSpan()
            .startSpan("external", "http", null)
            .setName("get method imagine-api call");
        try (final Scope scope = transaction.activate()) {
            span.injectTraceHeaders((name, value) -> request.header(name, value));
        } catch (Exception e) {
            span.captureException(e);
            throw e;
        } finally {
            span.end();
        }
    }
```

**Comment by SylvainJuge** [comment] 2021-08-02 07:13
Hi @sangkyunkim89 ,

First, did you managed to try with the snapshot to confirm if the initial issue with status code is resolved ?

On high level, your example shows how to create an HTTP span, but the issue with Webflux is that execution is asynchronous, and thus starting and ending the span is tricky. What could probably be done though is to use something like what is done with `TransactionAwareSubscriber` in our agent to properly wrap the HTTP client request execution.

Also, there has been a recent PR for adding Webflux client, thus it might be also be relevant to wait a bit until we have proper support for it.

**Comment by sangkyunkim89** [comment] 2021-08-02 13:01
@SylvainJuge 
Like the image below, I downloaded the snapshot you gave me and tried it. It's coming out well. Can I use this in the product?

![image](https://user-images.githubusercontent.com/65607130/127866041-749fd7bd-76ee-430a-8162-97644e0cdf6a.png)

**Comment by SylvainJuge** [comment] 2021-08-02 13:36
Thanks for the confirmation that it now works as expected !

I will now merge https://github.com/elastic/apm-agent-java/pull/1948 so it will be included in the next release.

Yes, you can use it with your application, it should be fine as there hasn't been many changes since the latest release and thus the risk of regression is very minimal.
Make sure to subscribe for release notifications to upgrade when it's released.

**Comment by sangkyunkim89** [comment] 2021-08-02 13:42
@SylvainJuge 
Thank you so much. Thank you so much for responding so quickly!
I hope the webclient also supports it soon!!
Good day

**Comment by SylvainJuge** [comment] 2021-08-18 08:05
The #1948 PR hasn't been merged yet. There was a few changes to make things simpler and reliable.

@sangkyunkim89 if you can, could you try the [latest snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1948/16/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.25.1-SNAPSHOT.jar). It should behave exactly as the previous version you tested, but any extra feedback is always welcome :-).

**Comment by sangkyunkim89** [comment] 2021-08-18 14:17
okay
@SylvainJuge 
i will try soon

**Comment by pcthomatos** [comment] 2021-08-19 20:22
I was having issues with headers being passed into the application. 
But with the latest snapshot it works again. 
This was only an issue with 1.25.0

**Comment by SylvainJuge** [comment] 2021-08-20 07:53
> I was having issues with headers being passed into the application.
> But with the latest snapshot it works again.
> This was only an issue with 1.25.0

Thanks for the feedback, thus it means we might have also fixed a latent bug as a side effect.

For reference, could you describe in more detail what did not worked as expected in `1.25.0` that is not working with this snapshot ? For example, is it one of the following ?
- HTTP headers not being properly captured by the agent on Webflux
- Agent altering the behavior of Webflux and preventing your application to read and handle them properly

**Comment by pcthomatos** [comment] 2021-08-20 18:24
Just to clarify.

With version 1.25.0 our authorization headers weren't coming into our webflux app.
With 1.24.0 and the new snapshot, functionality is restored.

**Comment by sangkyunkim89** [comment] 2021-08-21 11:25
@SylvainJuge 
I tested it, but when an exception occurs, it is displayed as a 500 error.
but the webclient is still not tracking

**Comment by SylvainJuge** [comment] 2021-08-23 07:22
Thanks for the clarification @pcthomatos.

@sangkyunkim89 for the webclient, it's still not supported (will be covered by #1306), thus this is expected.
Thanks a lot for testing, so we can conclude that in your case it's now working as expected, we can thus merge this PR.

**Closed** 2021-08-23 08:38 UTC
Labels: agent-java, community

**Comment by sangkyunkim89** [comment] 2021-09-09 04:55
There was a problem with the second agent you sent me Whatever it is,
there's no timeline
[image: Pasted Graphic.png]

The first one I sent came out well


2021년 8월 23일 (월) 오후 5:38, SylvainJuge ***@***.***>님이 작성:

**Comment by sangkyunkim89** [comment] 2021-09-09 04:56
[image: image.png]

2021년 9월 9일 (목) 오후 1:55, nic k ***@***.***>님이 작성:

**Comment by jeff-lauterbach-by** [comment] 2021-09-16 16:55
Oh nevermind - It looks like 1.26.0 was just released and it seems to resolve the issue I was facing.  Thanks!
