### ISSUE TITLE
Public API does not work on WildFly

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#362] opened 2018-11-29 16:55 UTC
See https://discuss.elastic.co/t/java-apm-agent-throws-classnotfoundexception-in-wildfly/158779

Reproduced in elastic/apm-agent-java#361

**Comment by eyalkoren** [comment] 2018-12-09 10:14
Considering all factors, such as 
- implications on users
- safety
- robustness
- maintainability 

I chose to go with the big refactor (@felixbarny second suggested option), so that all agent code is rooted in the `co.elastic.apm.agent` package. OpenTracing and public APIs are not under this root.
The `org.osgi.framework.bootdelegation` setting was updated to allow delegation only for agent-specific classes. In addition, the actual fix for WildFly was through same enablement using s
the `jboss.modules.system.pkgs` setting.

I moved the changes from #361 that reproduce the problem to the refactor+fix PR (#376) because this breaks the build, so closing #361.

**Closed** 2018-12-10 10:59 UTC
Labels: [zube]: In Review, type: bug
