### ISSUE TITLE
Webflux missing spans in timeline

### ISSUE THREAD

**Issue by sangkyunkim89** [elastic/apm-agent-java#2114] opened 2021-09-09 05:01 UTC
hi

@SylvainJuge 

Thank you so much for fixing the bugs I received before.
But I found a bug in the second snapshot version
The problem is that the timeline does not appear

![Pasted Graphic](https://user-images.githubusercontent.com/90259578/132625326-790156af-8bb8-40a0-98ca-eff357be2220.png)

The first version you gave me came out well

![image](https://user-images.githubusercontent.com/90259578/132625408-5ae19bcd-7f7f-4163-a9e2-30ae067954d1.png)

Check out our history link here
https://github.com/elastic/apm-agent-java/issues/1938

**Comment by SylvainJuge** [comment] 2021-09-09 08:55
The snapshot that was sent in #1938 is no longer available and the related PR has been merged (but not released yet).
From history, I assume that you are using a Webflux application here.

As the issue is a bit different that the one initially reported in #1938, we need to properly qualify it to know if it's a regression or not.

Could you please do the following with two versions of the agent:
- configure your agent with `log_level=debug` and `log_file=agent.log` to generate an external debug log file
- truncate the `agent.log` file and restart the application
- execute one call to the `GoodsReviewControllerV1#put` transaction
- copy `agent.log` and send it back for investigation

The two versions of the agent to test here are:
- [latest snapshot](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=co.elastic.apm&a=elastic-apm-agent&v=LATEST)
- [1.25.0](https://repo.maven.apache.org/maven2/co/elastic/apm/elastic-apm-agent/1.25.0/elastic-apm-agent-1.25.0.jar)

**Comment by sangkyunkim89** [comment] 2021-09-09 09:48
@SylvainJuge 
u send to me first this https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1948/2/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.25.1-SNAPSHOT.jar

next https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1948/16/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.25.1-SNAPSHOT.jar

**Comment by SylvainJuge** [comment] 2021-09-09 12:01
Yes, but those artifacts are no longer available, that's why I suggested we try with the two versions listed above.
- latest snapshot is the one that is closer to get released for now
- the 1.25.0 version is the previous version where the trace should include DB spans as expected.

Also, providing debug logs with both versions here is essential as it helps to know what is the sequence of events that might have caused this, without this it will be really hard to investigate further, unless you have a sample application that allows to easily reproduce the issue.

**Comment by sangkyunkim89** [comment] 2021-09-13 01:51
@SylvainJuge 
1.25.0 version dont work...

![image](https://user-images.githubusercontent.com/65607130/133012293-4c0e19bb-a338-45d6-b510-b867bd6e1c79.png)

Updated
7-22

what should I test?

**Comment by SylvainJuge** [comment] 2021-09-13 07:28
Hi @sangkyunkim89 ,

What we need for further investigation is to compare two agent logs
- one with the version that works as expected (with the DB spans visible in Kibana)
- one with the latest version from master where the Webflux status code issue is fixed (but that might have introduced regressions in your use-case).

In order to collect agent debug logs, please do the following with the two agent versions:

### Capturing agent debug logs

Here, we will refer to the agent log file as `/tmp/agent.log`, but any other location could be used.

- configure the agent with `log_level=debug` ([doc](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-level)) and `log_file=/tmp/agent.log` ([doc](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-file))
- truncate the `/tmp/agent.log` file and restart the application
- execute a few transactions which aren't properly captured by the agent
- copy the `/tmp/agent.log` file and send it back for investigation

Having the full log files here helps to distinguish agent versions as the agent hash/version is included at the beginning just before the agent configuration.

**Comment by SylvainJuge** [comment] 2022-06-17 12:58
Hi @sangkyunkim89 , this issue hadn't had any update in a while, could you help us by telling if the issue is still present with a more recent version ? From [your recent comments and screenshots on another issue](https://github.com/elastic/apm-agent-java/issues/2666#issuecomment-1154655506) it seems that the context propagation properly works as expected with Webflux.

If the issue still persists, then could you provide the agent logs with the procedure [described here](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html#trouble-shooting-logging-procedure) and execute only a single transaction where this issue occurs ?

**Closed** 2022-07-07 15:20 UTC
Labels: agent-java, community, triage
