### ISSUE TITLE
Can't disable ElasticAPM 1.18.0/1.17.0  

### ISSUE THREAD

**Issue by kushwiz** [elastic/apm-agent-java#1457] opened 2020-10-27 00:43 UTC
We kindly ask to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/apm) first. In addition to awesome, knowledgeable community contributors, core APM developers are on the forums every single day to help you out as well, so your questions will reach a wider audience there. If we confirm that there is a bug, then you can open an issue in this repo.

## Describe the bug
Can't disable the ElasticAPMAttacher agent via app properties

## Steps to reproduce
1. Use java 11 spring boot 2.3 app
2. Add elasticAPM dependencies
3. Set in application.yml
```
elastic:
  apm:
    enabled: false
    instrument: false
    recording: false
```

## Expected behavior
No events or logs from the APM agent being generated

## Debug logs
2020-10-26 17:38:49,685 [Attach Listener] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
2020-10-26 17:38:50,176 [Attach Listener] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.17.0 as PortalApplication on Java 11.0.4 (JetBrains s.r.o) Mac OS X 10.13.6
2020-10-26 17:38:50,176 [Attach Listener] WARN  co.elastic.apm.agent.configuration.StartupInfo - To enable all features and to increase startup times, please configure application_packages
2020-10-26 17:38:50,204 [Attach Listener] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING state
2020-10-26 17:38:56.916  INFO 13200 --- [           main] c.demo.Application     : Started Application in 6.341 seconds (JVM running for 18.214)
2020-10-26 17:39:19,692 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type METRICS with this error: Connection refused (Connection refused)
2020-10-26 17:39:19,693 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 0 seconds (+/-10%)
2020-10-26 17:39:49,697 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type METRICS with this error: Connection refused (Connection refused)
2020-10-26 17:39:49,698 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 1 seconds (+/-10%)
2020-10-26 17:40:19,693 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type METRICS with this error: Connection refused (Connection refused)
2020-10-26 17:40:19,694 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 4 seconds (+/-10%)
2020-10-26 17:40:49,700 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type METRICS with this error: Connection refused (Connection refused)
2020-10-26 17:40:49,700 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 9 seconds (+/-10%)
2020-10-26 17:41:19,695 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type METRICS with this error: Connection refused (Connection refused)
2020-10-26 17:41:19,695 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 16 seconds (+/-10%)

<details>
<summary>Click to expand</summary>

```
2020-10-26 17:38:49,685 [Attach Listener] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
2020-10-26 17:38:50,176 [Attach Listener] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.17.0 as PortalApplication on Java 11.0.4 (JetBrains s.r.o) Mac OS X 10.13.6
2020-10-26 17:38:50,176 [Attach Listener] WARN  co.elastic.apm.agent.configuration.StartupInfo - To enable all features and to increase startup times, please configure application_packages
2020-10-26 17:38:50,204 [Attach Listener] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING state


```
</details>

**Comment by felixbarny** [comment] 2020-10-27 07:04
Thanks for the report!
Closing as duplicate of #1444

**Closed by felixbarny** 2020-10-27 07:04 UTC

**Comment by felixbarny** [comment] 2020-10-27 07:22
I probably have misread your issue. It's not so much that disabling the agent doesn't work but a feature request to support configuration via `application.yml`? Currently, we don't support that as a configuration source. See the [docs](https://www.elastic.co/guide/en/apm/agent/java/current/configuration.html) on which configuration sources we do support.
