### ISSUE TITLE
ERROR co.elastic.apm.agent.bci.IndyBootstrap - Provider "jar" not found

### ISSUE THREAD

**Issue by sunilnagavelli** [elastic/apm-agent-java#2563] opened 2022-03-30 17:02 UTC
We are seeing this error in our Spring Cloud Gateway application deployed on Openshift, but it works well in the local, i am seeing issue only with our Openshift environment. 

Below are the details.

Elastic APM Jar version: 1.30.0, 1.29.0 and 1.28.4
Spring boot version: spring-boot-2.3.10.RELEASE
OpenShift Master: v3.11.0+ec8630f-265
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.0+ea42280
Java: 11
JVM Args: 

ERROR log:
```

Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport
2022-03-30 14:19:31,658 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.30.0 as my-api-gateway on Java 11.0.14.1 Runtime version: 11.0.14.1+1 VM version: 11.0.14.1+1 (Eclipse Adoptium) Linux 3.10.0-1062.18.1.el7.x86_64
2022-03-30 14:19:31,662 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - service_name: my-api-gateway' (source: Environment Variables)
2022-03-30 14:19:31,662 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - environment: 'PR' (source: Environment Variables)
2022-03-30 14:19:31,662 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - enable_experimental_instrumentations: 'true' (source: Java System Properties)
2022-03-30 14:19:31,662 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - server_url: 'https://eapm-instance-nonprod.xxxxx.com:443'  (source: Environment Variables)
2022-03-30 14:19:31,663 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - server_urls: 'https://eapm-instance-nonprod.xxxxx:443'  (source: Environment Variables)
2022-03-30 14:19:31,663 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - application_packages: 'com.my.api.gateway' (source: Environment Variables)
2022-03-30 14:19:33,463 [main] ERROR co.elastic.apm.agent.bci.IndyBootstrap - Provider "jar" not found
java.nio.file.ProviderNotFoundException: Provider "jar" not found
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at co.elastic.apm.agent.util.PackageScanner.getClassNames(PackageScanner.java:61) ~[elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.IndyBootstrap.getClassNamesFromBundledPlugin(IndyBootstrap.java:440) ~[elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.IndyBootstrap.bootstrap(IndyBootstrap.java:399) [elastic-apm-agent.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at java.lang.IndyBootstrapDispatcher.bootstrap(IndyBootstrapDispatcher.java:60) [?:?]
	at java.lang.invoke.BootstrapMethodInvoker.invoke(Unknown Source) [?:?]
	at java.lang.invoke.CallSite.makeSite(Unknown Source) [?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(Unknown Source) [?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(Unknown Source) [?:?]
	at co.elastic.apm.agent.bci.bytebuddy.Instrumented.isInstrumented(Instrumented.java:34) [?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at co.elastic.apm.agent.bci.bytebuddy.InstallationListenerImpl.onAfterWarmUp(InstallationListenerImpl.java:65) [elastic-apm-agent.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$InstallationListener$Compound.onAfterWarmUp(AgentBuilder.java:5221) [elastic-apm-agent.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$WarmupStrategy$Enabled.apply(AgentBuilder.java:11087) [elastic-apm-agent.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:10774) [elastic-apm-agent.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:10712) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:279) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:164) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:150) [elastic-apm-agent.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at co.elastic.apm.agent.premain.AgentMain.loadAndInitializeAgent(AgentMain.java:160) [elastic-apm-agent.jar:1.30.0]
	at co.elastic.apm.agent.premain.AgentMain.init(AgentMain.java:101) [elastic-apm-agent.jar:1.30.0]
	at co.elastic.apm.agent.premain.AgentMain.premain(AgentMain.java:50) [elastic-apm-agent.jar:1.30.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source) [?:?]
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source) [?:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [gateway.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [gateway.jar:?]
#logback.classic pattern: %d %-5level [%thread] %logger{0}: %msg%n

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.3.10.RELEASE)

2022-03-30 14:19:46,779 [main] ERROR co.elastic.apm.agent.bci.IndyBootstrap - Provider "jar" not found
java.nio.file.ProviderNotFoundException: Provider "jar" not found
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
2022-03-30 14:19:33,470 [main] ERROR co.elastic.apm.agent.bci.IndyBootstrap - Provider "jar" not found
java.nio.file.ProviderNotFoundException: Provider "jar" not found
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at co.elastic.apm.agent.util.PackageScanner.getClassNames(PackageScanner.java:61) ~[elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.IndyBootstrap.getClassNamesFromBundledPlugin(IndyBootstrap.java:440) ~[elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.IndyBootstrap.bootstrap(IndyBootstrap.java:399) [elastic-apm-agent.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at java.lang.IndyBootstrapDispatcher.bootstrap(IndyBootstrapDispatcher.java:60) [?:?]
	at java.lang.invoke.BootstrapMethodInvoker.invoke(Unknown Source) [?:?]
	at java.lang.invoke.CallSite.makeSite(Unknown Source) [?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(Unknown Source) [?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(Unknown Source) [?:?]
	at co.elastic.apm.agent.bci.bytebuddy.Instrumented.isInstrumented(Instrumented.java:34) [?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at co.elastic.apm.agent.bci.bytebuddy.InstallationListenerImpl.onAfterWarmUp(InstallationListenerImpl.java:65) [elastic-apm-agent.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$InstallationListener$Compound.onAfterWarmUp(AgentBuilder.java:5221) [elastic-apm-agent.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$WarmupStrategy$Enabled.apply(AgentBuilder.java:11087) [elastic-apm-agent.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:10774) [elastic-apm-agent.jar:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:10712) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:279) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:164) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:150) [elastic-apm-agent.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at co.elastic.apm.agent.premain.AgentMain.loadAndInitializeAgent(AgentMain.java:160) [elastic-apm-agent.jar:1.30.0]
	at co.elastic.apm.agent.premain.AgentMain.init(AgentMain.java:101) [elastic-apm-agent.jar:1.30.0]
	at co.elastic.apm.agent.premain.AgentMain.premain(AgentMain.java:50) [elastic-apm-agent.jar:1.30.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source) [?:?]
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source) [?:?]
2022-03-30 14:19:33,472 [main] WARN  co.elastic.apm.agent.bci.bytebuddy.InstallationListenerImpl - Warmup: instrumented bytecode of co.elastic.apm.agent.bci.bytebuddy.Instrumented does not work as expected
2022-03-30 14:19:35,597 [main] INFO  co.elastic.apm.agent.report.ReporterConfiguration - Both "server_urls" and "server_url" configuration options are set, therefore the "server_urls" configuration will be ignored.
2022-03-30 14:19:35,662 [elastic-apm-server-healthcheck] ERROR co.elastic.apm.agent.bci.IndyBootstrap - Provider "jar" not found
java.nio.file.ProviderNotFoundException: Provider "jar" not found
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at co.elastic.apm.agent.util.PackageScanner.getClassNames(PackageScanner.java:61) ~[elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.IndyBootstrap.getClassNamesFromBundledPlugin(IndyBootstrap.java:440) ~[elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.bci.IndyBootstrap.bootstrap(IndyBootstrap.java:399) [elastic-apm-agent.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at java.lang.IndyBootstrapDispatcher.bootstrap(IndyBootstrapDispatcher.java:60) [?:?]
	at java.lang.invoke.BootstrapMethodInvoker.invoke(Unknown Source) [?:?]
	at java.lang.invoke.CallSite.makeSite(Unknown Source) [?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(Unknown Source) [?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(Unknown Source) [?:?]
	at javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source) [?:?]
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source) [?:?]
	at javax.net.ssl.HttpsURLConnection.<init>(Unknown Source) [?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source) [?:?]
	at sun.net.www.protocol.https.Handler.openConnection(Unknown Source) [?:?]
	at sun.net.www.protocol.https.Handler.openConnection(Unknown Source) [?:?]
	at java.net.URL.openConnection(Unknown Source) [?:?]
	at co.elastic.apm.agent.util.UrlConnectionUtils.openUrlConnectionThreadSafely(UrlConnectionUtils.java:29) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.report.ApmServerClient.startRequestToUrl(ApmServerClient.java:139) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.report.ApmServerClient.executeForAllUrls(ApmServerClient.java:276) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.report.ApmServerHealthChecker.call(ApmServerHealthChecker.java:65) [elastic-apm-agent.jar:?]
	at co.elastic.apm.agent.report.ApmServerHealthChecker.call(ApmServerHealthChecker.java:42) [elastic-apm-agent.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by eyalkoren** [comment] 2022-03-31 08:50
Thanks for reporting!
We will look into that.
I don't think it is a real lack of a proper provider for `jar`.
Maybe it's something with how the scheme is parsed from the URI on this system or maybe disability to find through `ServiceLoader` - for example, inappropriate class loader lookup or using modules in a way that doesn't expose this service provider where we need it

**Comment by sunilnagavelli** [comment] 2022-03-31 09:39
> Thanks for reporting! We will look into that. I don't think it is a real lack of a proper provider for `jar`. Maybe it's something with how the scheme is parsed from the URI on this system or maybe disability to find through `ServiceLoader` - for example, inappropriate class loader lookup or using modules in a way that doesn't expose this service provider where we need it

Thanks for the response @eyalkoren, i have ensured that the jar in place well, i think we can see that logs itself where the Jar is picked up and getting initialised (log snippet below)
```
2022-03-30 14:19:31,658 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.30.0 as my-api-gateway on Java 11.0.14.1 Runtime version: 11.0.14.1+1 VM version: 11.0.14.1+1 (Eclipse Adoptium) Linux 3.10.0-1062.18.1.el7.x86_64
```
Here are my environment variables and also the java arguments passed w.r.t to elasticsearch
```
  ELASTIC_APM_APPLICATION_PACKAGES: com.optum.link.gateway
  ELASTIC_APM_SERVER_URL: https://eapm-nonprod-xxxx.xxxxx.com:443
  ELASTIC_APM_ENVIRONMENT: PR
  ELASTIC_APM_SERVICE_NAME: my-api-gateway_
  ELASTIC_APM_SERVER_URLS: "https://eapm-nonprod-xxxxx.xxxxx.com:443"
  ELASTIC_LOG_FILE: "/logs/output.log"
  ELASTIC_APM_LOG_LEVEL: INFO

Java Opts: " -javaagent:/opt/elastic/apm/elastic-apm-agent.jar -Delastic.apm.enable_experimental_instrumentations=true -Delastic.apm.enabled=true -Delastic.apm.verify.server.cert=false -Delastic.apm.log_file=/opt/elastic/elastic_agent.log"
```

Not sure what is missing here which is failing the apm agent jar initialisation well.

**Comment by eyalkoren** [comment] 2022-03-31 11:45
The problem is not with locating the agent jar, that would have been easier 🙂 
The agent doesn't find a proper `FileSystemProvider` for the `jar` scheme. 

Please run the following snippet somewhere in your application and provide the output: 
```
System.out.println(FileSystemProvider.installedProviders());
```

Also, please share your JPMS setup- do you setup Java modules in your system? If so - how exactly?

Thanks

**Comment by eyalkoren** [comment] 2022-03-31 14:38
Some more info: I created a small module Java app and tried to attach an agent to it when running with Eclipse Adoptium 11.0.14.1 using a `--module-path`. It failed much earlier:
```
[elastic-apm-agent] ERROR Failed to start agent
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at co.elastic.apm.agent.premain.AgentMain.loadAndInitializeAgent(AgentMain.java:160)
	at co.elastic.apm.agent.premain.AgentMain.init(AgentMain.java:101)
	at co.elastic.apm.agent.premain.AgentMain.premain(AgentMain.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at com.lmax.disruptor.util.Util$1.run(Util.java:103)
	at com.lmax.disruptor.util.Util$1.run(Util.java:100)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.lmax.disruptor.util.Util.<clinit>(Util.java:109)
	at com.lmax.disruptor.RingBufferFields.<clinit>(RingBuffer.java:34)
	at com.lmax.disruptor.dsl.Disruptor.<init>(Disruptor.java:137)
	at co.elastic.apm.agent.report.ApmServerReporter.<init>(ApmServerReporter.java:116)
	at co.elastic.apm.agent.report.ReporterFactory.createReporter(ReporterFactory.java:38)
	at co.elastic.apm.agent.impl.ElasticApmTracerBuilder.build(ElasticApmTracerBuilder.java:164)
	at co.elastic.apm.agent.impl.ElasticApmTracerBuilder.build(ElasticApmTracerBuilder.java:122)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:149)
	... 13 more
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe
	at co.elastic.apm.agent.premain.ShadedClassLoader.findClass(ShadedClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 24 more
```
So I don't think the reported issue is related.

**Comment by sunilnagavelli** [comment] 2022-03-31 14:38
@eyalkoren , I did sys out for the FileSystemProvider and got the below information
```
2022-03-31 14:35:03,015 [elastic-apm-remote-config-poller] INFO  co.elastic.apm.agent.configuration.ApmServerConfigurationSource - Received new configuration from APM Server: {}
--
  | ==========================================================================
  | [sun.nio.fs.LinuxFileSystemProvider@1ce2029b, jdk.internal.jrtfs.JrtFileSystemProvider@43090195]
  | =============================================================================

```
Not sure what JPMS means, we are using spring boot application structure, we used gradle to build and package.
<img width="363" alt="image" src="https://user-images.githubusercontent.com/40353788/161081625-a6d1bf63-4832-4d0f-9c61-9b17c9e36cce.png">

**Comment by eyalkoren** [comment] 2022-04-03 06:32
> `[sun.nio.fs.LinuxFileSystemProvider@1ce2029b, jdk.internal.jrtfs.JrtFileSystemProvider@43090195]`

Yep, that's definitely the culprit. This is what I get for the macOS build of the same version:
```
Starting Elastic APM 1.30.1-SNAPSHOT.UNKNOWN as Test on Java 11.0.14.1 Runtime version: 11.0.14.1+1 VM version: 11.0.14.1+1 (Eclipse Adoptium) Mac OS X 12.1
...
[sun.nio.fs.MacOSXFileSystemProvider@21a06946, jdk.nio.zipfs.ZipFileSystemProvider@77f03bb1, jdk.internal.jrtfs.JrtFileSystemProvider@326de728]
```

I found [this Temurin issue](https://github.com/adoptium/temurin-build/issues/2696), please check whether other builds contain the missing jar, or try with another JVM.

Looking forward to hear back, so we can close this issue, maybe with a related entry to the [troubleshooting page](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html)

**Comment by sunilnagavelli** [comment] 2022-04-03 20:13
@eyalkoren , This works from local (IntelliJ IDE) well, we are using the same image, So far i wonder what could be different with Openshift, so do you meant to say temurin and Openshift might have issues getting along in this context., Which version do you suggest other than Temurin?

Sorry but i am little confused on what needs to be done over here with our Openshift instance, please let me know.

**Comment by eyalkoren** [comment] 2022-04-04 06:27
> This works from local very well (IntelliJ IDE on MacOS)

Right, if you run `System.out.println(FileSystemProvider.installedProviders());` on your macOS, the output will include `jdk.nio.zipfs.ZipFileSystemProvider`, that is not available similarly in the Linux build of this same JDK version.
I can't say whether it is not packaged or not made available through the service loader mechanism.
However, I assume it is specific to the Temurin build for Linux because we never got heard of this so far.

So, my suggestion is that you try another image that uses some other OpenJDK 11 build (non-Adoptium) if it is possible.

**Comment by sunilnagavelli** [comment] 2022-04-04 11:09
Oh, changing the image would be crucial decision for our application cause we are using the same with other applications too, the way we use docker image is we build a base image and add necessary extensions specific to an application while building it and also our spring cloud gateway is bound to use this temurin image, please allow me some time on this to see what our engineering team would has to comment on changing the image. 

But on the on the other hand, as i mentioned, this working in the local with the same temurin based docker image, how would be different while we are deploying it to openshift, ideally we push the changes that works in the local to our environments, we expect no other changes that a different from the local configuration right? 
@eyalkoren

**Comment by eyalkoren** [comment] 2022-04-04 12:32
> we expect no other changes that a different from the local configuration right?

Ideally yes, I don't know what the source of the difference is. Maybe your engineering team can debug this JVM and see why we fail to see the `jdk.nio.zipfs.ZipFileSystemProvider` class.
If you can only package an image that uses another JVM just for testing, that will already provide at least a direction.

**Comment by sunilnagavelli** [comment] 2022-04-05 04:13
I am trying to check this with adoptopenjdk to see if that resolves the issue, we might need some time on this as we also potentially need to make few code changes. please wait for my confirmation @eyalkoren

**Comment by sunilnagavelli** [comment] 2022-04-05 09:18
> Some more info: I created a small module Java app and tried to attach an agent to it when running with Eclipse Adoptium 11.0.14.1 using a `--module-path`. It failed much earlier:
> 
> ```
> [elastic-apm-agent] ERROR Failed to start agent
> java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at co.elastic.apm.agent.premain.AgentMain.loadAndInitializeAgent(AgentMain.java:160)
> 	at co.elastic.apm.agent.premain.AgentMain.init(AgentMain.java:101)
> 	at co.elastic.apm.agent.premain.AgentMain.premain(AgentMain.java:50)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
> 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
> Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
> 	at com.lmax.disruptor.util.Util$1.run(Util.java:103)
> 	at com.lmax.disruptor.util.Util$1.run(Util.java:100)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at com.lmax.disruptor.util.Util.<clinit>(Util.java:109)
> 	at com.lmax.disruptor.RingBufferFields.<clinit>(RingBuffer.java:34)
> 	at com.lmax.disruptor.dsl.Disruptor.<init>(Disruptor.java:137)
> 	at co.elastic.apm.agent.report.ApmServerReporter.<init>(ApmServerReporter.java:116)
> 	at co.elastic.apm.agent.report.ReporterFactory.createReporter(ReporterFactory.java:38)
> 	at co.elastic.apm.agent.impl.ElasticApmTracerBuilder.build(ElasticApmTracerBuilder.java:164)
> 	at co.elastic.apm.agent.impl.ElasticApmTracerBuilder.build(ElasticApmTracerBuilder.java:122)
> 	at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:149)
> 	... 13 more
> Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe
> 	at co.elastic.apm.agent.premain.ShadedClassLoader.findClass(ShadedClassLoader.java:77)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 24 more
> ```
> 
> So I don't think the reported issue is related.

This is for you, The fix for this issue should setting up your java runtime this way, should fix your issue running your local setup.
```
$JAVA_HOME/bin/jlink \
         --add-modules java.compiler,java.base,java.logging,java \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime
```

**Comment by sunilnagavelli** [comment] 2022-04-05 09:24
and @eyalkoren , **I fixed the issue, now this error is gone, eapm jar getting initialised successfully and sending the data to elastic apm**, and the good part that i've managed to fix it without having to change the Temurin. 🙂

**Solution**: Add ```jdk.zipfs``` module to your java runtime environment.

Please proceed to close this issue.

**Comment by eyalkoren** [comment] 2022-04-05 09:44
> This is for you, The fix for this issue should setting up your java runtime this way, should fix your issue running your local setup.
>
> $JAVA_HOME/bin/jlink \
         --add-modules java.compiler,java.base,java.logging,java \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime

Thanks! 
Ideally, the fix we would look for would be to modify the agent so that it supports such setups out of the box, without requiring any modification of the setup, as much as and if possible.
Do you use this `--add-modules` setting anyway, regardless of the agent, which is why you didn't see what I [did](https://github.com/elastic/apm-agent-java/issues/2563#issuecomment-1084680031)?
If you don't apply these settings, would you get the same error I saw?

> I fixed the issue, now this error is gone, eapm jar getting initialised successfully and sending the data to elastic apm, and the good part that i've managed to fix it without having to change the Temurin. 🙂
>
> Solution: Add jdk.zipfs module to your java runtime environment.

This is awesome! So it is related to module visibility after all.
If possible, please share your entire command line and module setup, as well as a detailed description of how you resolved the issue, so we can document this for the benefit of other users. 

I will close this issue through a PR that adds a useful troubleshooting guidance once I get this info.

Thanks a lot for your terrific feedback!

**Comment by eyalkoren** [comment] 2022-04-05 12:49
I missed something important in your comment before - this is not a general module visibility issue, it is very specific to your setup, which builds its Java runtime using `jlink`.
Therefore, there is very little we can say about it in our troubleshooting page, but I'll add something. 
Thanks!

**Comment by sunilnagavelli** [comment] 2022-04-05 18:38
>This is awesome! So it is related to module visibility after all.
If possible, please share your entire command line and module setup, as well as a detailed description of how you resolved the issue, so we can document this for the benefit of other users.
I will close this issue through a PR that adds a useful troubleshooting guidance once I get this info.
Thanks a lot for your terrific feedback!

Yes @eyalkoren , For me 2 things made this fix possible, one Updating the elastic APM Jar from 1.28.4 and adding this JDK module.

> I missed something important in your comment before - this is not a general module visibility issue, it is very specific to your setup, which builds its Java runtime using `jlink`. Therefore, there is very little we can say about it in our troubleshooting page, but I'll add something. Thanks!

Sure, however people might come across this scenario so it is worth mentioning this module to save some time for them.

Here is the JRE env that we have setup
```
$JAVA_HOME/bin/jlink \
         --add-modules java.compiler,java.base,java.logging,java.security.jgss,java.security.sasl,java.sql,java.desktop,java.rmi,jdk.crypto.ec,jdk.charsets,jdk.zipfs \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime
```

Thank you for swift responses, it was great collaborating with you @eyalkoren :)

**Comment by eyalkoren** [comment] 2022-04-06 05:43
> Sure, however people might come across this scenario so it is worth mentioning this module to save some time for them.

Added to troubleshooting page - #2573

**Closed** 2022-04-06 05:42 UTC
Labels: agent-java, community, triage
