### ISSUE TITLE
AEM application - traces not showing/capturing outgoing HTTP requests

### ISSUE THREAD

**Issue by SanjuTechie87** [elastic/apm-agent-java#2104] opened 2021-09-04 06:40 UTC
**Issue Description**

We have currently setup the java apm-agent ( as command argument in JAVA_OPTS) for one of the AEM publisher application. We are able to see #Dispatcherservlet#doGet #Dispatcherservlet#doPost transaction in APM app in Kibana . But we are not able to see any further traces where it has made an outgoing HTTP call to external service .

**Information**
FYI, There is another apm - app dynamics is also installed in the machine and it is capturing all the traces. There are other tomcat servers where we have also configured apm-agent and we are able to see all the outgoing requests

**Version used**
java apm-agent version : 1.25.0
elasticsearch version : 7.14.0
kibana version: 7.14.0
apm-server version : 7.14.0

**Few things we have tried so far**

> Adding properties such as -Delastic.apm.disable_instrumentations=none -Dtrace_methods=* -Delastic.apm.profiling_inferred_spans_enabled=true
> Enabling Trace -Delastic.apm.log_level=TRACE ( not able to see any trace )
> Added sling.bootdelegation.co.elastic.apm=co.elastic.apm.* in sling.properties

Kindly help me by informing what configuration needs to be change to get all the traces. We are planning to replace app-dynamics with elastic-apm but this issue is really blocking us. Please help.

**Error stack trace** - Disclaimer can't give full due to security concern 

**java.lang.NoClassDefFoundError: javax/servlet/http/HttpServlet
        at co.elastic.apm.agent.servlet.ServletApiAdvice.onExitServletService(ServletApiAdvice.java:214)**
        at com.adobe.granite.rest.assets.impl.AssetContentDispositionFilter.doFilter(AssetContentDispositionFilter.java:97)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:72)

**Comment by SylvainJuge** [comment] 2021-09-06 07:52
Hi @SanjuTechie87 ,

I closed #2105 as duplicate of this issue, also you opened [this conversation](https://discuss.elastic.co/t/aem-trace-not-showing-outgoing-http-requests-java-apm-agent/283182) on our forum. We understand this might be an issue for you, but duplicating does not really help as the whole team gets notifications for each of those. As there is slightly more details in this one, I suggest we continue here and try to keep focus.

Few things that come to mind here:
- what Apache Sling version are you using ?
- do you know what is the underlying technology for Apache Sling to 1) handle incoming HTTP requests (seems Servlet from naming), and 2) to execute downstream HTTP client calls (which you seem to be missing here).
- does this behavior is the same without the AppDynamics agent ? Mixing agents is often source of unpredictable behaviors.
- do you have an example of what is being properly monitored with AppDynamics that is missing here for the outgoing HTTP calls ? For example, it might provide few hints to know which HTTP client is being used.

----

To move this forward, I suggest to do the following (in that order): 
- reset to the default minimal configuration for the Elastic APM agent (remove the `disable_instrumentations` `trace_methods` and `profiling_inferred_spans_enabled`).
- disable the AppDynamics agent (or remove it completely)
- configure the Elastic agent with `log_level=debug`
- truncate application/agent log file(s) and restart the application
- provide us the agent and/or application log file, you will probably have to rename any sensitive information there.

With `log_level=debug` the agent should output the configuration at the start of the log output, thus even if you can't share it here, you might be able to check that the configuration that you provided is effective or not.
You should be able to provide us this part of the log where this is printed without privacy issues.

Also, if the `NoClassDefFoundError` still happens, you should be able to share the full stack trace of the exception by removing any internal class names from the stack.

----

If removing the AppDynamics agent does not change the observed behavior, then it's probably related to OSGi, thus you can try the following:

Apache Sling seems to rely on OSGi, hence setting `org.osgi.framework.bootdelegation` might be required, thus in `sling.properties` :
- remove the `sling.bootdelegation.co.elastic.apm=co.elastic.apm.*` entry
- add `org.osgi.framework.bootdelegation=co.elastic.apm.*` (or append to any existing value).

Disclamer: I have never used Apache Sling nor AEM thus I can't try this myself.

**Comment by SanjuTechie87** [comment] 2021-09-08 14:46
@SylvainJuge  Thanks very much for your time and reply.

We are in process of debugging the issue. Have followed what you said - kept the default config and changed the log level to debug, removed Appd . 

The below is an extract from the debug log. We will provide more details shortly .

2021-09-08 15:23:08,484 [main] DEBUG co.elastic.apm.agent.util.DependencyInjectingServiceLoader - unable to instantiate 'co.elastic.apm.agent.httpclient.HttpClientInstrumentation', unsupported class version error: co/elastic/apm/agent/httpclient/HttpClientInstrumentation has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2021-09-08 15:23:08,485 [main] DEBUG co.elastic.apm.agent.util.DependencyInjectingServiceLoader - unable to instantiate 'co.elastic.apm.agent.httpclient.HttpClientAsyncInstrumentation', unsupported class version error: co/elastic/apm/agent/httpclient/HttpClientAsyncInstrumentation has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2021-09-08 15:23:08,485 [main] DEBUG co.elastic.apm.agent.util.DependencyInjectingServiceLoader - unable to instantiate 'co.elastic.apm.agent.httpclient.HttpRequestHeadersInstrumentation', unsupported class version error: co/elastic/apm/agent/httpclient/HttpRequestHeadersInstrumentation has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by SylvainJuge** [comment] 2021-09-09 09:09
Hi @SanjuTechie87 ,

Those debug messages are completely normal, expected and have no impact on your application.

It just indicates that some instrumentation plugins have been compiled for a more recent JDK that the JVM that is currently running the application and thus those plugins can't be loaded. In this particular case the plugin instruments the HTTP client that is shipped with Java 9.

**Comment by eyalkoren** [comment] 2021-09-12 07:53
Closing due to duplication with the corresponding [forum topic](https://discuss.elastic.co/t/aem-trace-not-showing-outgoing-http-requests-java-apm-agent/283182).
In the future, please avoid such duplications, asking in the forum is sufficient as first step for analysis.

**Comment by eyalkoren** [comment] 2021-09-13 07:57
Since agent version 1.18.0, no specific OSGi configurations should be required. 
Please try to remove all and any OSGi configuration you added especially for the Elastic agent and retry.
If you still get a `NoClassDefFoundError`, please share as much as possible from the related stack trace. If you can clear sensitive info from a full debug log and share it, the chances of quickly identifying the root cause will increase.

We can also wait until #2109 is merged and released. With this change, agent class loading is going to work entirely differently, but this is not only a snapshot you can test, it relies on different artifacts.

**Comment by SylvainJuge** [comment] 2021-09-20 11:58
The PR #2109 has been merged, and thus will be included in the next release, likely `1.27.0`, make sure to subscribe to project release notifications.

**Comment by eyalkoren** [comment] 2021-11-17 15:59
Closing as 1.27.0 has been released and we assume this issue won't be relevant with this version.
Feel free to reopen if needed.

**Comment by bryantcj52** [comment] 2021-12-21 20:27
We're seeing this in AEM/sling with elastic-apm-agent 1.28.1:

```
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServlet
	at co.elastic.apm.agent.servlet.JavaxServletApiAdvice.isInstanceOfHttpServlet(JavaxServletApiAdvice.java:214)
	at co.elastic.apm.agent.servlet.ServletApiAdvice.onExitServlet(ServletApiAdvice.java:189)
	at co.elastic.apm.agent.servlet.JavaxServletApiAdvice.onExitServletService(JavaxServletApiAdvice.java:65)
```

and

```
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
        at co.elastic.apm.agent.servlet.JavaxServletApiAdvice.isHttpServletRequest(JavaxServletApiAdvice.java:70)
        at co.elastic.apm.agent.servlet.JavaxServletApiAdvice.isHttpServletRequest(JavaxServletApiAdvice.java:43)
        at co.elastic.apm.agent.servlet.ServletApiAdvice.onServletEnter(ServletApiAdvice.java:77)
        at co.elastic.apm.agent.servlet.JavaxServletApiAdvice.onEnterServletService(JavaxServletApiAdvice.java:55)
```

We had the `org.osgi.framework.bootdelegation=co.elastic.apm.*` set before, removing it didn't help.

**Comment by SylvainJuge** [comment] 2022-01-06 08:20
Hi @bryantcj52 ,

AEM is not a product that is publicly available and that would be quite challenging to try reproducing your own setup.
As it's based on Apache Sling, could you tell us if that problem also happens with plain Apache Sling server also ? If so, that means the issue is more with Sling than AEM, which would be far easier to diagnose and provide a fix.

**Comment by SylvainJuge** [comment] 2022-01-26 15:41
Hi @bryantcj52, since debugging this issue might be tricky I've decided to provide a debug version of the agent that should provide more information when this exception is thrown.

Could you try to use [this snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-2418/6/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.28.5-SNAPSHOT.jar) and provide the agent logs for investigation ?

Alternatively, if you have a way to provide a trial version of AEM (Virtual machine image, docker image, simple zip) that helps to reproduce the issue, that would also be a convenient way to make progress here.

**Comment by bryantcj52** [comment] 2022-01-28 17:30
Attached are the logs from the snapshot version.
[apm-2104.zip](https://github.com/elastic/apm-agent-java/files/7960658/apm-2104.zip)

**Comment by SylvainJuge** [comment] 2022-01-31 14:12
Thanks for testing with the snapshot, it confirms one of the hypothesis we had around this:


```
JavaxServletApiAdvice - context classloader : jdk.internal.loader.ClassLoaders$AppClassLoader@3d4eac69
JavaxServletApiAdvice - classloader 'jdk.internal.loader.ClassLoaders$AppClassLoader@3d4eac69' can not access class 'javax.servlet.http.HttpServletRequest'
JavaxServletApiAdvice - classloader of class 'co.elastic.apm.agent.servlet.JavaxServletApiAdvice', IndyPluginClassLoader{targetClassLoader=com.adobe.cq.cq-history [358], agentClassLoader=co.elastic.apm.agent.premain.ShadedClassLoader@46f7f36a}
JavaxServletApiAdvice - classloader 'IndyPluginClassLoader{targetClassLoader=com.adobe.cq.cq-history [358], agentClassLoader=co.elastic.apm.agent.premain.ShadedClassLoader@46f7f36a}' can not access class 'javax.servlet.http.HttpServletRequest'
JavaxServletApiAdvice - classloader of class 'com.adobe.cq.history.impl.HistoryRequestFilter', com.adobe.cq.cq-history [358]
JavaxServletApiAdvice - classloader 'com.adobe.cq.cq-history [358]' can not access class 'javax.servlet.http.HttpServletRequest'

```

No classloader (either the context CL or the one from the instrumented class) seems to be able to load `javax.servlet.http.HttpServletRequest`.

Our agent assumes that the class being instrumented, here `com.adobe.cq.history.impl.HistoryRequestFilter` implements a Servlet Filter, and as a result is always able to load parts of the Servlet API through its own classloader. The agent instrumentation just tries to reuse this classloader to load other parts of the Servlet API which is expected to be there and available.

I am really not sure how this could happen, maybe one of the OSGi or AEM classloaders allow to load classes within a specific time frame and prevents doing the same after the application is properly started. As a result I don't know yet how we could move this investigation forward and find a proper way to fix it.

**Comment by bryantcj52** [comment] 2022-01-31 15:33
@SylvainJuge  I should note that the last agent version we had running and working was 1.22.0.

I will see if I can test anything around the osgi class loader.

**Comment by bryantcj52** [comment] 2022-01-31 16:21
@SylvainJuge  This does seem to be a common issue with ByteBuddy and multi-level class loaders:

https://stackoverflow.com/questions/60237664/classpath-problems-while-instrumenting-springboot-application
https://github.com/raphw/byte-buddy/issues/473

**Comment by SylvainJuge** [comment] 2022-02-01 08:52
The issue here is a bit different from the ones described in those issues, but it has similar symptoms.

With our agent, the advice classes (whose code is injected when doing instrumentation) are loaded in a classloader that is a child of the instrumented class classloader, hence advices should _in theory_ have the same visibility as the instrumented class.

To get back to your case, a class that implements a Servlet Filter is loaded in a classloader that can access the Servlet API classes, either because it's loaded in the same CL or because it has visibility and can delegate to another CL that can load it.

With OSGi (and AEM) each bundle is loaded in a separate CL, so the Servlet API and the class that implements a Servlet Filter are loaded in two distinct classloaders. At some point in time the one with the Servlet Filter must be able to resolve its dependencies on Servlet API to enable loading it, however when instrumented code is being executed later at runtime (when the instrumented code is being executed) this resolution does not seem available anymore. As a result any class that hasn't been made "visible" in the Servlet Filter classloader can't be resolved later at runtime unlike with regular Java applications.

**Comment by SylvainJuge** [comment] 2022-02-01 09:21
In order to validate this hypothesis, there could be two things to check:

-------
Trying to create another `Servlet` filter that directly refers to `javax.servlet.http.HttpServletRequest` when loaded, for example through a `static` block like this:
```
static {
    Object o = Object.class;
    if(o instanceof javax.servlet.http.HttpServletRequest){
        System.out.println("hello");
    }
}
```
If loading such Servlet Filter works, then it means that direct references to the `HttpServletRequest` are possible when resolved while the class is being loaded. This might require some work to properly package it as an OSGi module.

-------
Open the jar file that contains the module where `com.adobe.cq.history.impl.HistoryRequestFilter`, and look at the `META-INF/MANIFEST.MF` file, I'm pretty sure that the OSGi import statement (which defines which packages are required for this bundle) only imports the `javax.servlet` package and does not imports the `javax.servlet.http` package because the classes in the bundle don't require it. From what I understand OSGi relies on package names and sub-packages are not automatically included implicitly. If this is confirmed, then modifying the Jar file manifest to also import `javax.servlet.http` could allow to work-around this issue.

**Comment by SylvainJuge** [comment] 2022-02-02 08:53
Thanks for the update, at least it confirms that the visibility is defined on a per-package level.

So, in the case of this Servlet Filter, if we could make our agent only rely on `javax.servlet` package and dealing gracefully with the optional presence of `javax.servlet.http` that should work. However, I'm not sure it's possible and it would definitely complicate maintenance. Also, applying this strategy on all 50+ instrumentation plugins is not doable.

I agree with you, modifying all the bundles is definitely not a viable option, ideally we need to have something automatic here.
I wonder if we could maybe instrument the OSGi runtime itself in order to automatically add those "missing" imports to make the agent behave as expected.

**Comment by SylvainJuge** [comment] 2022-02-09 09:14
Hi @bryantcj52 , providing a generic fix for this would likely take some time, however if it's only impacting a few OSGi bundles related to server and not generally happening with every class that the agent instruments there might be a way to simply ignore those bundles when doing instrumentation.

So, for example here we know that there is an AEM plugin that is packaged as an OSGi bundle which relies on part of the Servlet API. If the agent would simply ignore this bundle, it might still be able to capture the transaction as other Servlet/Filter implementations will allow to capture the HTTP request.

Ideally, in order to know if we could apply this strategy for Servlets (and maybe others) we would need to have a list of all the classes that appear to be missing, which could be computed from the logs using a bash shell one-liner similar to the one below:
```
cat <your-log-file-with-all-exceptions> | grep 'Caused by: java.lang.ClassNotFoundException:' | sed 's/.*Caused by: java.lang.ClassNotFoundException: //' | sort -u
```

**Comment by SylvainJuge** [comment] 2022-02-21 09:06
Hi @bryantcj52 ,

I don't think that ignoring *all* classes in `com.adobe.*` will be the right solution here as we still need to instrument a few of them.

Could you try to configure the [`classes_excluded_from_instrumentation`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-classes-excluded-from-instrumentation) with only the classes that trigger this issue ? Doing this through configuration is the best option so far as the agent can't automatically detect such issues at runtime.

**Comment by bryantcj52** [comment] 2022-02-21 16:14
@SylvainJuge  Looks like the exclude config works.

**Comment by SylvainJuge** [comment] 2022-02-22 08:38
That's good news, at least you now have a workaround.

It seems that there is only a very small subset of classes that are impacted, and all of them seem to be implementation of Servlet filters by guessing from their name:
- `HistoryRequestFilter`
- `AssetContentDispositionFilter`
- `ResourceResolverHolderFilter`
Do you have a way to verify this assumption ? Maybe by opening the OSGi bundles and by looking at their descriptors in `META-INF/MANIFEST.MF` that should contain only `javax.servlet` and not `javax.servlet.http` packages.

If it is only happening in this case, we can make the whole Servlet API instrumentation ignore automatically classes that are loaded in a classloader that does not provide access to classes in `javax.servlet.http`, this would work like with the configuration you tried but automatically. While this would not prevent it from happening with other OSGi bundles it would allow to properly close this issue until another occurrence is found.

**Comment by SylvainJuge** [comment] 2022-02-24 15:15
Hi @bryantcj52, I've added a filter in our Servlet plugin to take care of this automatically in #2418 

Could you try [this snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-2418/20/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.29.1-SNAPSHOT.jar) and remove the [`classes_excluded_from_instrumentation`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-classes-excluded-from-instrumentation) configuration that was added previously ?
If the test is positive and the initial error is gone, it means that we could easily ship this workaround in the next agent release.

**Comment by bryantcj52** [comment] 2022-02-25 17:44
@SylvainJuge  Getting a ton of `SecurityExceptions` with that snapshot:

```
java.lang.SecurityException
        at org.apache.sling.engine.impl.helper.SlingServletContext.getClassLoader(SlingServletContext.java:533)
        at co.elastic.apm.agent.servlet.adapter.JavaxServletApiAdapter.getClassLoader(JavaxServletApiAdapter.java:105)
        at co.elastic.apm.agent.servlet.adapter.JavaxServletApiAdapter.getClassLoader(JavaxServletApiAdapter.java:42)
        at co.elastic.apm.agent.servlet.ServletServiceNameHelper.determineServiceName(ServletServiceNameHelper.java:49)
        at co.elastic.apm.agent.servlet.servicename.InitServiceNameInstrumentation$JavaxInitServiceNameInstrumentation$AdviceClass.onEnter(InitServiceNameInstrumentation.java:104)
        at org.apache.sling.distribution.servlet.DistributionAgentCreationFilter.init(DistributionAgentCreationFilter.java:81)
        at org.apache.sling.engine.impl.filter.ServletFilterManager.initFilter(ServletFilterManager.java:195)
        at org.apache.sling.engine.impl.filter.ServletFilterManager.addingService(ServletFilterManager.java:130)
        at org.apache.sling.engine.impl.filter.ServletFilterManager.addingService(ServletFilterManager.java:43)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
        at org.apache.sling.engine.impl.SlingMainServlet$1.run(SlingMainServlet.java:486)
java.lang.SecurityException
        at org.apache.sling.engine.impl.helper.SlingServletContext.getClassLoader(SlingServletContext.java:533)
        at co.elastic.apm.agent.servlet.adapter.JavaxServletApiAdapter.getClassLoader(JavaxServletApiAdapter.java:105)
        at co.elastic.apm.agent.servlet.adapter.JavaxServletApiAdapter.getClassLoader(JavaxServletApiAdapter.java:42)
        at co.elastic.apm.agent.servlet.ServletServiceNameHelper.determineServiceName(ServletServiceNameHelper.java:49)
        at co.elastic.apm.agent.servlet.servicename.InitServiceNameInstrumentation$JavaxInitServiceNameInstrumentation$AdviceClass.onEnter(InitServiceNameInstrumentation.java:104)
        at com.day.cq.wcm.core.impl.WCMRequestFilter.init(WCMRequestFilter.java:78)
        at org.apache.sling.engine.impl.filter.ServletFilterManager.initFilter(ServletFilterManager.java:195)
        at org.apache.sling.engine.impl.filter.ServletFilterManager.addingService(ServletFilterManager.java:130)
        at org.apache.sling.engine.impl.filter.ServletFilterManager.addingService(ServletFilterManager.java:43)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
        at org.apache.sling.engine.impl.SlingMainServlet$1.run(SlingMainServlet.java:486)
java.lang.SecurityException
        at org.apache.sling.engine.impl.helper.SlingServletContext.getClassLoader(SlingServletContext.java:533)
        at co.elastic.apm.agent.servlet.adapter.JavaxServletApiAdapter.getClassLoader(JavaxServletApiAdapter.java:105)
        at co.elastic.apm.agent.servlet.adapter.JavaxServletApiAdapter.getClassLoader(JavaxServletApiAdapter.java:42)
        at co.elastic.apm.agent.servlet.ServletServiceNameHelper.determineServiceName(ServletServiceNameHelper.java:49)
        at co.elastic.apm.agent.servlet.servicename.InitServiceNameInstrumentation$JavaxInitServiceNameInstrumentation$AdviceClass.onEnter(InitServiceNameInstrumentation.java:104)
        at com.adobe.cq.social.commons.cors.CORSAuthenticationFilter.init(CORSAuthenticationFilter.java:67)
        at org.apache.sling.engine.impl.filter.ServletFilterManager.initFilter(ServletFilterManager.java:195)
        at org.apache.sling.engine.impl.filter.ServletFilterManager.addingService(ServletFilterManager.java:130)
        at org.apache.sling.engine.impl.filter.ServletFilterManager.addingService(ServletFilterManager.java:43)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
        at org.apache.sling.engine.impl.SlingMainServlet$1.run(SlingMainServlet.java:486)
java.lang.SecurityException
	at org.apache.sling.engine.impl.helper.SlingServletContext.getClassLoader(SlingServletContext.java:533)
	at co.elastic.apm.agent.servlet.adapter.JavaxServletApiAdapter.getClassLoader(JavaxServletApiAdapter.java:105)
	at co.elastic.apm.agent.servlet.adapter.JavaxServletApiAdapter.getClassLoader(JavaxServletApiAdapter.java:42)
	at co.elastic.apm.agent.servlet.ServletServiceNameHelper.determineServiceName(ServletServiceNameHelper.java:49)
	at co.elastic.apm.agent.servlet.servicename.InitServiceNameInstrumentation$JavaxInitServiceNameInstrumentation$AdviceClass.onEnter(InitServiceNameInstrumentation.java:104)
	at javax.servlet.GenericServlet.init(GenericServlet.java:157)
	at org.apache.sling.servlets.resolver.internal.resource.ServletMounter.createServlet(ServletMounter.java:194)
	at org.apache.sling.servlets.resolver.internal.resource.ServletMounter.createAllServlets(ServletMounter.java:176)
	at org.apache.sling.servlets.resolver.internal.resource.ServletMounter.activate(ServletMounter.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:340)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:982)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:338)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:382)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:264)
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:420)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4817)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2336)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by SylvainJuge** [comment] 2022-03-14 10:56
Hi @bryantcj52 , sorry for not replying you earlier.

It seems that your application is relying on a security manager, thus you have to modify the application policy to make sure that the agent is granted the proper rights. The policy file is usually provided in the JVM command line arguments and adding a similar configuration to it will allow the agent.

```
grant codeBase "file:/apm/elastic-apm-agent.jar" {
    permission java.security.AllPermission;
};
```

Could you try modifying the policy file and tell us if that works as expected ?
It seems to me that we should already be able to merge #2418 as the related error seems to be fixed and this one is another issue in your environment completely unrelated to OSGi.

**Comment by bryantcj52** [comment] 2022-03-14 15:51
@SylvainJuge 

As far as I can tell, sling/aem doesn't use a security manager or any security policy files.

I'm able to get the same errors with base sling using the sling start app here: https://sling.apache.org/downloads.cgi#sling-application

**Comment by SylvainJuge** [comment] 2022-03-16 14:29
Thanks @bryantcj52 , this was really easy to reproduce

This `SecurityException` is triggered because Sling implementation explicitly prevent direct access to the classloader.

https://github.com/apache/sling-org-apache-sling-engine/blob/master/src/main/java/org/apache/sling/engine/impl/helper/SlingServletContext.java#L531-L537

This is not related to OSGi, but the easiest fix here is to ignore this known corner-case, I will update the PR with such a work-around.

**Comment by SylvainJuge** [comment] 2022-03-16 15:15
@bryantcj52 just to make sure that the latest work-around works as expected in your case, could you try with this [snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-2418/35/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.29.1-SNAPSHOT.jar) and  all the issues are now gone :crossed_fingers: ?

**Closed** 2022-03-17 09:51 UTC
Labels: bug, agent-java, community, 8.3-candidate
