### ISSUE TITLE
Add an option to set http.request.body.original size limit

### ISSUE THREAD

**Issue by ea1987** [elastic/apm-agent-java#828] opened 2019-09-03 08:32 UTC
**Is your feature request related to a problem? Please describe.**
Currently http.request.body.original size is limited/truncated to 10k characters. Since I'm using APM to storage payloads with a bigger size I would like setting size to be allowed to user configuration.

**Describe the solution you'd like**
An implementation of a specific property. Ex: elastic.apm.capture_body.size
Of course, setting shouldn't be to an infinite value but at least to a bigger size.

**Comment by axw** [comment] 2019-09-03 08:46
@ea1987 thanks for opening the issue. This looks like a duplicate of #456, so I'll close this one.

If you can provide any additional information about your motivation for opening this (e.g. why you want to capture the body, what you intend to do with it if it's > 10K characters, ...), please leave a comment on #456. Otherwise, I'd recommend subscribing to the issue to be informed of any updates.

**Closed by axw** 2019-09-03 08:46 UTC
