### ISSUE TITLE
JMS message beans doesn't contain elastic apm logging

### ISSUE THREAD

**Issue by marinkton** [elastic/apm-agent-java#3192] opened 2023-06-16 13:20 UTC
We upgraded our Spring Boot and Openliberty services to Java 17 and Spring Boot 3. What we've noticed is that the message beans for openliberty and spring boot (JMS) are not instrumenting the elasticsearch properties into the the logging. The rest-api's are logging correctly the elastic properties. We've also tried to print the trace id in our application by ourself with "ElasticApm.currentTransaction().getTraceId()". This is giving us an empty value. 

So are we missing something in the configuration, because of the upgrade? We need the transaction and trace id in the logging. 

The version we use is 1.39.0.

Our properties:
`elastic.apm:
  environment: dev
  service-name: apm-test-logging
  server-url: https://test:8200
  verify-server-cert: false
  enable-log-correlation: true
  log-format-sout: json
  application-packages: nl.test
  central_config: false`

**Comment by jackshirazi** [comment] 2023-06-19 12:34
Can you try with version 1.35.0 to rule out or in some optimization that were added to the agent around messaging

**Comment by marinkton** [comment] 2023-06-19 13:21
@jackshirazi I tried it and unfortunately it doesn't work. We're using as I said Spring Boot 3 and Open Liberty Services with Java 17. I see Spring Boot 3 support is added from version 1.38.0.

**Comment by jackshirazi** [comment] 2023-06-19 14:59
I can't immediately see what's missing, it would be helpful if you have a minimal example I could run that shows the issue. Meanwhile I'll try to reproduce

**Comment by jackshirazi** [comment] 2023-06-19 16:42
(obviously I need to extend to using messaging, but that's where you could help with a simple example)

**Comment by marinkton** [comment] 2023-06-19 18:07
@jackshirazi Thanks, I appreciate your effort. As I said in my question, the controllers (rest api's) are instrumenting correctly the elastic properties in our Spring Boot and Open Liberty apps. The problem only occurs in the messaging beans for both.

**Comment by JonasKunz** [comment] 2023-06-20 08:03
Maybe this is not related to spring at all but rather to `jakarta.*` vs `jmx.*` JMS namespaces?
Looking at this [issue](https://github.com/elastic/apm-agent-java/issues/3192), it seems like we don't support JMS in the `jakarta.*` namespace yet.

**Comment by jackshirazi** [comment] 2023-06-20 10:21
I think the supported tech entry may be incorrect, we did a push on the jakarta namespaces but I think we've not finished the JMS part, and it seems yours is the first bug report identifying that. I'll look at whether we can get you a snapshot to test

**Comment by marinkton** [comment] 2023-06-20 21:28
@jackshirazi perfect thanks, any idea when jakarta.jms namespace will be supported?

**Comment by jackshirazi** [comment] 2023-06-20 22:38
The next version in a couple of weeks if this is what is causing your issue. Please try the [snapshot build](https://github.com/elastic/apm-agent-java/actions/runs/5327426295?pr=3198#artifacts) (the agent snapshot jar is in the elastic-apm-agent zip file, or the -java8 one if you are using that)

**Comment by marinkton** [comment] 2023-06-23 11:10
@jackshirazi thanks for the snapshot. I tried to include it in my project, but it seems like that the attach package is missing. I can't import co.elastic.apm.attach.ElasticApmAttacher. I've looked inside the jar and i've noticed that the attach package is missing. 

This is how I added the snapshot build to my project. 
        <dependency>
            <groupId>co.elastic.apm</groupId>
            <artifactId>apm-agent-attach</artifactId>
            <version>1.39.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/resources/elastic-apm-agent-1.39.1-SNAPSHOT.jar</systemPath>
        </dependency>

**Comment by jackshirazi** [comment] 2023-06-23 11:49
For testing could you use the javaagent option on the command line? Only the `elastic-apm-agent-1.39.0.jar` jar needs replacing with `elastic-apm-agent-1.39.1-SNAPSHOT.jar` in that case

**Comment by SylvainJuge** [comment] 2023-06-26 08:05
Hi @marinkton , for clarification you are using the `apm-agent-attach` artifact in your application, and the link @jackshirazi provided was for the `elastic-apm-agent` artifact, the latter must be used with the `-javaagent` option.

So here you should either:
- download the large "build" [archive](https://github.com/elastic/apm-agent-java/suites/13743999198/artifacts/760909394) from our CI and extract the `apm-agent-attach-1.39.1-SNAPSHOT.jar` from it and replace the `<systemPath>` value with this file path.
- use the `-javaagent` setup option with the `elastic-apm-agent-1.39.1-SNAPSHOT.jar` downloaded previously

**Comment by marinkton** [comment] 2023-06-26 10:46
@SylvainJuge @jackshirazi unfortunately the snapshot does not work. I've used the --javaagent setup.

The startup logs :
The logs are showing that I'm using your snapshot version correctly:

`
{"@timestamp":"2023-06-26T10:25:01.209Z","log.level": "WARN","message":"This is a pre-release snapshot version, usage in production is not recommended unless instructed otherwise.", "ecs.version": "1.2.0","event.dataset":"apm-logging.apm-agent","process.thread.name":"main","log.logger":"co.elastic.apm.agent.configuration.StartupInfo"}
{"@timestamp":"2023-06-26T10:25:01.209Z","log.level": "INFO","message":"Starting Elastic APM 1.39.1-SNAPSHOT.6d79d01 as apm-logging on Java 17.0.7 Runtime version: 17.0.7+7 VM version: openj9-0.38.0 (IBM Corporation) Linux 4.18.0-372.32.1.el8_6.x86_64", "ecs.version": "1.2.0","event.dataset":"apm-logging.apm-agent","process.thread.name":"main","log.logger":"co.elastic.apm.agent.configuration.StartupInfo"}
`

But the elastic props are still empty in the messaging beans (I've used a open liberty service to test this).

`
{"message":"Bericht is succesvol geplaatst op logging-acties","ibm_datetime":"2023-06-26T12:26:44.276+0200","log.logger":"nl.justid.dad.utilities.jms.DADActiveMQDestination","log.level":"INFO","log.origin.function":"enqueue","ibm_className":"nl.test.jms.DADActiveMQDestination","transaction.id":"","trace.id":"","@timestamp":"2023-06-26T10:26:44.277546591Z","ext_appName":"logging-service","span.id":"","process.thread.name":"Thread-1 (ActiveMQ-client-global-threads)"}
`

**Comment by SylvainJuge** [comment] 2023-06-26 11:18
In this case if you could provide a very simple app that helps to reproduce the problem that would really be helpful.

From what I understand:
- the transactions are properly created on the HTTP endpoint.
- you have some "messaging beans" that should be triggered when they handle a message from JMS.

What we need to know:
- does your application sends messages to JMS from the HTTP request handling or does the application also handles incoming messages through JMS ?
- how are those JSON logs created? are you using `ecs-logging-java` or the agent built-in [reformatting](https://www.elastic.co/guide/en/apm/agent/java/current/logs.html#log-reformatting) feature ? The weird thing here is that we have empty valies for `transaction.id` and `trace.id` and I'm pretty sure the java agent does not set such empty values.

**Comment by marinkton** [comment] 2023-06-26 12:12
@SylvainJuge the application handles incoming messages through JMS. We have multiple services in Open liberty and Spring Boot. Everything was working fine before the Java 17 and Jakarta namespace upgrade.

For spring boot we're using the dependency:

`
		<dependency>
			<groupId>co.elastic.logging</groupId>
			<artifactId>log4j2-ecs-layout</artifactId>
			<version>${co.elastic.logging.log4j2-ecs-layout-version}</version>
		</dependency>
`

and for open liberty we have a custom method for setting up the logging:

`   
 protected void setupLogging() {

        LogRecordContext.unregisterExtension(TIMESTAMP);
        LogRecordContext.unregisterExtension(TRACE_ID);
        LogRecordContext.unregisterExtension(TRANSACTION_ID);
        LogRecordContext.unregisterExtension(SPAN_ID);

        LogRecordContext.registerExtension(TIMESTAMP, () -> ZonedDateTime.now(ZoneOffset.UTC).format(DateTimeFormatter.ISO_INSTANT));
        LogRecordContext.registerExtension(TRACE_ID, () -> ElasticApm.currentTransaction().getTraceId());
        LogRecordContext.registerExtension(TRANSACTION_ID, () -> ElasticApm.currentTransaction().getId());
        LogRecordContext.registerExtension(SPAN_ID, () -> ElasticApm.currentSpan().getId());

        initialized = true;
    }
`

The transactions are properly created on the HTTP endpoint indeed, but the messagings beans are not created properly. 
This problem occurs in both frameworks (Spring and Open Liberty).


I'll try to provide an example today or tomorrow.

**Comment by SylvainJuge** [comment] 2023-06-27 08:50
Thanks ! That explains the empty `transaction_id` fields in the JSON logs.
We don't provide a dedicated instrumentation for OpenLiberty, but the `setupLogging` does an equivalent job here when the logs as written in JSON.

**Comment by LeaTaka** [comment] 2023-06-27 20:27
Hi there, same problem here. 
I would like to contribute with my experience on the issue 👇

Tested;
-	ecs-console-appender in logback.spring.xml*
-	ELASTIC_APM_LOG_ECS_REFORMATTING enabled instead of logback.spring.xml*
-	apm-agent version 1.36, 1.38 and 1.39
-	Receiving a message from ibm MQ server with the DefaultJmsListenerContainerFactory

Results:
-	No correlation id’s are injected jms listener related logback logging
-	Correlation id’s are injected for normal api requests

*Please find attached the example project I used for testing. Also have a look at the example folder for the used configurations in the attached [jms-logcorrelation-example-project.zip](https://github.com/elastic/apm-agent-java/files/11886909/jms-logcorrelation-example-project.zip)

**Comment by SylvainJuge** [comment] 2023-06-29 08:39
Hi @LeaTaka and @marinkton , we have fixed a few issues in the PR that adds support for Jakarta namespace.

Could you try with [this snapshot](https://github.com/elastic/apm-agent-java/suites/13930361198/artifacts/775625437) of the Java agent and see if that now works as expected ?

Thanks to the sample application provided by @LeaTaka I've managed to reproduce the issues locally which really helped a lot.
There are still few test failures to investigate in the PR, but that's only due to unit-testing.

**Comment by LeaTaka** [comment] 2023-06-29 10:03
### First results testing with your snapshot;

1. using @JmsListener ✅
2. requested a normal rest api ✅
3. checking log-correlation in Kibana ✅

### App-3 logging >>
`{"@timestamp":"2023-06-29T09:43:02.004Z","log.level": "INFO","message":"Received message is: \n  JMSMessage class: jms_text\n  JMSType:          null\n  JMSDeliveryMode:  2\n  JMSDeliveryDelay: 0\n  JMSDeliveryTime:  0\n  JMSExpiration:    0\n  JMSPriority:      4\n  JMSMessageID:     ID:414d51204d514d534f30352020202020645e84ef21a79402\n  JMSTimestamp:     1688031781981\n  JMSCorrelationID: null\n  JMSDestination:   queue:///DEV.SDS.02.LQ02\n  JMSReplyTo:       null\n  JMSRedelivered:   false\n    JMSXAppID: /app/apm-java.jar           \n    JMSXDeliveryCount: 1\n    JMSXUserID: mqsrtp01    \n    JMS_IBM_Character_Set: UTF-8\n    JMS_IBM_Encoding: 273\n    JMS_IBM_Format: MQSTR   \n    JMS_IBM_MsgType: 8\n    JMS_IBM_PutApplType: 28\n    JMS_IBM_PutDate: 20230629\n    JMS_IBM_PutTime: 09430199\n    elastic_apm_traceparent: 00-1b751e269027419c5d29d1f34a4bb110-94ad8ee90009fc92-01\n    traceparent: 00-1b751e269027419c5d29d1f34a4bb110-94ad8ee90009fc92-01\n    tracestate: es=s:1\nListener - Message from App2: f673bbe2-67dd-4d54-a516-c059c91ee8a6","ecs.version": "1.2.0","service.name":"app-3-java","service.version":"0.0.1-SNAPSHOT","service.environment":"npo","event.dataset":"app-3-java.CONSOLE","process.thread.name":"org.springframework.jms.JmsListenerEndpointContainer#0-1","log.logger":"nl.xxx.healthcheck.poc.api.MyController","transaction.id":"414e81172c54699e","trace.id":"1b751e269027419c5d29d1f34a4bb110"}

{"@timestamp":"2023-06-29T09:44:02.949Z","log.level": "INFO","message":"Getting info from app4","ecs.version": "1.2.0","service.name":"app-3-java","service.version":"0.0.1-SNAPSHOT","service.environment":"npo","event.dataset":"app-3-java.CONSOLE","process.thread.name":"http-nio-8080-exec-6","log.logger":"nl.xxx.healthcheck.poc.api.MyController","transaction.id":"ce69bdfbf3b9cdb2","trace.id":"52616fc9f61319d5d638ff0dde9cfe6c"}

{"@timestamp":"2023-06-29T09:44:03.007Z","log.level": "INFO","message":"Getting info from app5","ecs.version": "1.2.0","service.name":"app-3-java","service.version":"0.0.1-SNAPSHOT","service.environment":"npo","event.dataset":"app-3-java.CONSOLE","process.thread.name":"http-nio-8080-exec-6","log.logger":"nl.xxx.healthcheck.poc.api.MyController","transaction.id":"ce69bdfbf3b9cdb2","trace.id":"52616fc9f61319d5d638ff0dde9cfe6c"}`

### Kibana >>
![image](https://github.com/elastic/apm-agent-java/assets/44557739/34f07835-b531-48d6-bdb8-94cc5ccf7e44)
![image](https://github.com/elastic/apm-agent-java/assets/44557739/292e6de9-4a10-4c9a-a7d0-a8e1e0fcad87)

**Comment by LeaTaka** [comment] 2023-06-29 10:04
Seems to be working, excellent work! 
Please let me know when you plan to release the final fix.

**Comment by SylvainJuge** [comment] 2023-06-30 08:04
Hi @LeaTaka you can subscribe to the notifications to know when #3198 is merged and when a new release is available.

**Comment by LeaTaka** [comment] 2023-07-03 18:45
@SylvainJuge Heads-up: I could be wrong but it seems that elastic-apm-agent-1.39.1-SNAPSHOT.jar impacts ELASTIC_APM_LOG_SENDING.

**Comment by SylvainJuge** [comment] 2023-07-06 12:27
@LeaTaka I've tested the log sending locally and its working as expected on my side, could you try it with the latest release 1.39.0 and see if you have something in the "Observability > Logs > Log Stream" view in Kibana ? (here you might miss the trace correlation, but it should still be part of the global log stream, or even the per-service stream).
If you still experience any issue here I would suggest we discuss this further [in the forum](https://discuss.elastic.co/) or by creating another bug report as it seems to be a separate issue from the JMS support this issue is about.

**Comment by LeaTaka** [comment] 2023-07-10 08:48
Cool @SylvainJuge. When I come across smt related, I will file a separate bug report. 
For now I do not have much time left to do further testing, so I leave it there. I might have seen it wrong. 

Anyways good that you have it covered! Cheers 👌

**Closed** 2023-07-12 14:24 UTC
Labels: instrumentation, agent-java, community

**Comment by marinkton** [comment] 2023-07-19 12:17
@jackshirazi@SylvainJuge,

Could you please reopen this bug issue? I wasn't available for the past two weeks, but now I'm back. We've tested the new snapshot version and it works well with Spring Boot, but unfortunately, we're encountering issues with open liberty. You can download the zip file [this link](https://drive.google.com/file/d/15_Q7hq4_xWN4Z0iHXcb2aIORPaQDz9aQ/view?usp=sharing) .

By the way, you can ignore the dockerfile in the project.

To build the project, simply run mvn clean install, and to run it, use mvn liberty:dev. If needed, you can modify the property values in liberty/config/server.env.

Thanks in advance!

**Comment by jackshirazi** [comment] 2023-07-19 12:26
Please try with the just released 1.40.0. If it works with Spring but not open liberty it's a different bug - so in that case please open a separate issue
