### ISSUE TITLE
Spring WebFlux support

### ISSUE THREAD

**Issue by prafsoni** [elastic/apm-agent-java#60] opened 2018-04-16 12:40 UTC
I don't know if this is a correct place for a feature request. Please add support for Spring WebFlux Framework too along with Web MVC. The new frameworks provide native support to build reactive web services. We are currently considering and moving towards Webflux, support in a future release will be awesome.

**Comment by felixbarny** [comment] 2018-04-16 12:42
Hi and thanks for that feature request. We definitely do consider adding support for this, however it is not targeted for version 1 which we see as a production ready MVP which supports auto instrumentation via `-javaagent`. Once we are at that stage, we will add support for more frameworks.

**Comment by felixbarny** [comment] 2018-04-16 12:44
Make sure to fill out the survey if you did not already: https://docs.google.com/forms/d/e/1FAIpQLScd0RYiwZGrEuxykYkv9z8Hl3exx_LKCtjsqEo1OWx8BkLrOQ/viewform

We use the results to prioritize framework support.

**Comment by prafsoni** [comment] 2018-04-16 12:52
Thanks, filled the survey. Maybe 1.1 will have support for this?

**Comment by felixbarny** [comment] 2018-04-17 12:07
I can't promise anything at this stage, but spring web reactive is currently the most requested reactive web framework in terms of agent support, so we will probably work on it soon after 1.0.

**Comment by prafsoni** [comment] 2018-04-17 13:48
Cool, is there a roadmap for 1.0 or it will be ready when it’s ready?

**Comment by felixbarny** [comment] 2018-04-23 07:14
The roadmap is basically the issues + milestones. However, there is no fixed date for 1.0/GA.

**Comment by prafsoni** [comment] 2018-04-23 11:55
Gotcha!

**Comment by felixbarny** [comment] 2018-05-15 09:00
The roadmap is just GitHub issues + milestones. Note that there is not much for post GA yet. Anything, in particular, you are interested in?

**Comment by digz6666** [comment] 2018-05-15 09:03
@felixbarny Yes I'm interested to know about what features are currently ready and what is coming on what version. And also want to know about the general architecture, if someone wants to contribute by sending pull request, where he or she might look for things that could be done.

**Comment by b0c1** [comment] 2018-10-15 09:51
It will contain both annotation and functional API?

**Comment by felixbarny** [comment] 2018-10-15 11:03
Ideally, yes. But we have not started working on this feature and I don't have a lot of insight into the framework's internals yet.

**Comment by felixbarny** [comment] 2018-10-15 11:05
@digz6666 FYI, we have added a [CONTRIBUTING.md](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md) which also links to an architecture overview.

**Comment by zhongdj** [comment] 2019-05-24 03:26
any progress on this?

**Comment by felixbarny** [comment] 2019-05-24 06:56
Unfortunately not. Make sure to 👍 the OP

**Comment by nerddelphi** [comment] 2019-08-21 14:34
Is there any roadmap to support that? I'm getting an issue related to WebFlux: https://discuss.elastic.co/t/java-agent-doesnt-generate-any-span-transaction-using-spring-cloud-gateway/196120

**Comment by felixbarny** [comment] 2019-08-21 16:12
It's currently in the backlog and it's unclear when we will get to it.

**Comment by lreuven** [comment] 2019-10-08 07:10
closing dup https://github.com/elastic/apm-agent-java/pull/827

**Comment by kevchandler** [comment] 2020-01-30 09:43
any update on when this might get implemented?

**Comment by eyalkoren** [comment] 2020-01-30 10:31
No concrete date or version, but it is definitely on the radar

**Comment by georglundesgaard** [comment] 2020-02-06 18:46
Do you need any help on this? This is a much needed feature for us, so it would be great to have it. I haven't worked with the apm agent or any JVM agents per se, but that shouldn't be to much of a hurdle I hope. I could do some tinkering with the code and try to get something to work and submit a pull request to this project.

What is the biggest challenge with implementing support for WebFlux? Is it the asynchronous nature of the reactive requests that pose the biggest challenge?

**Comment by felixbarny** [comment] 2020-02-07 07:27
There's a PR for it already from the community but I'm not sure about it's state: https://github.com/elastic/apm-agent-java/pull/827

Spring WebFlux is quite high on our priority list of things to tackle next.

**Comment by RubiHali** [comment] 2020-03-11 11:39
Any update when this will be released. We want to use Elastic APM but due to no support for webflux, we are not able to use it and all our apis are on web flux. It will help if we can release the change early.

**Comment by PGoski** [comment] 2020-06-08 19:56
I've improved https://github.com/elastic/apm-agent-java/pull/827 and made apm-spring-weblux to work with real life app, added netty support also:
code:
https://github.com/PGoski/apm-agent-java/tree/mb-add-spring-webflux-plugin

jar for testing:
https://github.com/PGoski/apm-agent-java/releases/tag/1.16.1-SNAPSHOT

**Comment by subeenn** [comment] 2020-09-15 10:18
@SylvainJuge We dont see any update on PR in last 2 months. Could you please provide an update on this? Badly waiting for this feature.

**Comment by SylvainJuge** [comment] 2020-09-15 14:53
@subeenn Yes, it hasn't been updated in an while, but I should get back to it soon. Also, please note that PR https://github.com/elastic/apm-agent-java/pull/1305 will replace this one as it's more exhaustive.

**Comment by dzmitryvarabyou** [comment] 2020-10-29 12:20
Waiting for this also. Any updates so far?

**Comment by nhogan5** [comment] 2020-11-16 00:30
With reactive programming becoming more mainstream it seems like this should be coming up pretty soon. Any expectations for this feature?

**Comment by eyalkoren** [comment] 2020-11-16 08:29
It is still ranked very high in our prioritizations, so we expect to get back to that some time soon.

**Comment by lborisevich-clgx** [comment] 2021-01-20 19:45
Any updates? Really waiting for this one

**Comment by SylvainJuge** [comment] 2021-01-21 08:11
No update so far, but I can confirm it's still high priority. I will dedicate some time to focus on this in the coming weeks thus stay tuned.

**Comment by skypiri** [comment] 2021-04-19 09:44
Waiting for this also, Any updates?

**Comment by SylvainJuge** [comment] 2021-04-19 12:12
We have made good progress on this and the PR is currently in review : https://github.com/elastic/apm-agent-java/pull/1305

The two plugins in this PR (reactor+webflux) are `experimental` right now, and will likely be shipped as-is once the PR is merged.
That means that those will be disabled by default and you need to set `disable_instrumentations=` (empty string) to enable it ([doc](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-disable-instrumentations))

**Closed** 2021-05-28 07:32 UTC
Labels: focus, instrumentation, new-feature
