### ISSUE TITLE
Unexpected side-effect of sampling profiler with file copy within transaction

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#3119] opened 2023-04-21 14:02 UTC
When the following conditions are met, there are unexpected side-effects on file copy operations
- Java agent attached with `-javaagent`
- Sampling profiler enabled `elastic.apm.profiling_inferred_spans_enabled=true`
- within an active transaction `elastic.apm.trace_methods=Main#transactionMethod`
- trying to copy a rather large file, above ~50 mb with using `FileChannel` (could also happen with other APIs, but I haven't tested yet).

The issue was initially reported when deploying a `.war` on tomcat through the `manager` webapp (by providing the path to the .war to deploy, not using upload), but in fact the is not Tomcat specific.

One of the likely reasons this was not detected reported earlier is because large file copy operations are rarely triggered from a transaction, and that the used API might not be the most commonly used.

The following code allows to reproduce the issue by creating a 100mb file and trying to copy it, when the sampling profiler is enabled the file copy is less than expected (about ~51mb, but the actual value and threshold to trigger might be OS-dependant).
```
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

public class Main {

    public static void main(String[] args) {

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            // ignored
        }

        // needs to be within a transaction
        transactionMethod();
    }

    private static void transactionMethod() throws IllegalStateException, RuntimeException {

        Path tmp = Paths.get(System.getProperty("java.io.tmpdir"));
        Path source = tmp.resolve("source");
        Path destination = tmp.resolve("destination");

        try {
            Files.deleteIfExists(source);
            Files.deleteIfExists(destination);

            // generate a ~100mb source file
            byte[] data = new byte[100*1024*1024]; // 100mb of zeroes
            Files.write(source, data, StandardOpenOption.CREATE, StandardOpenOption.APPEND);

            // those few lines emulates the way tomcat copies the .war file before deployment
            // in org.apache.catalina.startup.ExpandWar.copy
            try (FileChannel ic = (new FileInputStream(source.toFile())).getChannel();
                 FileChannel oc = (new FileOutputStream(destination.toFile())).getChannel()) {
                ic.transferTo(0, ic.size(), oc);
            }

            if (Files.size(source) != Files.size(destination)) {
                // will be thrown for large files when within a transaction + sampling profiler enabled
                throw new IllegalStateException("file size do not match !!");
            }

        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        System.out.println("that's fine !");
    }
}
```

**Comment by felixbarny** [comment] 2023-04-21 16:51
Does the issue also happen with async-profiler 2.x?

**Comment by jackshirazi** [comment] 2023-04-25 16:12
doesn't reproduce on `Ubuntu 22.04.2`, does on `RHEL 9.0`

**Comment by jackshirazi** [comment] 2023-04-26 15:34
> Does the issue also happen with async-profiler 2.x?

I did a basic swap-in replacement (so the profile data failed to get populated, but the profiler did run), and the failure is the same

**Comment by jackshirazi** [comment] 2023-04-26 15:35
Note that although on RHEL the failure is reproducible, it occasionally doesn't happen and the file copy completes

**Comment by jackshirazi** [comment] 2023-04-28 11:57
Finally made progress by going down to the native calls and back up ... only to find it's a tomcat bug which Sylvain perfectly reproduced. I've opened a [tomcat PR](https://github.com/apache/tomcat/pull/612) with a proposed fix.

Basically, tomcat calls `FileChannel.transferTo()` just once, assuming it will complete the file transfer, but here it only does a partial transfer, so it needs to loop to complete the transfer. The reason this is seen here and not in most tomcat deployments is that async-profiler installs signal handlers for signals, and the CPU time slicer signals (it could really be any signal, but I'm seeing the CPU time slicing in my tests) which interrupts the file copy transfer so that only part of it gets transferred. I guess most WARs are small enough and the OS call efficient enough that you need a particular combination to get the transfer interrupted like this (it looks like it needs the profiler to be active at the time of the transfer, but I couldn't be certain because of the overhead `strace` imposes which meant it was really hard to reproduce the bug with `strace` running).

Workaround alternatives:
- turn off the profiler
- reduce the frequency of the profiler
- patch the tomcat installation with the one file change per the [PR](https://github.com/apache/tomcat/pull/612)

**Closed by jackshirazi** 2023-04-28 11:57 UTC
Labels: bug, agent-java, 8.9-candidate
