### ISSUE TITLE
metaDataMap doesn't seem to work

### ISSUE THREAD

**Issue by LeePui** [elastic/apm-agent-java#2517] opened 2022-03-16 12:39 UTC
APM version : 1.26.0
I found that each time I execute sql, it will execute `select user` first.
I use arthas trace `co.elastic.apm.agent.jdbc.helper.JdbcHelper#getConnectionMetaData`, i found every time it will execute `ConnectionMetaData connectionMetaData = metaDataMap.get(connection);` --> `connectionMetaData = ConnectionMetaData.create(metaData.getURL(), connection.getCatalog(), metaData.getUserName());` --> `metaDataMap.put(connection, connectionMetaData);`, GC runs every 4 seconds

**Comment by SylvainJuge** [comment] 2022-03-16 12:57
Hi @LeePui , which JDBC driver and connection-pool are you using here ?

Some drivers do execute a SQL query to get the database metadata, but here there should be some caching provided by `metaDataMap`, unless the `Connection` object does not remain the same.

Could you provide the following please ?
- jdbc driver used
- connection-pool used + its configuration

If the GC is able to clear the content of `metaDataMap`, then it means that the keys have been GCs, which means that the `Connection` objects that were used were ephemeral and short-lived, thus they would effectively bypass the cache.

**Comment by LeePui** [comment] 2022-03-17 02:04
> 
Thank you for your prompt reply.
jdbc driver : `mysql-connector-java 5.1.45`
connection-pool : `druid 1.1.16`
druid configuration (DruidDataSource): 
```
initialSize : 5,
maxActive : 20
minIdle : 5,
phyTimeoutMillis : 7200000,
testWhileIdle : true,
timeBetweenEvictionRunsMillis : 60000,
minEvictableIdleTimeMillis : 300000,
maxEvictableIdleTimeMillis : 300000
```
My application gc about every 4 seconds during peak period, but the frequency of executing `select user` is much higher than this. 

I use arthas : `trace co.elastic.apm.agent.jdbc.helper.JdbcHelper#getConnectionMetaData`
![image](https://user-images.githubusercontent.com/14257862/158721765-28197fd7-924f-40f6-aef2-fe7ef280c33d.png)
It looks like it can't get the cache in the map every time.

**Comment by eyalkoren** [comment] 2022-03-27 13:43
@LeePui Please upgrade to the latest version (1.30.0) and report back whether it resolves the issue.
A lot has changed since 1.26.0 was released. 
For example, it contains #1820 but does not contain a related fix that seems very relevant - #2340 .
Thanks!

**Comment by eyalkoren** [comment] 2022-04-03 13:18
@LeePui please let us know whether this issue is still relevant with the latest version, or close it if already resolved.
Thanks.

**Comment by eyalkoren** [comment] 2022-04-05 10:49
Closing this due to lack of feedback, assuming that the issue is resolved with latest versions.
Feel free to reopen if this is not true.

**Closed by eyalkoren** 2022-04-05 10:49 UTC
Labels: agent-java, community, triage
