### ISSUE TITLE
Support JAX-RS Async API

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#713] opened 2019-07-09 13:27 UTC
Related to https://discuss.elastic.co/t/jaxrs-async-distrubuted-tracing-not-works/189531.

No trace context propagation when using the async JAX-RS API, as follows:
```
client.target(url).request().async().get();
```

We currently don't have dedicated support to JAX-RS client through the API, as decided and documented in elastic/apm-agent-java#200 .

Instead, we decided to rely on our `HttpUrlConnection` instrumentation, which works well for sync requests and async requests that make use of the Java Executors. The older (1.x) `com.sun` Jersey implementation seems to rely on them, but not the newer (2.x) `org.glassfish` implementation. For the latter, it should be easy to add support by applying the Executor instrumentation to `org.glassfish.jersey.client.ClientExecutor`.

Other than Jersey, we may include RESTEasy as well in this issue.

**Comment by kananindzya** [comment] 2019-07-11 12:17
Hello @eyalkoren , I will take this one.

**Comment by eyalkoren** [comment] 2019-07-11 12:38
@kananindzya awesome! ❤️ Thanks!

**Comment by felixbarny** [comment] 2019-07-18 14:14
`org.glassfish.jersey.client.ClientExecutor` uses `ExecutorService`s under the hood, so I'm not sure what's missing here.

Without reproducing the problem mentioned in https://discuss.elastic.co/t/jaxrs-async-distrubuted-tracing-not-works/189531 and understanding the root cause, I think it's a bit premature to attempt a fix.

**Comment by eyalkoren** [comment] 2019-08-08 10:42
Lowering priority as we can't reproduce that.
Asked the user again to try and find concrete details. If we get them, we can revisit.

**Comment by lreuven** [comment] 2019-10-08 07:34
closing, can't reproduce.

**Closed by lreuven** 2019-10-08 07:34 UTC
Labels: [zube]: Ready, type: bug
