### ISSUE TITLE
JVM performance counters monitoring

### ISSUE THREAD

**Issue by mdindoffer** [elastic/apm-agent-java#322] opened 2018-11-20 07:30 UTC
A vital part of any Java APM is JVM performance reporting. The Elastic Java agent in its current state does not gather JVM performance data. We have to monitor things like Heap usage, GC pauses, etc. using a separate JMX solution.

It would be great if the Java APM could gather all the traditional JVM metrics:
* GC stats (pauses, generations)
* Heap, Permgen, Metaspace usage
* Thread counts (daemon, normal)
* Classloader stats

We've looked at the [Elastic Metrics](https://www.elastic.co/solutions/metrics), but it seems it  doesn't gather data from inside a JVM, only from the host OS.

**Comment by felixbarny** [comment] 2018-11-20 07:32
Hi and thanks for your input. This is something we will be working on in the near future.

Closing as duplicate of #112

**Closed by felixbarny** 2018-11-20 07:32 UTC

**Comment by felixbarny** [comment] 2018-11-20 13:44
In the meantime, this blog may be relevant to you: https://www.elastic.co/blog/monitoring-java-applications-with-metricbeat-and-jolokia

**Comment by mdindoffer** [comment] 2018-11-20 15:11
Thanks for the link, we will look into the jolokia solution. But afaik it involves creating our own field-jmx mappings and dashboards, which isn't really appealing.
Is there any rough ETA for the JVM metrics? Can we expect GA in say a couple of months?
