### ISSUE TITLE
Improper life cycle management in async servlet API

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#584] opened 2019-04-15 15:20 UTC
The `/async-start-servlet` test case logs warnings. The transaction is activated 3 times but deactivated 4 times.

```
[2019-04-15T11:43:21.683Z] [jetty] [qtp1983025922-26] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00
-00000000000000000000000000000000-9c3a3bf78adb2a20-00 on thread 26
[2019-04-15T11:43:21.683Z] [jetty] [qtp1983025922-26] WARN co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating a span ('' 00-00000000000000000000000000000000-9c3a3bf78adb2a20-00) which is not the currently active span (null). This can happen when not properly deactivating a previous span.
[2019-04-15T11:43:21.683Z] [jetty] [qtp1983025922-26] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-00000000000000000000000000000000-9c3a3bf78adb2a20-00 on thread 26
[2019-04-15T11:43:21.683Z] [jetty] [qtp1983025922-26] WARN co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating a span ('' 00-00000000000000000000000000000000-9c3a3bf78adb2a20-00) which is not the currently active span (null). This can happen when not properly deactivating a previous span.
```

We should enable assertions in the servlet containers so this fails integration tests

**Comment by eyalkoren** [comment] 2019-04-23 13:46
Actually the lifecycle is mostly managed properly - activated and deactivated properly on the initiating thread and ended exactly once in all scenarios. 
On the worker thread, things are a bit more complicated- some servlet containers wrap the already-wrapped-Runnable (the one we wrap during `AsyncContext#start`) and submit to an `ExecutorService`. If we instrument this `ExecutorService`, then the servlet-container-Runnable-wrapper escapes our check and gets wrapped again. In such scenarios, the Transaction gets activated and deactivated twice **properly**. The problem is with https://github.com/elastic/apm-agent-java/blob/5dce1606f5a328d113216659716ff5cce1c63485/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/ElasticApmTracer.java#L482 where the first activation clears the stack and the second gets it empty.

We should probably get rid of this stack clearance. Instead, we can force a certain order of deactivate/end only for Transactions, and make the stack check-and-clear on `Transaction#end`.

In any case, I am adding two checks for this kind of situations:
1. Avoid activating already active spans in the Runnable/Callable wrappers
2. Avoid wrapping a wrapped Runnable/Callable by maintaining a thread-local state in the entry and exit of instrumented methods where we do wrapping

In addition, Jetty and Payara exposed another problem- `AsyncContext#complete` is called on the same thread that runs the Runnable, so it deactivates the Transaction before `Runnable#run` is ended and on the same thread. The fix for this is not deactivating spans from the `AsyncContexListener` explicitly when invoking https://github.com/elastic/apm-agent-java/blob/21d64124fa20cd0aa18bd6932d08eb9d33a313b3/apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletTransactionHelper.java#L164

**Closed** 2019-04-24 10:12 UTC
Labels: [zube]: In Review, type: bug
