### ISSUE TITLE
 Elastic APM Standalone attach | ERROR Unable to attach to JVM with PID

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-java#1751] opened 2021-04-08 07:27 UTC
Hi,

I'm trying to instrument a Jboss module with the elastic apm standalone attach (version 1.22)

I got this error

```
2021-04-08 09:20:09.379  INFO Attaching the Elastic APM agent to 86341 /opt/software/jboss/jboss-modules.jar -Djboss.modules.system.pkgs=com.sun.java.swing -Dlogging.configuration=file:/opt/software/jboss/bin/jboss-cli-logging.properties with arguments {service_name=batch-runner, server_url=http://localhost:8200}

2021-04-08 09:20:11.113 ERROR Unable to attach to JVM with PID = 86341

java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@244038d0

        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)

        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:273)

        at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:170)

        at co.elastic.apm.attach.RemoteAttacher.onJvmStart(RemoteAttacher.java:131)

        at co.elastic.apm.attach.RemoteAttacher.attachToNewJvms(RemoteAttacher.java:114)

        at co.elastic.apm.attach.RemoteAttacher.main(RemoteAttacher.java:92)

Caused by: java.lang.reflect.InvocationTargetException

        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:497)

        at co.elastic.apm.attach.bytebuddy.agent.Attacher.install(Attacher.java:110)

        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)

        ... 5 more

Caused by: java.lang.NumberFormatException: For input string: ""

        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)

        at java.lang.Integer.parseInt(Integer.java:592)

        at java.lang.Integer.parseInt(Integer.java:615)

        at co.elastic.apm.attach.bytebuddy.agent.VirtualMachine$ForHotSpot.checkHeader(VirtualMachine.java:277)

        at co.elastic.apm.attach.bytebuddy.agent.VirtualMachine$ForHotSpot.load(VirtualMachine.java:365)

        at co.elastic.apm.attach.bytebuddy.agent.VirtualMachine$ForHotSpot.loadAgent(VirtualM
```

**Comment by WassimDhib** [comment] 2021-04-08 07:39
Java version :

```
openjdk version "1.8.0_65"

OpenJDK Runtime Environment (build 1.8.0_65-b17)

OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
```

**Comment by WassimDhib** [comment] 2021-04-08 08:17
I tried to disable cheks, `elastic.apm.disable_bootstrap_checks=true`
But I still have the same error

**Comment by SylvainJuge** [comment] 2021-04-08 12:57
Hi @WassimDhib,

There are quite a few things to check:
- does the system user that runs the attach command you shown is the same system user that runs the JVM process ?
- does attaching the agent through the `-javaagent` parameter works as expected ? In other words, is that only unique to the runtime attach setup method or does the agent works properly with other setup methods ?

We recently merged https://github.com/elastic/apm-agent-java/pull/1667 that will for example allow to execute proper `sudo` command if required to use the same user as the one running the JVM, which is common error.

**Comment by WassimDhib** [comment] 2021-04-08 13:10
Hi @SylvainJuge 

Yes the attach command is running under the same system user that runs the JVM process
Yes it works with `-javaagent` parameter

**Comment by felixbarny** [comment] 2021-04-13 14:48
@WassimDhib please try with the [`--without-emulated-attach`](https://www.elastic.co/guide/en/apm/agent/java/current/setup-attach-cli.html#setup-attach-cli-usage-options) option. Note that this requires a full JDK installation, a JRE won't suffice.

Internal note: Maybe we should automatically re-try attachment without emulated attach if the former fails?

**Comment by SylvainJuge** [comment] 2021-04-19 13:44
@felixbarny since you discusses this with Rafael recently, if I remember correctly the conclusion was:
- we could automatically retry with/without the emulated attach when it fails
- we should try without the emulated attach by default, then try with it if it fails (this is the part I'm not 100% certain about).

**Comment by felixbarny** [comment] 2021-04-19 15:57
Rafael recommended using the emulated attach last. That's also how the `ByteBuddyAgent.AttachmentProvider.DEFAULT` is set up: https://github.com/raphw/byte-buddy/blob/8c0be529eec02d52d5617c10ccc11763b4bf0a67/byte-buddy-agent/src/main/java/net/bytebuddy/agent/ByteBuddyAgent.java#L758-L764

I think my rationale for using it first was that it works better when the JVM the attacher runs with differs from the target JVM. In that case, the `AttachmentProvider` would return true when calling `AttachmentProvider.Accessor::isAvailable` but fail once actually doing the attachment.

What we could do is to have two attachment providers: the first would be similar to `ByteBuddyAgent.AttachmentProvider.DEFAULT` but without the emulated attach. If the attachment fails with this provider, we should re-try with `ForEmulatedAttachment.INSTANCE`.

@raphw Does that make sense? Would it make sense to internalize that into Byte Buddy, making cross-JVM attachment more robust out-of-the-box?

**Comment by raphw** [comment] 2021-04-19 20:54
By default, Byte Buddy should already consider all approaches and only consider the first that seems to work. I thought about iterating them explicitly (make an install attempt with any strategy until one succeeds) but felt that this should typically be done by the user with logging opportunity. Let me think about making retrial the default. It would require some refactoring in the internal API.

I'd suggest just that: Attempt a regular attachment, use the emulation if it does not work. The advantage with the regular attachment is that it follows the VM version while emulation can lag behind when new versions of the JVM are released.

**Comment by eyalkoren** [comment] 2021-04-20 06:13
@WassimDhib can you confirm that attachment with a JDK and the `--without-emulated-attach` option works?

**Comment by WassimDhib** [comment] 2021-04-24 22:20
Hi


Sorry for the delay of my response.

I tested with a JDK (openjdk version "1.8.0_65")
with this command line :

`java -jar /var/opt/application/apm-agent-attach-1.22.0-standalone.jar     --include '.*myapplication.*'        --continuous     --config service_name=myapplication     --config server_url=http://localhost:8200 --without-emulated-attach`

I still have this error :

```
2021-04-25 00:13:34.266  INFO Attaching the Elastic APM agent to 72798 /opt/software/jboss/jboss-modules.jar -Djboss.modules.system.pkgs=com.sun.java.swing -Dlogging.configuration=file:/opt/software/jboss/bin/jboss-cli-logging.properties with arguments {service_name=batch-runner, server_url=http://localhost:8200}
2021-04-25 00:13:36.194 ERROR Unable to attach to JVM with PID = 72798
java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@7d6f77cc
        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)
        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:273)
        at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:170)
        at co.elastic.apm.attach.RemoteAttacher.onJvmStart(RemoteAttacher.java:131)
        at co.elastic.apm.attach.RemoteAttacher.attachToNewJvms(RemoteAttacher.java:114)
        at co.elastic.apm.attach.RemoteAttacher.main(RemoteAttacher.java:92)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at co.elastic.apm.attach.bytebuddy.agent.Attacher.install(Attacher.java:110)
        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
        ... 5 more
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at co.elastic.apm.attach.bytebuddy.agent.VirtualMachine$ForHotSpot.checkHeader(VirtualMachine.java:277)
        at co.elastic.apm.attach.bytebuddy.agent.VirtualMachine$ForHotSpot.load(VirtualMachine.java:365)
        at co.elastic.apm.attach.bytebuddy.agent.VirtualMachine$ForHotSpot.loadAgent(VirtualMachine.java:335)
        ... 11 more
```

**Comment by raphw** [comment] 2021-04-25 06:41
From the stack trace it seems as the emulation is still used.

**Comment by WassimDhib** [comment] 2021-04-25 11:10
I double checked my application. I turned out that it uses an other jdk (there was two jdk on this server)

It looks like an Oracle JDK
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```


So I changed the attach command line to user this one  : 
`/opt/software/java/bin/java  -jar /var/opt/application/apm-agent-attach-1.22.0-standalone.jar  --without-emulated-attach   ...`

but still have the same error 
 ```
2021-04-25 13:07:19.289 ERROR Unable to attach to JVM with PID = 108736
java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@5aaa6d82
        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)
        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:273)
        at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:170)
        at co.elastic.apm.attach.RemoteAttacher.onJvmStart(RemoteAttacher.java:131)
        at co.elastic.apm.attach.RemoteAttacher.attachToNewJvms(RemoteAttacher.java:114)
        at co.elastic.apm.attach.RemoteAttacher.main(RemoteAttacher.java:92)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at co.elastic.apm.attach.bytebuddy.agent.Attacher.install(Attacher.java:110)
        at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
        ... 5 more
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at co.elastic.apm.attach.bytebuddy.agent.VirtualMachine$ForHotSpot.checkHeader(VirtualMachine.java:277)
        at co.elastic.apm.attach.bytebuddy.agent.VirtualMachine$ForHotSpot.load(VirtualMachine.java:365)
        at co.elastic.apm.attach.bytebuddy.agent.VirtualMachine$ForHotSpot.loadAgent(VirtualMachine.java:335)
        ... 10 more

```

**Comment by eyalkoren** [comment] 2021-05-02 02:54
@WassimDhib version [1.23.0](https://www.elastic.co/guide/en/apm/agent/java/current/release-notes-1.x.html#release-notes-1.23.0) includes some considerable enhancements in the remote attachment mechanism. Please review the chances and try the new CLI tool, so we know we are looking at an issue that is relevant to the current state and handle it appropriately if it still exists.

**Comment by WassimDhib** [comment] 2021-05-08 00:48
`/opt/software/java/bin/java  -jar /var/opt/application/batchs/apm-agent-attach-cli-1.23.0.jar  --include-all  --continuous`


```

{"@timestamp":"2021-05-08T00:44:50.523Z", "log.level": "INFO", "message":"Attaching the Elastic APM agent to 98529 /opt/software/jboss/jboss-modules.jar with arguments {}", "ecs.version": "1.2.0","service.name":"java-attacher","event.dataset":"java-attacher.log","process.thread.name":"main","log.logger":"co.elastic.apm.attach.AgentAttacher"}


{"@timestamp":"2021-05-08T00:44:52.462Z", "log.level":"ERROR", "message":"Unable to attach to JVM with PID = 98529", "ecs.version": "1.2.0","service.name":"java-attacher","event.dataset":"java-attacher.log","process.thread.name":"main","log.logger":"co.elastic.apm.attach.AgentAttacher","error.type":"java.lang.IllegalStateException","error.message":"Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@8f2ef19","error.stack_trace":"java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@8f2ef19\n\tat net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)\n\tat net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:273)\n\tat co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:168)\n\tat co.elastic.apm.attach.AgentAttacher.attach(AgentAttacher.java:215)\n\tat co.elastic.apm.attach.AgentAttacher.onJvmMatch(AgentAttacher.java:192)\n\tat co.elastic.apm.attach.AgentAttacher.onJvmStart(AgentAttacher.java:177)\n\tat co.elastic.apm.attach.AgentAttacher.handleNewJvms(AgentAttacher.java:164)\n\tat co.elastic.apm.attach.AgentAttacher.handleNewJvmsLoop(AgentAttacher.java:139)\n\tat co.elastic.apm.attach.AgentAttacher.main(AgentAttacher.java:131)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat net.bytebuddy.agent.Attacher.install(Attacher.java:110)\n\tat net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)\n\t... 8 more\nCaused by: java.lang.NumberFormatException: For input string: \"\"\n\tat java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)\n\tat java.lang.Integer.parseInt(Integer.java:592)\n\tat java.lang.Integer.parseInt(Integer.java:615)\n\tat net.bytebuddy.agent.VirtualMachine$ForHotSpot.checkHeader(VirtualMachine.java:277)\n\tat net.bytebuddy.agent.VirtualMachine$ForHotSpot.load(VirtualMachine.java:365)\n\tat net.bytebuddy.agent.VirtualMachine$ForHotSpot.loadAgent(VirtualMachine.java:335)\n\t... 14 more\n"}
```

**Comment by SylvainJuge** [comment] 2021-06-02 09:27
Hi @WassimDhib , we released version 1.24.0 on Monday, but there was no changes related to runtime attach.

Since you mentioned having multiple JDKs installed on this system, would you mind executing the following commands to double-check all of them ?


```
# get java -version for the JVM you are using (to compare with others)
echo "$(readlink -f /opt/software/java/bin/java)"
/opt/software/java/bin/java --version


# will execute java -version on all running JVMs
sudo ps -ef | grep 'bin/java' | awk '!/grep/ {print $1;print $8;system($8  " -version");print "----"}'
```

**Comment by WassimDhib** [comment] 2021-06-02 23:33
et voilà

```
echo "$(readlink -f /opt/software/java/bin/java)"
/opt/software/java/bin/java



/opt/software/java/bin/java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)


sudo ps -ef | grep 'bin/java' | awk '!/grep/ {print $1;print $8;system($8  " -version");print "----"}'
app
/opt/software/java/bin/java
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
----
app
/opt/software/java/bin/java
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
----
app
/opt/software/java/bin/java
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by SylvainJuge** [comment] 2021-06-03 15:16
Update : I tried to reproduce this behavior with the following
- using a dedicated user account `app` that have no `sudo` nor any special privilege
- using a simple tomcat server as test application
- agent version 1.23.0 and 1.24.0
- using with & without `--without-emulated-attach` option
- try changing file ownership of the jdk folder (hypothesis being that maybe some filesystem rights could somehow influence how temporary files are creater in /tmp).

In all cases, the app is running as `app` user, and the app JVM is the same JVM used to attach.

With the `app` user and `--without-emulated-attach` option, I get the following exception, but it's not the same as yours
```
java.lang.IllegalStateException: The current accessor does not allow to attach to the current VM
  at co.elastic.apm.attach.GetAgentProperties.getAgentAndSystemPropertiesCurrentUser(GetAgentProperties.java:88)
  at co.elastic.apm.attach.GetAgentProperties.getAgentAndSystemProperties(GetAgentProperties.java:65)
  at co.elastic.apm.attach.AgentAttacher.<init>(AgentAttacher.java:73)
  at co.elastic.apm.attach.AgentAttacher.main(AgentAttacher.java:131)
```

Then, when trying to attach with `root` user, I get the following error, but it's due to having a Jetbrains Toolbox running on my machine, thus while it looks closer to what you reported, we are still not there yet.
```
java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@6d4d66d2
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:613)
  at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:273)
  at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:168)
  at co.elastic.apm.attach.AgentAttacher.attach(AgentAttacher.java:215)
  at co.elastic.apm.attach.AgentAttacher.onJvmMatch(AgentAttacher.java:192)
  at co.elastic.apm.attach.AgentAttacher.onJvmStart(AgentAttacher.java:177)
  at co.elastic.apm.attach.AgentAttacher.handleNewJvms(AgentAttacher.java:164)
  at co.elastic.apm.attach.AgentAttacher.handleNewJvmsLoop(AgentAttacher.java:139)
  at co.elastic.apm.attach.AgentAttacher.main(AgentAttacher.java:131)
Caused by: java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at net.bytebuddy.agent.Attacher.install(Attacher.java:110)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
  ... 8 more
Caused by: java.lang.IllegalStateException: java.lang.module.FindException: Module java.instrument not found
  at net.bytebuddy.agent.VirtualMachine$ForHotSpot.checkHeader(VirtualMachine.java:288)
  at net.bytebuddy.agent.VirtualMachine$ForHotSpot.load(VirtualMachine.java:365)
  at net.bytebuddy.agent.VirtualMachine$ForHotSpot.loadAgent(VirtualMachine.java:335)
  ... 14 more
```

**Comment by raphw** [comment] 2021-06-03 19:06
This can happen with a jlink-built version of the JVM that does not contain the java.instrument module. If you are creating a modular image from a jar with a *module-info*, only required modules will be included in the VM image. Often, the `java.instrument` module is not required as it is only used by agents. The consequence is that such images do not support instrumentation or agents. I had discussed this with the Oracle team as a potential problem, but I was not agreed with upon this issue and this is how things are.

You can manually require the *java.instrument* module when creating a modular VM, but you need to anticipate that you want to later attach an agent.

**Comment by felixbarny** [comment] 2021-06-15 11:51
> Let me think about making retrial the default. It would require some refactoring in the internal API.

@raphw Have you given that some more thought? If you're not keen on adding that to Byte Buddy we'd do that in our agent. Otherwise, we'd wait until it's in Byte Buddy.

**Comment by raphw** [comment] 2021-06-16 09:09
I think I will not add it for now. I have started a thought process, but I have not found a solution that I like just now. In theory, any viable attachment should work. I am afraid of swallowing errors if I simply retrial, but possibly, I will add explicit iteration methods at some point.

I recommend you to add your own mechanism for now.

**Comment by felixbarny** [comment] 2021-06-16 10:22
> I think my rationale for using it first was that it works better when the JVM the attacher runs with differs from the target JVM.

Maybe my whole premise was wrong here. Even with the emulated attach, it's not possible to attach to a J9 JVM from a hotspot JVM, for example. That's because [`net.bytebuddy.agent.VirtualMachine.Resolver#run`](https://github.com/raphw/byte-buddy/blob/e2299870a37109e1a411274e2e051a67dfcb7f31/byte-buddy-agent/src/main/java/net/bytebuddy/agent/VirtualMachine.java#L157-L159) doesn't consider the type of the target VM, just the type of the current VM.

So I guess there's no occasion where the emulated attach is preferable to the regular one. Unless maybe it would make attachment from, for example, OpenJDK 7 to OpenJDK 11 or vice-versa more robust. Or unless the type of the target VM is considered.

But for now, it seems the best option is just to use `net.bytebuddy.agent.ByteBuddyAgent.AttachmentProvider#DEFAULT`, right?

**Comment by raphw** [comment] 2021-06-16 11:08
Actually, it is possible to attach from HotSpot to (Open)J9 using the emulation. You would need to explicitly specify the J9 attachment as provider, though.

**Comment by SylvainJuge** [comment] 2021-06-16 11:51
> But for now, it seems the best option is just to use `net.bytebuddy.agent.ByteBuddyAgent.AttachmentProvider#DEFAULT`, right?

Changing the emulated attach option ordering means that we have to filter-out the accessors that require external attachment, otherwise we can't attach to the running JVM, otherwise the first available will get returned, I had to filter those order change PR https://github.com/elastic/apm-agent-java/pull/1865 https://github.com/elastic/apm-agent-java/blob/30dd812c77a8917e5134be9c129d9e4d8693f7ac/apm-agent-attach/src/main/java/co/elastic/apm/attach/ElasticAttachmentProvider.java#L111 

Which means that we could not reuse `AttachmentProvider#DEFAULT` value as-is.

**Comment by SylvainJuge** [comment] 2021-06-24 13:14
Update: we changed attachment provider ordering in https://github.com/elastic/apm-agent-java/pull/1865 (which is about to be merged).

From now on, the first native attachment provider that is available will be used, and emulated attach will only be used as last option. The `--without-emulated-attach` option has also been removed as it became useless. Previously emulated attachment provider was used with high priority when used.

I will add a link to a snapshot version here once it's merged for testing. @WassimDhib do you think you could check if that makes a difference in your case ?

**Comment by WassimDhib** [comment] 2021-06-25 12:33
@SylvainJuge I can give it a try

**Comment by SylvainJuge** [comment] 2021-06-29 08:10
Hi @WassimDhib , I'll close this issue for now as the related change has been merged.
Please re-open it (or add a comment) if it does not solve your issue so we can further investigate.

**Closed by SylvainJuge** 2021-06-29 08:10 UTC
Labels: agent-java, bug

**Comment by issamnacim** [comment] 2022-01-03 23:59
i changed to  <elastic-apm.version>1.28.4</elastic-apm.version>  but i still have the same error  => 
Caused by: java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@1b701da1


public static void main(String[] args) {
		ElasticApmAttacher.attach();
		SpringApplication.run(AutolabGatewayApplication.class, args);
	}

**Comment by SylvainJuge** [comment] 2022-01-04 15:12
Hi @issamnacim as this issue is closed it might definitely be better to open a new one for clarity as we aren't sure it's 100% the same issue here. Also, if this happens with version `1.28.4`  it might be a regression or something not related at all.

In order to make it easier/faster to solve your issue, could you please:
- open a separate issue
- provide the full stack trace in the issue description

Thanks in advance !

**Comment by issamnacim** [comment] 2022-01-04 17:31
Ok thnks @SylvainJuge  i oppened this issue ==> https://github.com/elastic/apm-agent-java/issues/2383
