### ISSUE TITLE
Monitoring for In-flight Requests / Jobs

### ISSUE THREAD

**Issue by danielfariati** [elastic/apm-agent-java#1055] opened 2020-02-26 18:43 UTC
Hi.

Correct me if I'm wrong, but I believe the APM only tracks requests / jobs after they are finished.
It would be awesome to have the possibility to monitor requests / jobs still in-flight.

I didn't think of it in depth, but what I thought so far, was:
Every _x_ seconds, a job checks if there are any requests running for more than _y_ seconds;
If there are requests exceeding that threshold, a ping in sent to the server specifying that the request is still alive (and all of the finished spans so far, but I don't know if that is possible);
If the request did not receive any ping after _z_ seconds, mark it as dead / cancelled;

It would also be nice if the values were configurable. Something like:
1. The amount of time the request have to be running for it to be sent to the APM Server;
2. The amount of time after the last received ping, to mark the request as dead (maybe this would have to be configurable in the server?);

This feature would probably consist of changes in both the agent and the server.

To give more information on _why_ I want this feature:
If this feature existed, we could determine *what* was running on the server when a server went down; For instance, let's say that there's a job that runs on the background and causes the JVM to crash; The way the APM works today, we don't have any way of knowing what was running when the JVM crashed, because the request never finished.

I know this will probably be very hard to do (if even possible), but I believe it would make an even more complete APM.

(Also, I don't know if this is the right project to open this request.)

**Comment by SylvainJuge** [comment] 2020-02-27 17:36
Hi @danielfariati 

We try to keep repository issues actionable, thus our forum is the best place to discuss new feature ideas. I have updated https://github.com/elastic/apm-agent-java#getting-help to make that a bit more clear.

If I understand your case, you have a server that executes long-running tasks (at least a few seconds), and you suspect that one of them is making the application crash.

While most things in APM UI are displayed per transaction, they are sent and stored separately by the agent (at least the Java one), thus I might be wrong, but you should be able to query spans by using the Discover tab in Kibana, which could provide a clue about what was currently being executed at the time of the crash.

Without more context and details about what are the application symptoms (JVM crash, OutOfMemoryError, high cpu usage, high garbage collector activity, ...), we can't know if the currently active transactions might be the cause of the application slowdown/crash.

For example, in case of a memory leak, memory usage will grow over time, and at some time GC will consume 100% of CPU without being able to free much memory, as a result, the transactions currently running will be slowed down, but are not the cause of it.

I will be closing this issue, but would be happy to discuss this further [in our forum](https://discuss.elastic.co/tags/c/apm/java)

**Closed by SylvainJuge** 2020-02-27 17:36 UTC
